### ISSUE TITLE
NoSuchMethodError: closeQuietly (Renjin 0.7.0-RC7, Guava 17.0)

### ISSUE THREAD

**Issue by lkorogodski** [bedatadriven/renjin#105]
java.lang.NoSuchMethodError: com.google.common.io.Closeables.closeQuietly(Ljava/io/Closeable;)V
	at org.renjin.primitives.packaging.ClasspathPackage.resourceExists(ClasspathPackage.java:59)
	at org.renjin.primitives.packaging.ClasspathPackageLoader.load(ClasspathPackageLoader.java:22)
	at org.renjin.primitives.packaging.NamespaceRegistry.tryLoad(NamespaceRegistry.java:149)
	at org.renjin.primitives.packaging.NamespaceRegistry.tryGetNamespace(NamespaceRegistry.java:143)
	at org.renjin.primitives.packaging.NamespaceRegistry.getNamespace(NamespaceRegistry.java:126)
	at org.renjin.primitives.packaging.NamespaceRegistry.getNamespace(NamespaceRegistry.java:116)
	at org.renjin.primitives.packaging.NamespaceRegistry.getNamespace(NamespaceRegistry.java:82)
	at org.renjin.primitives.packaging.Packages.library(Packages.java:23)
	at org.renjin.primitives.R$primitive$library.doApply(R$primitive$library.java from WrapperSource:70)
	at org.renjin.primitives.R$primitive$library.apply(R$primitive$library.java from WrapperSource:31)
	at org.renjin.eval.Context.evaluateCall(Context.java:261)
	at org.renjin.eval.Context.evaluate(Context.java:193)
	at org.renjin.eval.Context.evaluate(Context.java:161)
	at org.renjin.eval.SessionBuilder.build(SessionBuilder.java:72)
	at org.renjin.script.RenjinScriptEngineFactory.getScriptEngine(RenjinScriptEngineFactory.java:94)
	at org.renjin.script.RenjinScriptEngineFactory.getScriptEngine(RenjinScriptEngineFactory.java:14)
	at javax.script.ScriptEngineManager.getEngineByName(ScriptEngineManager.java:238)

when calling

new ScriptEngineManager().getEngineByName("Renjin")

Please note that this happens with the latest version of Renjin (0.7.0-RC7), which apparently uses Guava 17.0. Looking through the issue #55, I have noticed that it is believed that the upgrade to Guava 17.0 solves the issue, but this appears not to be the case.

**Comment by btrapp** [comment]
I found that moving to 0.7.0-RC8-SNAPSHOT fixes this issue, for what it's worth.

**Comment by lkorogodski** [comment]
Thanks! Looks like it does.

**Comment by mjkallen** [comment]
Please see https://groups.google.com/forum/m/#!topic/renjin-dev/RcBKzUauvbo for the latest news regarding builds: use RELEASE if you want to get the latest version in your project.
