### ISSUE TITLE
Implement ComplexVector.newCopyBuilder()

### ISSUE THREAD

**Issue by akbertram** [bedatadriven/renjin#11]
ERROR: implement mejava.lang.UnsupportedOperationException: implement me
	at org.renjin.sexp.ComplexVector.newCopyBuilder(ComplexVector.java:195)
	at org.renjin.sexp.ComplexVector.newCopyBuilder(ComplexVector.java:33)
	at org.renjin.primitives.subset.SubscriptOperation.createReplacementBuilder(SubscriptOperation.java:306)
	at org.renjin.primitives.subset.SubscriptOperation.replace(SubscriptOperation.java:238)
	at org.renjin.primitives.subset.Subsetting.setSubset(Subsetting.java:237)

**Comment by akbertram** [comment]
This has been [implemented](https://github.com/bedatadriven/renjin/blob/2f3a8e127c08273c29969eadb3a59177d5482ed4/core/src/main/java/org/renjin/sexp/ComplexVector.java#L86-L86).
