### ISSUE TITLE
Implement subst for fixed regular expressions

### ISSUE THREAD

**Issue by akbertram** [bedatadriven/renjin#16]
java.lang.UnsupportedOperationException: subst not yet implemented for fixed RE
	at org.renjin.primitives.text.regex.FixedRE.subst(FixedRE.java:53)
	at org.renjin.primitives.text.Text.sub(Text.java:292)
	at org.renjin.primitives.R$primitive$sub.doApply(R$primitive$sub.java from WrapperSource:147)
	at org.renjin.primitives.R$primitive$sub.apply(R$primitive$sub.java from WrapperSource:39)
	at org.renjin.primitives.special.InternalFunction.apply(InternalFunction.java:55)
	at org.renjin.eval.Context.evaluateCall(Context.java:251)
	at org.renjin.eval.Context.evaluate(Context.java:183)
	at org.renjin.primitives.special.BeginFunction.apply(BeginFunction.java:46)
	at org.renjin.eval.Context.evaluateCall(Context.java:251)
	at org.renjin.eval.Context.evaluate(Context.java:183)
	at org.renjin.eval.Context.evaluate(Context.java:160)
	at org.renjin.sexp.Closure.doApply(Closure.java:108)

**Comment by akbertram** [comment]
Fixed by @hannesmuehleisen in d9235dc339845f1f4fa2865a584d72c29246a584
