### ISSUE TITLE
Missing Fortran error handler API methods rchkuser_, rexit_, rwarn_

### ISSUE THREAD

**Issue by PavilVenugopal** [bedatadriven/renjin#161]
I am getting this error "object 'C_filter1' not found" on running the filter command "filter(rep(1,10),1,rep(35,1000))" from the package "signal".

**Comment by akbertram** [comment]
According to the 
[report page](http://packages.renjin.org/package/org.renjin.cran/signal) for this package, it looks like Renjin wasn't able to compile the C and Fortran sources:

> This package can be loaded by Renjin but there was an error compiling C/FORTRAN sources and 33 out 42 tests failed.

Digging into the [build log](http://packages.renjin.org/package/org.renjin.cran/signal/0.7-6/build/18), it looks like compilation specifically of dpchim.f failed with the error:

```
org.renjin.gcc.InternalCompilerException: Exception compiling function dpchim in unit dpchim.f.gimple
	at org.renjin.gcc.codegen.UnitClassGenerator.emitFunctions(UnitClassGenerator.java:163)
	at org.renjin.gcc.codegen.UnitClassGenerator.emit(UnitClassGenerator.java:115)
	at org.renjin.gcc.GimpleCompiler.compile(GimpleCompiler.java:166)
        ...
Caused by: java.lang.UnsupportedOperationException: Could not find function 'rexit_'
	at org.renjin.gcc.symbols.GlobalSymbolTable.findCallGenerator(GlobalSymbolTable.java:75)
	at org.renjin.gcc.symbols.UnitSymbolTable.findCallGenerator(UnitSymbolTable.java:104)
	at org.renjin.gcc.symbols.LocalVariableTable.findCallGenerator(LocalVariableTable.java:64)
	at org.renjin.gcc.codegen.expr.ExprFactory.findCallGenerator(ExprFactory.java:167)
	at org.renjin.gcc.codegen.FunctionGenerator.emitCall(FunctionGenerator.java:291)
	at org.renjin.gcc.codegen.FunctionGenerator.emitBasicBlock(FunctionGenerator.java:226)
	... 28 more
```

It [looks like](http://stackoverflow.com/questions/25747639/compiling-fortran-code-for-r-package-under-windows-undefined-reference-to-rexit) this is one of the error handling methods GNU R provides to Fortran sources.

**Comment by akbertram** [comment]
@psolaimani you can add to [Error.java](https://github.com/bedatadriven/renjin/blob/4990a73b76fe10749c510be5b715146cd21b104e/tools/gnur-runtime/src/main/java/org/renjin/gnur/api/Error.java)

**Comment by akbertram** [comment]
@psolaimani that's resolved the compilation problem with the signals package, but it looks like C_filter1 is actually defined in MASS, which is still failing the native compilation stage.

**Comment by akbertram** [comment]
@PavilVenugopal looks like your code is still not running, but I'd like to close the ticket for this particular issue. You can follow Issue #164 to get updates on when MASS is fixed, which signal and your code depends on.
