### ISSUE TITLE
unif_rand is not implemented

### ISSUE THREAD

**Issue by thorstenwagner** [bedatadriven/renjin#181]
I try to use renjin in one of my imagej plugins. Unfortunately, I got an exception:

> org.renjin.eval.EvalException: Unimplemented GNU R API function 'unif_rand'
	at org.renjin.primitives.Native.dotC(Native.java:92)
	at org.renjin.primitives.R$primitive$$C.apply(R$primitive$$C.java:70)
	at org.renjin.eval.Context.evaluateCall(Context.java:262)
	at org.renjin.eval.Context.evaluate(Context.java:194)
	at org.renjin.primitives.special.AssignLeftFunction.assignLeft(AssignLeftFunction.java:60)
	at org.renjin.primitives.special.AssignLeftFunction.apply(AssignLeftFunction.java:44)
	at org.renjin.eval.Context.evaluateCall(Context.java:262)
	at org.renjin.eval.Context.evaluate(Context.java:194)
	at org.renjin.primitives.special.BeginFunction.apply(BeginFunction.java:46)
	at org.renjin.eval.Context.evaluateCall(Context.java:262)
	at org.renjin.eval.Context.evaluate(Context.java:194)
	at org.renjin.primitives.special.IfFunction.apply(IfFunction.java:50)
	at org.renjin.eval.Context.evaluateCall(Context.java:262)
	at org.renjin.eval.Context.evaluate(Context.java:194)
	at org.renjin.primitives.special.BeginFunction.apply(BeginFunction.java:46)
	at org.renjin.eval.Context.evaluateCall(Context.java:262)
	at org.renjin.eval.Context.evaluate(Context.java:194)
	at org.renjin.eval.Calls.applyClosure(Calls.java:57)
	at org.renjin.primitives.S3$GenericMethod.doApply(S3.java:588)
	at org.renjin.primitives.S3$GenericMethod.apply(S3.java:575)
	at org.renjin.primitives.S3.UseMethod(S3.java:47)
	at org.renjin.primitives.S3.UseMethod(S3.java:39)
	at org.renjin.primitives.R$primitive$UseMethod.doApply(R$primitive$UseMethod.java:77)
	at org.renjin.primitives.R$primitive$UseMethod.apply(R$primitive$UseMethod.java:31)
	at org.renjin.eval.Context.evaluateCall(Context.java:262)
	at org.renjin.eval.Context.evaluate(Context.java:194)
	at org.renjin.eval.Context.evaluate(Context.java:162)
	at org.renjin.sexp.Closure.doApply(Closure.java:108)
	at org.renjin.eval.ClosureDispatcher.apply(ClosureDispatcher.java:76)
	at org.renjin.eval.ClosureDispatcher.applyClosure(ClosureDispatcher.java:61)
	at org.renjin.sexp.Closure.apply(Closure.java:82)
	at org.renjin.eval.Context.evaluateCall(Context.java:262)
	at org.renjin.eval.Context.evaluate(Context.java:194)
	at org.renjin.primitives.special.AssignLeftFunction.assignLeft(AssignLeftFunction.java:60)
	at org.renjin.primitives.special.AssignLeftFunction.apply(AssignLeftFunction.java:44)
	at org.renjin.eval.Context.evaluateCall(Context.java:262)
	at org.renjin.eval.Context.evaluate(Context.java:194)
	at org.renjin.eval.Context.evaluateExpressionVector(Context.java:253)
	at org.renjin.eval.Context.evaluate(Context.java:192)
	at org.renjin.script.RenjinScriptEngine.eval(RenjinScriptEngine.java:145)
	at org.renjin.script.RenjinScriptEngine.eval(RenjinScriptEngine.java:104)

It seems that the unif_rand functions is not implemented. It happens when I apply the predict function of the randomForest package.

This is my POM.XML:
https://gist.github.com/thorstenwagner/58629a3ebbddf32a72d28b0e5d8edbac

Any chance that it will be implemented soon?

Thanks in advance!

**Comment by thorstenwagner** [comment]
Wow! That was fast. Thanks!

**Comment by akbertram** [comment]
Does it work now?

**Comment by thorstenwagner** [comment]
Yes it does! Thanks again.

Cheers,
Thorsten
