### ISSUE TITLE
Master does not build

### ISSUE THREAD

**Issue by KIC** [bedatadriven/renjin#190]
I am not able to get the tools compiled, please see my maven logs
```
-------------------------------------------------------
 T E S T S
-------------------------------------------------------
Running org.renjin.maven.test.ForkedTestControllerTest
-------------------------------------------------------
 R E N J I N   T E S T S
-------------------------------------------------------
Running mean.Rd
No default packages specified
Evaluation of mean.Rd failed
Tests run: 1, Failures: 0, Errors: 1, Skipped: 0, Time elapsed: 1.346  << FAILURE!
-------------------------------------------------------
 R E N J I N   T E S T S
-------------------------------------------------------
Running successful.R
No default packages specified
Tests run: 3, Failures: 0, Errors: 0, Skipped: 0, Time elapsed: 1.487
-------------------------------------------------------
 R E N J I N   T E S T S
-------------------------------------------------------
Running infiniteOutput.R
No default packages specified
Evaluation of infiniteOutput.R timed out
Tests run: 1, Failures: 0, Errors: 1, Skipped: 0, Time elapsed: 3.002  << FAILURE!
Evaluation of infiniteOutput.R failed
Exception in thread "Thread-2" java.lang.NullPointerException
        at org.renjin.maven.test.ForkedTestController$ResultListener.run(ForkedTestController.java:184)
        at java.lang.Thread.run(Thread.java:745)
-------------------------------------------------------
 R E N J I N   T E S T S
-------------------------------------------------------
Running timeout.R
Evaluation of timeout.R timed out
Tests run: 1, Failures: 0, Errors: 1, Skipped: 0, Time elapsed: 1.001  << FAILURE!
-------------------------------------------------------
 R E N J I N   T E S T S
-------------------------------------------------------
Running outOfMemory.R
Evaluation of timeout.R failed
Exception in thread "Thread-3" java.lang.NullPointerException
        at org.renjin.maven.test.ForkedTestController$ResultListener.run(ForkedTestController.java:184)
        at java.lang.Thread.run(Thread.java:745)
No default packages specified
Exception in thread "main" java.lang.OutOfMemoryError: Java heap space
        at org.renjin.sexp.DoubleArrayVector$Builder.<init>(DoubleArrayVector.java:177)
        at org.renjin.sexp.DoubleArrayVector$Builder.withInitialCapacity(DoubleArrayVector.java:196)
        at org.renjin.stats.internals.distributions.RNG.runif(RNG.java:88)
        at org.renjin.primitives.R$primitive$runif.doApply(R$primitive$runif.java:75)
        at org.renjin.primitives.R$primitive$runif.apply(R$primitive$runif.java:36)
        at org.renjin.primitives.special.InternalFunction.apply(InternalFunction.java:55)
        at org.renjin.eval.Context.evaluateCall(Context.java:282)
        at org.renjin.eval.Context.evaluate(Context.java:206)
        at org.renjin.primitives.special.AssignLeftFunction.assignLeft(AssignLeftFunction.java:60)
        at org.renjin.primitives.special.AssignLeftFunction.apply(AssignLeftFunction.java:44)
        at org.renjin.eval.Context.evaluateCall(Context.java:282)
        at org.renjin.eval.Context.evaluate(Context.java:206)
        at org.renjin.primitives.special.BeginFunction.apply(BeginFunction.java:46)
        at org.renjin.eval.Context.evaluateCall(Context.java:282)
        at org.renjin.eval.Context.evaluate(Context.java:206)
        at org.renjin.primitives.special.ForFunction.apply(ForFunction.java:59)
        at org.renjin.eval.Context.evaluateCall(Context.java:282)
        at org.renjin.eval.Context.evaluate(Context.java:206)
        at org.renjin.repl.JlineRepl.readExpression(JlineRepl.java:175)
        at org.renjin.repl.JlineRepl.run(JlineRepl.java:107)
        at org.renjin.maven.test.TestExecutor.executeTestFile(TestExecutor.java:176)
        at org.renjin.maven.test.TestExecutor.executeTest(TestExecutor.java:110)
        at org.renjin.maven.test.TestExecutor.execute(TestExecutor.java:86)
        at org.renjin.maven.test.TestExecutor.main(TestExecutor.java:51)
Evaluation of outOfMemory.R failed
Forked JVM exited with code 1
Tests run: 1, Failures: 0, Errors: 1, Skipped: 0, Time elapsed: 1.197  << FAILURE!
Renjin 0.9.0-SNAPSHOT
Copyright (C) 2015 The R Foundation for Statistical Computing
Copyright (C) 2015 BeDataDriven
>
> ## Test that exceeds possible memory assigned to JVM...
>
> print("about to allocate gobs of memory!!")
[1] "about to allocate gobs of memory!!"
>
> x <- list()
> for(i in 1:100000) {
+     print(i)
+     x[[i]] <- .Internal(runif(2^28, 0, 1))
+ }
[1] 1

Running good.R
No default packages specified
Tests run: 1, Failures: 0, Errors: 0, Skipped: 0, Time elapsed: 0.806
Tests run: 5, Failures: 1, Errors: 0, Skipped: 0, Time elapsed: 10.579 sec <<< FAILURE!
Running org.renjin.maven.test.ExamplesParserTest
!!@@@@####START!!@@@@####(root)
No default packages specified
Could not load this project's namespace (it may not have one)
org.renjin.eval.EvalException: Could not load package foo; tried org.renjin.bioconductor:foo, org.renjin.cran:foo
        at org.renjin.primitives.packaging.NamespaceRegistry.getNamespace(NamespaceRegistry.java:133)
        at org.renjin.primitives.packaging.NamespaceRegistry.getNamespace(NamespaceRegistry.java:87)
        at org.renjin.primitives.packaging.Packages.library(Packages.java:23)
        at org.renjin.primitives.R$primitive$library.doApply(R$primitive$library.java:73)
        at org.renjin.primitives.R$primitive$library.apply(R$primitive$library.java:34)
        at org.renjin.primitives.special.InternalFunction.apply(InternalFunction.java:55)
        at org.renjin.eval.Context.evaluateCall(Context.java:282)
        at org.renjin.eval.Context.evaluate(Context.java:206)
        at org.renjin.primitives.special.BeginFunction.apply(BeginFunction.java:46)
        at org.renjin.eval.Context.evaluateCall(Context.java:282)
        at org.renjin.eval.Context.evaluate(Context.java:206)
        at org.renjin.eval.Context.evaluate(Context.java:162)
        at org.renjin.sexp.Closure.doApply(Closure.java:107)
        at org.renjin.eval.ClosureDispatcher.apply(ClosureDispatcher.java:76)
        at org.renjin.eval.ClosureDispatcher.applyClosure(ClosureDispatcher.java:61)
        at org.renjin.sexp.Closure.apply(Closure.java:81)
        at org.renjin.eval.Context.evaluateCall(Context.java:282)
        at org.renjin.eval.Context.evaluate(Context.java:206)
        at org.renjin.eval.Context.evaluate(Context.java:162)
        at org.renjin.maven.test.TestExecutor.loadLibrary(TestExecutor.java:128)
        at org.renjin.maven.test.TestExecutor.executeTestFile(TestExecutor.java:164)
        at org.renjin.maven.test.ExamplesParserTest.testInfiniteLoop(ExamplesParserTest.java:20)
        at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.lang.reflect.Method.invoke(Method.java:498)
        at junit.framework.TestCase.runTest(TestCase.java:154)
        at junit.framework.TestCase.runBare(TestCase.java:127)
        at junit.framework.TestResult$1.protect(TestResult.java:106)
        at junit.framework.TestResult.runProtected(TestResult.java:124)
        at junit.framework.TestResult.run(TestResult.java:109)
        at junit.framework.TestCase.run(TestCase.java:118)
        at junit.framework.TestSuite.runTest(TestSuite.java:208)
        at junit.framework.TestSuite.run(TestSuite.java:203)
        at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.lang.reflect.Method.invoke(Method.java:498)
        at org.apache.maven.surefire.junit.JUnitTestSet.execute(JUnitTestSet.java:96)
        at org.apache.maven.surefire.junit.JUnit3Provider.executeTestSet(JUnit3Provider.java:117)
        at org.apache.maven.surefire.junit.JUnit3Provider.invoke(JUnit3Provider.java:94)
        at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.lang.reflect.Method.invoke(Method.java:498)
        at org.apache.maven.surefire.util.ReflectionUtils.invokeMethodWithArray(ReflectionUtils.java:164)
        at org.apache.maven.surefire.booter.ProviderFactory$ProviderProxy.invoke(ProviderFactory.java:110)
        at org.apache.maven.surefire.booter.SurefireStarter.invokeProvider(SurefireStarter.java:175)
        at org.apache.maven.surefire.booter.SurefireStarter.runSuitesInProcessWhenForked(SurefireStarter.java:107)
        at org.apache.maven.surefire.booter.ForkedBooter.main(ForkedBooter.java:68)
!!@@@@####FAIL!!@@@@####
Tests run: 2, Failures: 0, Errors: 0, Skipped: 0, Time elapsed: 0.722 sec
Running org.renjin.maven.test.TestExecutorTest
!!@@@@####START!!@@@@####(root)
No default packages specified
!!@@@@####FAIL!!@@@@####
!!@@@@####DONE!!@@@@####
Tests run: 1, Failures: 0, Errors: 0, Skipped: 0, Time elapsed: 0.309 sec

Results :

Failed tests:   testInfiniteOutput(org.renjin.maven.test.ForkedTestControllerTest)

Tests run: 8, Failures: 1, Errors: 0, Skipped: 0

[INFO] ------------------------------------------------------------------------
[INFO] Reactor Summary:
[INFO]
[INFO] Renjin Parent ..................................... SUCCESS [20.026s]
[INFO] Renjin Tools ...................................... SUCCESS [0.159s]
[INFO] Renjin GCC Bridge Parent .......................... SUCCESS [0.151s]
[INFO] Renjin GCC Runtime ................................ SUCCESS [12.427s]
[INFO] Renjin Core ....................................... SUCCESS [1:32.763s]
[INFO] Renjin Common Math Routines ....................... SUCCESS [2.577s]
[INFO] Renjin GCC Bridge Plugin .......................... SUCCESS [5.986s]
[INFO] Renjin GCC Bridge Compiler ........................ SUCCESS [17.992s]
[INFO] Renjin GCC Bridge Maven Plugin .................... SUCCESS [14.913s]
[INFO] Renjin BLAS Library ............................... SUCCESS [11.687s]
[INFO] renjin-appl ....................................... SUCCESS [4.341s]
[INFO] Renjin GNU-R Runtime .............................. SUCCESS [4.257s]
[INFO] Renjin Packages Parent ............................ SUCCESS [0.151s]
[INFO] Renjin Read-Eval-Print-Loop ....................... SUCCESS [1.914s]
[INFO] Renjin GNU R Installation ......................... SUCCESS [1.318s]
[INFO] Renjin Packager ................................... SUCCESS [1.812s]
[INFO] Renjin GNU R Native Sources Compiler .............. SUCCESS [3.052s]
[INFO] Renjin Maven Plugin ............................... FAILURE [40.682s]
[INFO] hamcrest .......................................... SKIPPED
[INFO] grDevices ......................................... SKIPPED
[INFO] graphics .......................................... SKIPPED
[INFO] utils ............................................. SKIPPED
[INFO] stats ............................................. SKIPPED
[INFO] datasets .......................................... SKIPPED
[INFO] methods ........................................... SKIPPED
[INFO] Renjin Script Engine .............................. SKIPPED
[INFO] Renjin Test Packages Parent ....................... SKIPPED
[INFO] Dummy Renjin Package Alpha ........................ SKIPPED
[INFO] Dummy Renjin Package Beta ......................... SKIPPED
[INFO] renjin-aether-package-loader ...................... SKIPPED
[INFO] grid .............................................. SKIPPED
[INFO] tools ............................................. SKIPPED
[INFO] splines ........................................... SKIPPED
[INFO] parallel .......................................... SKIPPED
[INFO] stats4 ............................................ SKIPPED
[INFO] compiler .......................................... SKIPPED
[INFO] Renjin Command Line Interface ..................... SKIPPED
[INFO] AppEngine Support classes for Renjin .............. SKIPPED
[INFO] Dummy third party package ......................... SKIPPED
[INFO] Renjin Integration Tests .......................... SKIPPED
[INFO] Dummy third party package with conflicting name ... SKIPPED
[INFO] Dummy CRAN package with periods in the name ....... SKIPPED
[INFO] Test S4 package ................................... SKIPPED
[INFO] Test S3 package ................................... SKIPPED
[INFO] Dummy Renjin Package with Explict source order .... SKIPPED
[INFO] Dummy Renjin Package with Implicit source order ... SKIPPED
[INFO] Test package with data ............................ SKIPPED
[INFO] Test Package with native code ..................... SKIPPED
[INFO] Test Package linking against another package ...... SKIPPED
[INFO] tcltk ............................................. SKIPPED
[INFO] Renjin GCC Bridge Microbenchmarks ................. SKIPPED
[INFO] Renjin Studio ..................................... SKIPPED
[INFO] Renjin Standalone Platform-independent distribution  SKIPPED
[INFO] Renjin ............................................ SKIPPED
[INFO] Renjin Math Parent ................................ SKIPPED
[INFO] Renjin Math Micro Benchmarks ...................... SKIPPED
[INFO] ------------------------------------------------------------------------
[INFO] BUILD FAILURE
[INFO] ------------------------------------------------------------------------
[INFO] Total time: 3:57.251s
[INFO] Finished at: Mon Jun 13 16:13:24 UTC 2016
[INFO] Final Memory: 107M/179M
[INFO] ------------------------------------------------------------------------
[ERROR] Failed to execute goal org.apache.maven.plugins:maven-surefire-plugin:2.10:test (default-test) on project renjin-maven-plugin: There are test failures.
[ERROR]
[ERROR] Please refer to /root/renjin/tools/maven-plugin/target/surefire-reports for the individual test results.
[ERROR] -> [Help 1]
[ERROR]
[ERROR] To see the full stack trace of the errors, re-run Maven with the -e switch.
[ERROR] Re-run Maven using the -X switch to enable full debug logging.
[ERROR]
[ERROR] For more information about the errors and possible solutions, please read the following articles:
[ERROR] [Help 1] http://cwiki.apache.org/confluence/display/MAVEN/MojoFailureException
[ERROR]
[ERROR] After correcting the problems, you can resume the build with the command
[ERROR]   mvn <goals> -rf :renjin-maven-plugin

```

**Comment by KIC** [comment]
Sorry got it to work by doing the build and the test seperate:

```
mvn install -DskipTests -Dmaven.test.skip=true
mvn surefire:test

```

**Comment by akbertram** [comment]
Strange... though by doing this, you are skipping the tests written in R, which are run by the `renjin-maven-plugin` and not `surefire`. Can you share the output of `testInfiniteOutput(org.renjin.maven.test.ForkedTestControllerTest)`?

**Comment by KIC** [comment]
this is weird, when I make the maven build straight in my Dockerfile the build fails. when I log into that container and do the build by foot I can not reproduce the failing test. Hmm ... how can I collect the test results on a partially failed docker image? Well for me it is not so important (while still interesting). If you like you can try to reproduce with this Dockerfile:

```
FROM ubuntu:trusty
MAINTAINER KIC

ENV HOME /root
ENV DEBIAN_FRONTEND noninteractive

RUN apt-get update && apt-get install -y software-properties-common
RUN apt-add-repository ppa:webupd8team/java
RUN apt-get update
RUN echo oracle-java8-installer shared/accepted-oracle-license-v1-1 select true | sudo /usr/bin/debconf-set-selections
RUN apt-get install -y oracle-java8-installer
RUN apt-get install -y git maven gcc-4.6 gcc-4.6-plugin-dev gfortran-4.6 gcc-4.6.multilib g++-4.6 make vim

WORKDIR /root/
RUN git clone https://github.com/bedatadriven/renjin.git
WORKDIR renjin
RUN mvn clean install -DskipTests -Dmaven.test.skip=true
RUN mvn clean install #fails
```

when you fail, then log into the latest commit id (which should be after `RUN mvn clean install -DskipTests -Dmaven.test.skip=true` and execute a new clean install the build and tests are running just fine (at least for me)

**Comment by nuest** [comment]
I don't want to hijack this thread, but do you have published the Dockerfile somewhere in a repo, or an image on Docker Hub? I wanted to play around with renjin without installing, so I'd happily use an existing Docker image for that.

**Comment by akbertram** [comment]
The Renjin repo includes a [Vagrantfile](https://github.com/bedatadriven/renjin/blob/master/Vagrantfile) that you might find useful.

**Comment by KIC** [comment]
I had once my own fork of renjin with the dockerfile, but that does not exist anymore. never the less here is the file I have used.


```
FROM ubuntu:trusty
MAINTAINER KIC

ENV HOME /root
ENV DEBIAN_FRONTEND noninteractive

RUN apt-get update && apt-get install -y software-properties-common
RUN apt-add-repository ppa:webupd8team/java
RUN apt-get update
RUN echo oracle-java8-installer shared/accepted-oracle-license-v1-1 select true | sudo /usr/bin/debconf-set-selections
RUN apt-get install -y oracle-java8-installer 
RUN apt-get install -y git maven gcc-4.6 gcc-4.6-plugin-dev gfortran-4.6 gcc-4.6.multilib g++-4.6 make vim
RUN git config --global user.email "you@example.com"

WORKDIR /root/
RUN git clone https://github.com/bedatadriven/renjin.git
#RUN git clone https://github.com/KIC/renjin.git
WORKDIR /root/renjin
RUN mvn clean install -DskipTests -Dmaven.test.skip=true
# RUN mvn clean install -Ptools
# RUN mvn clean install 

WORKDIR /root/
```

**Comment by nuest** [comment]
Justt want to briefly follow up here, that I got Dockerfiles working a while back, see https://hub.docker.com/repository/docker/nuest/renjin/
