### ISSUE TITLE
QuitException in REPL (version 0.8.2135)

### ISSUE THREAD

**Issue by mjkallen** [bedatadriven/renjin#206]
A regression in the REPL:

```
kallen@kallen-ThinkPad-X230:~$ renjin
Using local repository: /home/kallen/.m2/repository
Renjin 0.8.2135
Copyright (C) 2015 The R Foundation for Statistical Computing
Copyright (C) 2015 BeDataDriven
> q()
ERROR: org.renjin.repl.QuitException
org.renjin.repl.QuitException
	at org.renjin.repl.JlineSessionController.quit(JlineSessionController.java:21)
	at org.renjin.primitives.Sessions.quit(Sessions.java:21)
	at org.renjin.primitives.R$primitive$quit.doApply(R$primitive$quit.java:76)
	at org.renjin.primitives.R$primitive$quit.apply(R$primitive$quit.java:37)
	at org.renjin.primitives.special.InternalFunction.apply(InternalFunction.java:55)
	at org.renjin.eval.Context.evaluateCall(Context.java:283)
	at org.renjin.eval.Context.evaluate(Context.java:207)
	at org.renjin.eval.Context.evaluate(Context.java:163)
	at org.renjin.sexp.Closure.doApply(Closure.java:107)
	at org.renjin.eval.ClosureDispatcher.apply(ClosureDispatcher.java:76)
	at org.renjin.eval.ClosureDispatcher.applyClosure(ClosureDispatcher.java:61)
	at org.renjin.sexp.Closure.apply(Closure.java:81)
	at org.renjin.eval.Context.evaluateCall(Context.java:283)
	at org.renjin.eval.Context.evaluate(Context.java:207)
	at org.renjin.eval.Context.evaluateExpressionVector(Context.java:266)
	at org.renjin.eval.Context.evaluate(Context.java:205)
	at org.renjin.repl.JlineRepl.readExpression(JlineRepl.java:196)
	at org.renjin.repl.JlineRepl.run(JlineRepl.java:103)
	at org.renjin.cli.Main.startInteractive(Main.java:114)
	at org.renjin.cli.Main.run(Main.java:99)
	at org.renjin.cli.Main.main(Main.java:69)
  at q()
Caused by:org.renjin.repl.QuitException
...
```

**Comment by akbertram** [comment]
Fixed in 0120d687391f0fdc14263530f8da5ca049eaf9e4
