### ISSUE TITLE
Cannot use foreach library

### ISSUE THREAD

**Issue by marioguerriero** [bedatadriven/renjin#210]
Hi. I am trying to use the foreach library in a script evaluated through a ScriptEngine with the following code:
```java
ScriptEngineManager engineManager = new ScriptEngineManager();
engine = engineManager.getEngineByName("Renjin");
engine.eval("script.R")
```
The script.R file is made as follows:
```R
library(DBI)
library(RMySQL)
library(foreach)
library(doMC)
library(parallel)

# Not available value for database queries
NAV <- "#NA"

# Database connection parameters
dbuser <- "root"
dbpassword <- "mario"
dbname <- "loganalysis"
dbhost <- "localhost"
dbport <- 3306
dbconnectionurl <- paste("jdbc:mysql://",dbhost,":",dbport,"/",dbname,sep="")

# Create database connection
#con <<- dbConnect(MySQL(),dbname=dbname,username="root",password="mario")

###############################
# Merge resource table with rav
###############################
buildTables <- function(sourcedb=NULL) {
  runner <- function(x) {
    x(sourcedb)
  }

  fns <- c(buildResourcesTable, buildUsersTable, buildActionsTable)

  mclapply(fns, runner, mc.cores = detectCores())

  #resources <<- buildResourcesTable(sourcedb)
  #users <<- buildUsersTable(sourcedb)
  #actions <<- buildActionsTable(sourcedb)
}

###############################
# Merge resource table with rav
###############################
buildResourcesTable <- function(sourcedb=NULL) {
  table <- "resource"
  eav <- "rav"

  con <- dbConnect(MySQL(),dbname=dbname,username="root",password="mario")

  # Query resources
  sql <- paste("select * from",table)
  q <- dbSendQuery(con,sql)
  entity <- fetch(q,n=-1)

  # Get rav table
  sql <- paste("select * from",eav)
  q <- dbSendQuery(con,sql)
  eav <- fetch(q,n=-1)

  # add columns for attributes
  attrs <- unique(eav$attribute)
  entity[,paste(table,".",attrs,sep="")] <- NAV

  # Add resources attributes
  foreach(id = entity[,"idResource"])  %dopar% {

    # Get rav table
    sql <- paste("select * from ","rav","where entityId =",id)
    q <- dbSendQuery(con,sql)
    res <- fetch(q,n=-1)

    id <- as.numeric(id)

    foreach(a = res$attribute) %dopar% {
      entity[which(entity$idResource == id),paste(table,".",a,sep="")] <- res$value[which(res$attribute == a)]
    }
  }

  if(!is.null(sourcedb)) {
    entity <- entity[which(entity$resource.sourcedb == sourcedb),]
  }

  resources <<- entity
}

...
```
And I have the following Renjin dependencies in my pom.xml file
```XML
<dependency>
			<groupId>org.renjin</groupId>
			<artifactId>renjin-script-engine</artifactId>
			<version>RELEASE</version>
		</dependency>

		<dependency>
			<groupId>org.renjin.cran</groupId>
			<artifactId>DBI</artifactId>
			<version>1.0.49</version>
		</dependency>

		<dependency>
			<groupId>org.renjin.cran</groupId>
			<artifactId>RMySQL</artifactId>
			<version>1.0.49</version>
		</dependency>

		<dependency>
			<groupId>org.renjin.cran</groupId>
			<artifactId>foreach</artifactId>
			<version>1.4.2-b287</version>
		</dependency>

		<dependency>
			<groupId>org.renjin.cran</groupId>
			<artifactId>doMC</artifactId>
			<version>1.3.4-b12</version>
		</dependency>
```

This is the error I get:

> org.renjin.eval.EvalException: IOException while loading package org.renjin.cran:foreach: Could not load package org.renjin:compiler
	at org.renjin.primitives.packaging.NamespaceRegistry.tryLoad(NamespaceRegistry.java:205)
	at org.renjin.primitives.packaging.NamespaceRegistry.tryGetNamespace(NamespaceRegistry.java:173)
	at org.renjin.primitives.packaging.NamespaceRegistry.getNamespace(NamespaceRegistry.java:135)
	at org.renjin.primitives.packaging.NamespaceRegistry.getNamespace(NamespaceRegistry.java:97)
	at org.renjin.primitives.packaging.Packages.library(Packages.java:23)
	at org.renjin.primitives.R$primitive$library.doApply(R$primitive$library.java:73)
	at org.renjin.primitives.R$primitive$library.apply(R$primitive$library.java:34)
	at org.renjin.primitives.special.InternalFunction.apply(InternalFunction.java:55)
	at org.renjin.eval.Context.evaluateCall(Context.java:283)
	at org.renjin.eval.Context.evaluate(Context.java:207)
	at org.renjin.primitives.special.BeginFunction.apply(BeginFunction.java:46)
	at org.renjin.eval.Context.evaluateCall(Context.java:283)
	at org.renjin.eval.Context.evaluate(Context.java:207)
	at org.renjin.eval.Context.evaluate(Context.java:163)
	at org.renjin.sexp.Closure.doApply(Closure.java:107)
	at org.renjin.eval.ClosureDispatcher.apply(ClosureDispatcher.java:76)
	at org.renjin.eval.ClosureDispatcher.applyClosure(ClosureDispatcher.java:61)
	at org.renjin.sexp.Closure.apply(Closure.java:81)
	at org.renjin.eval.Context.evaluateCall(Context.java:283)
	at org.renjin.eval.Context.evaluate(Context.java:207)
	at org.renjin.eval.Context.evaluateExpressionVector(Context.java:266)
	at org.renjin.eval.Context.evaluate(Context.java:205)
	at org.renjin.script.RenjinScriptEngine.eval(RenjinScriptEngine.java:150)
	at org.renjin.script.RenjinScriptEngine.eval(RenjinScriptEngine.java:145)
	at org.renjin.script.RenjinScriptEngine.eval(RenjinScriptEngine.java:124)
	at it.unisannio.loganalysis.analysis.TableHandler.<init>(TableHandler.java:30)
	at it.unisannio.loganalysis.analysis.TableHandler.getInstance(TableHandler.java:22)
	at it.unisannio.loganalysis.presentation.MyUI.lambda$init$4a7e7d78$1(MyUI.java:51)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at com.vaadin.event.ListenerMethod.receiveEvent(ListenerMethod.java:508)
	at com.vaadin.event.EventRouter.fireEvent(EventRouter.java:198)
	at com.vaadin.event.EventRouter.fireEvent(EventRouter.java:161)
	at com.vaadin.server.AbstractClientConnector.fireEvent(AbstractClientConnector.java:1008)
	at com.vaadin.ui.AbstractField.fireValueChange(AbstractField.java:1159)
	at com.vaadin.ui.AbstractField.setValue(AbstractField.java:570)
	at com.vaadin.ui.AbstractSelect.setValue(AbstractSelect.java:732)
	at com.vaadin.ui.AbstractField.setValue(AbstractField.java:468)
	at com.vaadin.ui.ComboBox.changeVariables(ComboBox.java:730)
	at com.vaadin.server.communication.ServerRpcHandler.changeVariables(ServerRpcHandler.java:603)
	at com.vaadin.server.communication.ServerRpcHandler.handleInvocations(ServerRpcHandler.java:422)
	at com.vaadin.server.communication.ServerRpcHandler.handleRpc(ServerRpcHandler.java:273)
	at com.vaadin.server.communication.UidlRequestHandler.synchronizedHandleRequest(UidlRequestHandler.java:79)
	at com.vaadin.server.SynchronizedRequestHandler.handleRequest(SynchronizedRequestHandler.java:41)
	at com.vaadin.server.VaadinService.handleRequest(VaadinService.java:1409)
	at com.vaadin.server.VaadinServlet.service(VaadinServlet.java:364)
	at javax.servlet.http.HttpServlet.service(HttpServlet.java:790)
	at org.eclipse.jetty.servlet.ServletHolder.handle(ServletHolder.java:769)
	at org.eclipse.jetty.servlet.ServletHandler$CachedChain.doFilter(ServletHandler.java:1667)
	at org.eclipse.jetty.websocket.server.WebSocketUpgradeFilter.doFilter(WebSocketUpgradeFilter.java:172)
	at org.eclipse.jetty.servlet.ServletHandler$CachedChain.doFilter(ServletHandler.java:1650)
	at org.eclipse.jetty.servlet.ServletHandler.doHandle(ServletHandler.java:583)
	at org.eclipse.jetty.server.handler.ScopedHandler.handle(ScopedHandler.java:143)
	at org.eclipse.jetty.security.SecurityHandler.handle(SecurityHandler.java:577)
	at org.eclipse.jetty.server.session.SessionHandler.doHandle(SessionHandler.java:223)
	at org.eclipse.jetty.server.handler.ContextHandler.doHandle(ContextHandler.java:1125)
	at org.eclipse.jetty.servlet.ServletHandler.doScope(ServletHandler.java:515)
	at org.eclipse.jetty.server.session.SessionHandler.doScope(SessionHandler.java:185)
	at org.eclipse.jetty.server.handler.ContextHandler.doScope(ContextHandler.java:1059)
	at org.eclipse.jetty.server.handler.ScopedHandler.handle(ScopedHandler.java:141)
	at org.eclipse.jetty.server.handler.ContextHandlerCollection.handle(ContextHandlerCollection.java:215)
	at org.eclipse.jetty.server.handler.HandlerCollection.handle(HandlerCollection.java:110)
	at org.eclipse.jetty.server.handler.HandlerWrapper.handle(HandlerWrapper.java:97)
	at org.eclipse.jetty.server.Server.handle(Server.java:497)
	at org.eclipse.jetty.server.HttpChannel.handle(HttpChannel.java:311)
	at org.eclipse.jetty.server.HttpConnection.onFillable(HttpConnection.java:248)
	at org.eclipse.jetty.io.AbstractConnection$2.run(AbstractConnection.java:540)
	at org.eclipse.jetty.util.thread.QueuedThreadPool.runJob(QueuedThreadPool.java:610)
	at org.eclipse.jetty.util.thread.QueuedThreadPool$3.run(QueuedThreadPool.java:539)
	at java.lang.Thread.run(Thread.java:745)
Caused by: org.renjin.eval.EvalException: Could not load package org.renjin:compiler
	at org.renjin.primitives.packaging.NamespaceRegistry.getNamespace(NamespaceRegistry.java:156)
	at org.renjin.primitives.packaging.NamespaceRegistry.getNamespace(NamespaceRegistry.java:118)
	at org.renjin.primitives.io.serialization.SessionReadContext.findNamespace(SessionReadContext.java:38)
	at org.renjin.primitives.io.serialization.RDataReader.readNamespace(RDataReader.java:496)
	at org.renjin.primitives.io.serialization.RDataReader.readExp(RDataReader.java:177)
	at org.renjin.primitives.io.serialization.RDataReader.readTag(RDataReader.java:421)
	at org.renjin.primitives.io.serialization.RDataReader.readClosure(RDataReader.java:253)
	at org.renjin.primitives.io.serialization.RDataReader.readExp(RDataReader.java:185)
	at org.renjin.primitives.io.serialization.RDataReader.readFile(RDataReader.java:81)
	at org.renjin.packaging.LazyLoadFrame.load(LazyLoadFrame.java:45)
	at org.renjin.primitives.packaging.FileBasedPackage.loadSymbols(FileBasedPackage.java:31)
	at org.renjin.primitives.packaging.NamespaceRegistry.populateNamespace(NamespaceRegistry.java:221)
	at org.renjin.primitives.packaging.NamespaceRegistry.tryLoad(NamespaceRegistry.java:190)
	... 71 more

Since it works fine in standard R interpreter I am assuming this is a Renjin bug.

**Comment by akbertram** [comment]
It looks like `foreach` has an implicit dependency on the compiler package.
