### ISSUE TITLE
Implement file.rename() for R save.image() functionality

### ISSUE THREAD

**Issue by colomb001** [bedatadriven/renjin#228]
R's save.image() function appears to error out due to file.rename() not being implemented yet:
`save.image("C:/temp/work.RData")`
`Error: Sorry! file.rename not yet implemented!`

**Comment by mjkallen** [comment]
Hi @colomb001 thanks for opening this issue. Unfortunately we are currently focusing on other aspects of the interpreter so it may take a while for us to pick this up. We do welcome contributions to implement missing functions!

**Comment by colomb001** [comment]
Well, that was fast. I was going to use this as an opportunity to dip my
toes in contributing. Should one want to contribute, is there any
documentation regarding the source layout / conventions?

Thanks

**Comment by akbertram** [comment]
Sorry!!

I spent some time on bug-fixes this morning and this was low hanging fruit :-)

A good first contribution might be to implement `file.remove`. It's very similar to what I just committed above, you can use a7c3735 as a model.

As far a coding conventions go, we don't have anything formal written up, but we do enforce identing and some minor formatting conventions using checkstyle, so just run `mvn install` and it will fail if you've done anything egregious :-)

**Comment by colomb001** [comment]
Apologies ahead of time if this isn't the correct forum for this question,
but I can't seem to get any a webstart application which uses renjin to
work. I'm using the jar-with-dependencies.jar and keep getting an exception
when the class loader tries to load the JitterComputation interface. I've
exploded the jar to ensure that interface is within it. I've tried with
Java 8u60 and u101. Running the application from within our IDE using the
same jar works. https://github.com/bedatadriven/renjin/issues/3 mentions
that the studio can be launched through webstart from the renjin.org
website, but that seems gone. Any ideas? Thanks

org.renjin.eval.EvalException: Exception compiling node sum(^(-([958d],
*([958d], -8.0E-4)), 2.0))
at org.renjin.eval.Context.evaluateCall(Context.java:307)
at org.renjin.eval.Context.evaluate(Context.java:218)
at
org.renjin.primitives.special.AssignLeftFunction.assignLeft(AssignLeftFunction.java:75)
at
org.renjin.primitives.special.AssignLeftFunction.apply(AssignLeftFunction.java:44)
at org.renjin.eval.Context.evaluateCall(Context.java:298)
at org.renjin.eval.Context.evaluate(Context.java:218)
at org.renjin.primitives.special.BeginFunction.apply(BeginFunction.java:46)
at org.renjin.eval.Context.evaluateCall(Context.java:298)
at org.renjin.eval.Context.evaluate(Context.java:218)
at org.renjin.primitives.special.ForFunction.apply(ForFunction.java:91)
at org.renjin.eval.Context.evaluateCall(Context.java:298)
at org.renjin.eval.Context.evaluate(Context.java:218)
at org.renjin.primitives.special.BeginFunction.apply(BeginFunction.java:46)
at org.renjin.eval.Context.evaluateCall(Context.java:298)
at org.renjin.eval.Context.evaluate(Context.java:218)
at org.renjin.eval.Context.evaluate(Context.java:165)
at org.renjin.sexp.Closure.doApply(Closure.java:107)
at org.renjin.eval.ClosureDispatcher.apply(ClosureDispatcher.java:76)
at org.renjin.eval.ClosureDispatcher.applyClosure(ClosureDispatcher.java:61)
at org.renjin.sexp.Closure.apply(Closure.java:81)
at org.renjin.eval.Context.evaluateCall(Context.java:298)
at org.renjin.eval.Context.evaluate(Context.java:218)
at
org.renjin.primitives.special.AssignLeftFunction.assignLeft(AssignLeftFunction.java:60)
at
org.renjin.primitives.special.AssignLeftFunction.apply(AssignLeftFunction.java:44)
at org.renjin.eval.Context.evaluateCall(Context.java:298)
at org.renjin.eval.Context.evaluate(Context.java:218)
at org.renjin.eval.Context.evaluateExpressionVector(Context.java:281)
at org.renjin.eval.Context.evaluate(Context.java:216)
at org.renjin.script.RenjinScriptEngine.eval(RenjinScriptEngine.java:150)
at org.renjin.script.RenjinScriptEngine.eval(RenjinScriptEngine.java:109)
CssFactorTool.java:204)
at java.util.concurrent.Executors$RunnableAdapter.call(Unknown Source)
at java.util.concurrent.FutureTask.runAndReset(Unknown Source)
at
java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.access$301(Unknown
Source)
at
java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(Unknown
Source)
at java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
at java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
at java.lang.Thread.run(Unknown Source)
Caused by: java.lang.RuntimeException: Exception compiling node
sum(^(-([958d], *([958d], -8.0E-4)), 2.0))
at
org.renjin.compiler.pipeline.DeferredNodeComputer.run(DeferredNodeComputer.java:43)
at
org.renjin.compiler.pipeline.SimpleVectorPipeliner.forceMemoizedValues(SimpleVectorPipeliner.java:49)
at
org.renjin.compiler.pipeline.SimpleVectorPipeliner.forceMemoizedValues(SimpleVectorPipeliner.java:46)
at
org.renjin.compiler.pipeline.SimpleVectorPipeliner.forceMemoizedValues(SimpleVectorPipeliner.java:46)
at
org.renjin.compiler.pipeline.SimpleVectorPipeliner.forceMemoizedValues(SimpleVectorPipeliner.java:46)
at
org.renjin.compiler.pipeline.SimpleVectorPipeliner.forceMemoizedValues(SimpleVectorPipeliner.java:46)
at
org.renjin.compiler.pipeline.SimpleVectorPipeliner.materialize(SimpleVectorPipeliner.java:20)
at org.renjin.eval.Context.materialize(Context.java:193)
at
org.renjin.primitives.subset.MatrixSelection.replaceVectorElements(MatrixSelection.java:272)
at
org.renjin.primitives.subset.MatrixSelection.replaceAtomicVectorElements(MatrixSelection.java:263)
at
org.renjin.primitives.subset.MatrixSelection.replaceAtomicVectorElements(MatrixSelection.java:13)
at org.renjin.primitives.subset.Subsetting.setSubset(Subsetting.java:324)
at
org.renjin.primitives.R$primitive$$bracket$assign.apply(R$primitive$$bracket$assign.java:60)
at org.renjin.eval.Context.evaluateCall(Context.java:298)
... 40 more
Caused by: java.lang.NoClassDefFoundError:
org/renjin/compiler/pipeline/JittedComputation
at java.lang.ClassLoader.defineClass1(Native Method)
at java.lang.ClassLoader.defineClass(Unknown Source)
at java.lang.ClassLoader.defineClass(Unknown Source)
at
org.renjin.compiler.pipeline.DeferredJitter$MyClassLoader.defineClass(DeferredJitter.java:162)
at
org.renjin.compiler.pipeline.DeferredJitter.compile(DeferredJitter.java:71)
at
org.renjin.compiler.pipeline.DeferredJitCache.compile(DeferredJitCache.java:29)
at
org.renjin.compiler.pipeline.DeferredNodeComputer.run(DeferredNodeComputer.java:29)
... 53 more
Caused by: java.lang.ClassNotFoundException:
org.renjin.compiler.pipeline.JittedComputation
at java.lang.ClassLoader.findClass(Unknown Source)
at java.lang.ClassLoader.loadClass(Unknown Source)
at java.lang.ClassLoader.loadClass(Unknown Source)

**Comment by akbertram** [comment]
@colomb001 I've opened #235 for this issue.
