### ISSUE TITLE
lsfit() Error: not all arguments have the same length

### ISSUE THREAD

**Issue by colomb001** [bedatadriven/renjin#260]
Having some issues using lsfit with renjin 0.8.2238
Using Renjin Studio:
> b=matrix(c(2,4,3,1,5,7),nrow=3)
> d=c(7,4,2)
> lsfit(b,d)
Error: not all arguments have the same length

Using RGui 3.3.1
> b=matrix(c(2,4,3,1,5,7),nrow=3)
> d=c(7,4,2)
> lsfit(b,d)
$coefficients
Intercept        X1        X2 
    7.375     0.250    -0.875 
.
.
.

**Comment by akbertram** [comment]
@colomb001 Looks like Renjin is confused because it's looking at `length(b)` rather than `nrow(b)`. Do you know where this error originates from? `model.matrix()` ? `model.frame()`?

**Comment by colomb001** [comment]
not sure I understand the question, but digging into the lsfit R code, I see this call failing

complete.cases(x, y, wt)

when wt is NULL. if wt is not null, the method returns.

**Comment by akbertram** [comment]
So the error "not all arguments have the same length" is thrown by `complete.cases()` ?

**Comment by colomb001** [comment]
Here is the associated exception I get when just calling complete.cases through the script engine

`Failure(s) in R code: complete.cases(b, d, NULL)
org.renjin.eval.EvalException: not all arguments have the same length
	at org.renjin.stats.internals.CompleteCases.countNumCases(CompleteCases.java:83)
	at org.renjin.stats.internals.CompleteCases.completeCases(CompleteCases.java:25)
	at org.renjin.primitives.R$primitive$complete$cases.apply(R$primitive$complete$cases.java:54)
	at org.renjin.primitives.special.InternalFunction.apply(InternalFunction.java:55)
	at org.renjin.eval.Context.evaluateCall(Context.java:298)
	at org.renjin.eval.Context.evaluate(Context.java:218)
	at org.renjin.eval.Context.evaluate(Context.java:165)
	at org.renjin.sexp.Closure.doApply(Closure.java:107)
	at org.renjin.eval.ClosureDispatcher.apply(ClosureDispatcher.java:76)
	at org.renjin.eval.ClosureDispatcher.applyClosure(ClosureDispatcher.java:61)
	at org.renjin.sexp.Closure.apply(Closure.java:81)
	at org.renjin.eval.Context.evaluateCall(Context.java:298)
	at org.renjin.eval.Context.evaluate(Context.java:218)
	at org.renjin.eval.Context.evaluateExpressionVector(Context.java:281)
	at org.renjin.eval.Context.evaluate(Context.java:216)
	at org.renjin.script.RenjinScriptEngine.eval(RenjinScriptEngine.java:150)
	at org.renjin.script.RenjinScriptEngine.eval(RenjinScriptEngine.java:109)
	at com.css.jri.RenjinUtility.evalFunction(RenjinUtility.java:66)
	at com.css.jri.RenjinUtility.eval(RenjinUtility.java:54)
	at ScratchWorkbench.renjinTest(ScratchWorkbench.java:761)
	at ScratchWorkbench.main(ScratchWorkbench.java:774)`

**Comment by akbertram** [comment]
It looks like 'complete.cases' is supposed to ignore NULLs, where as Renjin treats its like a zero-length vector.

**Comment by colomb001** [comment]
I think this may be just one of the issues. I've changed the complete.cases call within lsfit() to omit the NULL wt and I now get this error:

`Error: object 'C_Cdqrls' not found`

**Comment by akbertram** [comment]
The [test case](https://github.com/bedatadriven/renjin/blob/d333ab7e6e057cfb9f63579a412b9626481bb15e/tests/src/test/R/test.lsfit.R#L24-L24) for lsfit above now runs in Renjin 0.8.2247.

Can you open a new issue with the full stack trace if you run into a new problem?

**Comment by colomb001** [comment]
Just tried it under 0.8.2247 and it works as expected. Thank you! It is possible my edit of the lsfit() function could have had some other unintended consequences. Don't see a need to open up a ticket for that.

**Comment by akbertram** [comment]
Glad to hear it!
