### ISSUE TITLE
Support Pointers to C++ Member Functions 

### ISSUE THREAD

**Issue by psolaimani** [bedatadriven/renjin#282]
`svm` function from **e1071** package which is written in C++, is not compiling. This causes failure **clinical_livercohort** benchmark.

```
[INFO] ------------------------------------------------------------------------
[INFO] BUILD FAILURE
[INFO] ------------------------------------------------------------------------
[INFO] Total time: 4.021s
[INFO] Finished at: Wed Nov 23 11:02:14 CET 2016
[INFO] Final Memory: 12M/308M
[INFO] ------------------------------------------------------------------------
[ERROR] Failed to execute goal org.renjin:renjin-maven-plugin:0.8.2288:gnur-compile (compile) on project e1071: Compilation of GNU R sources failed: Failed to compile Gimple: Exception compiling function get_Q [_ZNK5SVC_Q5get_QEii] in unit svm.gimple: Exception compiling instruction T7598 = *T7597			#1292: Exception compiling assignment to T7598 = *T7597			#1292: Unsupported cast to int32 (*functionPtr)()** [FatPtrStrategy] from struct Kernel [RecordClassTypeStrategy]: UnsupportedCastException -> [Help 1]
org.apache.maven.lifecycle.LifecycleExecutionException: Failed to execute goal org.renjin:renjin-maven-plugin:0.8.2288:gnur-compile (compile) on project e1071: Compilation of GNU R sources failed
	at org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor.java:217)
	at org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor.java:153)
	at org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor.java:145)
	at org.apache.maven.lifecycle.internal.LifecycleModuleBuilder.buildProject(LifecycleModuleBuilder.java:84)
	at org.apache.maven.lifecycle.internal.LifecycleModuleBuilder.buildProject(LifecycleModuleBuilder.java:59)
	at org.apache.maven.lifecycle.internal.LifecycleStarter.singleThreadedBuild(LifecycleStarter.java:183)
	at org.apache.maven.lifecycle.internal.LifecycleStarter.execute(LifecycleStarter.java:161)
	at org.apache.maven.DefaultMaven.doExecute(DefaultMaven.java:320)
	at org.apache.maven.DefaultMaven.execute(DefaultMaven.java:156)
	at org.apache.maven.cli.MavenCli.execute(MavenCli.java:537)
	at org.apache.maven.cli.MavenCli.doMain(MavenCli.java:196)
	at org.apache.maven.cli.MavenCli.main(MavenCli.java:141)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:57)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:606)
	at org.codehaus.plexus.classworlds.launcher.Launcher.launchEnhanced(Launcher.java:289)
	at org.codehaus.plexus.classworlds.launcher.Launcher.launch(Launcher.java:229)
	at org.codehaus.plexus.classworlds.launcher.Launcher.mainWithExitCode(Launcher.java:415)
	at org.codehaus.plexus.classworlds.launcher.Launcher.main(Launcher.java:356)
Caused by: org.apache.maven.plugin.MojoExecutionException: Compilation of GNU R sources failed
	at org.renjin.maven.GnurBuildMojo.execute(GnurBuildMojo.java:75)
	at org.apache.maven.plugin.DefaultBuildPluginManager.executeMojo(DefaultBuildPluginManager.java:101)
	at org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor.java:209)
	... 19 more
Caused by: org.renjin.packaging.BuildException: Compilation of GNU R sources failed
	at org.renjin.packaging.PackageBuilder.compileNativeSources(PackageBuilder.java:82)
	at org.renjin.packaging.PackageBuilder.build(PackageBuilder.java:50)
	at org.renjin.maven.GnurBuildMojo.execute(GnurBuildMojo.java:69)
	... 21 more
Caused by: org.renjin.packaging.BuildException: Failed to compile Gimple
	at org.renjin.packaging.NativeSourceBuilder.compileGimple(NativeSourceBuilder.java:201)
	at org.renjin.packaging.NativeSourceBuilder.build(NativeSourceBuilder.java:67)
	at org.renjin.packaging.PackageBuilder.compileNativeSources(PackageBuilder.java:76)
	... 23 more
Caused by: org.renjin.gcc.InternalCompilerException: Exception compiling function get_Q [_ZNK5SVC_Q5get_QEii] in unit svm.gimple
	at org.renjin.gcc.codegen.UnitClassGenerator.emitFunctions(UnitClassGenerator.java:233)
	at org.renjin.gcc.codegen.UnitClassGenerator.emit(UnitClassGenerator.java:159)
	at org.renjin.gcc.GimpleCompiler.compile(GimpleCompiler.java:221)
	at org.renjin.packaging.NativeSourceBuilder.compileGimple(NativeSourceBuilder.java:199)
	... 25 more
Caused by: org.renjin.gcc.InternalCompilerException: Exception compiling instruction T7598 = *T7597			#1292
	at org.renjin.gcc.codegen.FunctionGenerator.emitBasicBlock(FunctionGenerator.java:305)
	at org.renjin.gcc.codegen.FunctionGenerator.emit(FunctionGenerator.java:141)
	at org.renjin.gcc.codegen.UnitClassGenerator.emitFunctions(UnitClassGenerator.java:231)
	... 28 more
Caused by: java.lang.RuntimeException: Exception compiling assignment to T7598 = *T7597			#1292
	at org.renjin.gcc.codegen.FunctionGenerator.emitAssignment(FunctionGenerator.java:347)
	at org.renjin.gcc.codegen.FunctionGenerator.emitBasicBlock(FunctionGenerator.java:290)
	... 30 more
Caused by: org.renjin.gcc.InternalCompilerException: Unsupported cast to int32 (*functionPtr)()** [FatPtrStrategy] from struct Kernel [RecordClassTypeStrategy]
	at org.renjin.gcc.codegen.expr.ExprFactory.maybeCast(ExprFactory.java:86)
	at org.renjin.gcc.codegen.expr.ExprFactory.dereferenceThenCast(ExprFactory.java:469)
	at org.renjin.gcc.codegen.expr.ExprFactory.memRef(ExprFactory.java:433)
	at org.renjin.gcc.codegen.expr.ExprFactory.findGenerator(ExprFactory.java:332)
	at org.renjin.gcc.codegen.FunctionGenerator.emitAssignment(FunctionGenerator.java:342)
	... 31 more
Caused by: org.renjin.gcc.codegen.type.UnsupportedCastException
	at org.renjin.gcc.codegen.fatptr.FatPtrStrategy.cast(FatPtrStrategy.java:252)
	at org.renjin.gcc.codegen.fatptr.FatPtrStrategy.cast(FatPtrStrategy.java:47)
	at org.renjin.gcc.codegen.expr.ExprFactory.maybeCast(ExprFactory.java:84)
	... 35 more
```

**Comment by akbertram** [comment]
The target type is not actually `int32` but a function pointer type:
 
> `T7598 = *T7597`: Unsupported cast to `int32 (*functionPtr)()**` [FatPtrStrategy] from `struct Kernel` [RecordClassTypeStrategy]

 The relevant line of C++ is in [svm.cpp](https://github.com/cran/e1071/blob/1.6-7/src/svm.cpp#L1292)

```.c++
data[j] = (Qfloat)(y[i]*y[j]*(this->*kernel_function)(i,j));
```

The problematic part of the Gimple for this line is at basic block 7:

```.c
  struct Kernel* T7594 = &&*this@0                     
  int32 T7595 = *this@0.kernel_function.__delta                       
  unsigned int32 T7596 = T7595                 
  struct Kernel* T7597 = T7594 + T7596                 
  int32 (*functionPtr)()** T7598 = *T7597   
```
Where the following record types are defined:

```
struct Kernel[0x7f13d3da3f18] {
     0: struct QMatrix 
    32: struct anonymous_0x7f13d3dae150 kernel_function
    96: struct svm_node** x
    128: real64* x_square
    160: int32 kernel_type
    192: int32 degree
    224: real64 gamma
    288: real64 coef0
}
struct QMatrix[0x7f13d3d94d20] {
     0: int32 (*functionPtr)()** _vptr.QMatrix
}
struct anonymous[0x7f13d3dae150] {
     0: real64 (*functionPtr)(struct Kernel*, int32, int32)* __pfn
    32: int32 __delta
}
```

The C++ frontend is basically taking a shortcut here. `T7597` contains the address of the beginning
of a Kernel structure, which begins with a QMatrix structure, which begins with an array of function pointers -- the classes' virtual dispatch table (vtable). So frontend knows that the address of the Kernel struct is also the address of the vtable. 

We can implement a specific casting strategy from record to the type of the first field that should accommodate this probably pretty common C++ idiom.

**Comment by akbertram** [comment]
Seems like we're good:
http://packages.renjin.org/package/org.renjin.cran/e1071/1.6-7/build/51#test-svm-examples
