### ISSUE TITLE
Pass fat pointer as record unit pointer

### ISSUE THREAD

**Issue by akbertram** [bedatadriven/renjin#284]
This can legally occur when passing a pointer to struct A as a pointer to struct B when:
* A is NOT a unit pointer
* B is a unit pointer
* A has a field of offset 0 of type B

Currently fails with

```
Caused by: java.lang.UnsupportedOperationException: Cannot pass expression of type org.renjin.gcc.codegen.fatptr.FatPtrPair as a record unit pointer of type Ljava/lang/Object;
	at org.renjin.gcc.codegen.type.record.unit.RecordUnitPtrParam.loadParameter(RecordUnitPtrParam.java:108)
	at org.renjin.gcc.codegen.call.FunctionCallGenerator$CallExpr.load(FunctionCallGenerator.java:142)
	at org.renjin.gcc.codegen.call.FunctionCallGenerator.emitCall(FunctionCallGenerator.java:85)
	at org.renjin.gcc.codegen.FunctionGenerator.emitCall(FunctionGenerator.java:375)
	at org.renjin.gcc.codegen.FunctionGenerator.emitBasicBlock(FunctionGenerator.java:303)
	... 31 more
```

**Comment by akbertram** [comment]
Fixed by f24c153c1ed3ee7a5d58238a53a5c9e7024ccb5a
