### ISSUE TITLE
Stacktrace is printed to standard output

### ISSUE THREAD

**Issue by DaveJarvis** [bedatadriven/renjin#297]
**Replicate**
Call:

```
scriptEngine.eval( "source('pluralize.R');" );
```

Ensure that the file does not exist.

**Actual Results**
```
Exception in thread "JavaFX Application Thread" org.renjin.eval.EvalException: Could not read from "pluralize.R" because it is a not a file.
	at org.renjin.primitives.io.connections.FileConnection.doOpenForInput(FileConnection.java:90)
	at org.renjin.primitives.io.connections.FileConnection.assureOpenForInput(FileConnection.java:77)
	at org.renjin.primitives.io.connections.FileConnection.getInputStream(FileConnection.java:132)
	at org.renjin.primitives.io.connections.AbstractConnection.getReader(AbstractConnection.java:33)
	at org.renjin.primitives.io.connections.FileConnection.open(FileConnection.java:61)
	at org.renjin.primitives.io.connections.Connections.newConnection(Connections.java:335)
	at org.renjin.primitives.io.connections.Connections.file(Connections.java:138)
	at org.renjin.primitives.R$primitive$file.doApply(R$primitive$file.java:75)
	at org.renjin.primitives.R$primitive$file.apply(R$primitive$file.java:36)
	at org.renjin.primitives.special.InternalFunction.apply(InternalFunction.java:45)
	at org.renjin.eval.Context.evaluateCall(Context.java:302)
	at org.renjin.eval.Context.evaluate(Context.java:222)
	at org.renjin.eval.Context.evaluate(Context.java:163)
	at org.renjin.sexp.Closure.doApply(Closure.java:84)
	at org.renjin.eval.ClosureDispatcher.apply(ClosureDispatcher.java:73)
	at org.renjin.eval.ClosureDispatcher.applyClosure(ClosureDispatcher.java:58)
	at org.renjin.sexp.Closure.apply(Closure.java:79)
	at org.renjin.eval.Context.evaluateCall(Context.java:302)
	at org.renjin.eval.Context.evaluate(Context.java:222)
	at org.renjin.primitives.special.AssignLeftFunction.assignLeft(AssignLeftFunction.java:57)
	at org.renjin.primitives.special.AssignLeftFunction.apply(AssignLeftFunction.java:41)
	at org.renjin.eval.Context.evaluateCall(Context.java:302)
	at org.renjin.eval.Context.evaluate(Context.java:222)
	at org.renjin.primitives.special.BeginFunction.apply(BeginFunction.java:38)
	at org.renjin.eval.Context.evaluateCall(Context.java:302)
	at org.renjin.eval.Context.evaluate(Context.java:222)
	at org.renjin.primitives.special.IfFunction.apply(IfFunction.java:44)
	at org.renjin.eval.Context.evaluateCall(Context.java:302)
	at org.renjin.eval.Context.evaluate(Context.java:222)
	at org.renjin.primitives.special.BeginFunction.apply(BeginFunction.java:38)
	at org.renjin.eval.Context.evaluateCall(Context.java:302)
	at org.renjin.eval.Context.evaluate(Context.java:222)
	at org.renjin.primitives.special.IfFunction.apply(IfFunction.java:40)
	at org.renjin.eval.Context.evaluateCall(Context.java:302)
	at org.renjin.eval.Context.evaluate(Context.java:222)
	at org.renjin.primitives.special.BeginFunction.apply(BeginFunction.java:38)
	at org.renjin.eval.Context.evaluateCall(Context.java:302)
	at org.renjin.eval.Context.evaluate(Context.java:222)
	at org.renjin.eval.Context.evaluate(Context.java:163)
	at org.renjin.sexp.Closure.doApply(Closure.java:84)
	at org.renjin.eval.ClosureDispatcher.apply(ClosureDispatcher.java:73)
	at org.renjin.eval.ClosureDispatcher.applyClosure(ClosureDispatcher.java:58)
	at org.renjin.sexp.Closure.apply(Closure.java:79)
	at org.renjin.eval.Context.evaluateCall(Context.java:302)
	at org.renjin.eval.Context.evaluate(Context.java:222)
	at org.renjin.eval.Context.evaluateExpressionVector(Context.java:285)
	at org.renjin.eval.Context.evaluate(Context.java:220)
	at org.renjin.script.RenjinScriptEngine.eval(RenjinScriptEngine.java:168)
	at org.renjin.script.RenjinScriptEngine.eval(RenjinScriptEngine.java:127)
```

**Expected Results**
No stack trace printed to console.

**Comment by DaveJarvis** [comment]
Might not be a Renjin issue.
