### ISSUE TITLE
Unable to load foreign library

### ISSUE THREAD

**Issue by subrotosanyal** [bedatadriven/renjin#306]
I am trying to execute the code:
---------------------------------
import javax.script.ScriptEngine;
import javax.script.ScriptEngineManager;

import org.renjin.sexp.DoubleVector;

public class TestRenjin {
	public static void main(String[] args) throws Exception {
		ScriptEngineManager scriptEngineFactory = new ScriptEngineManager();
		ScriptEngine rEngine = scriptEngineFactory.getEngineByName("Renjin");
		DoubleVector res = (DoubleVector) rEngine.eval("a <- 5; b <- 4; a*b");
		System.out.println("Result: " + res);
		rEngine.eval("library('org.renjin.cran:foreign')");
	}
}

but it ends up with an exception:
------------------------------------

Exception in thread "main" org.renjin.eval.EvalException: IOException while loading package org.renjin.cran:foreign: object 'spss_init' not found
	at org.renjin.primitives.packaging.NamespaceRegistry.tryLoad(NamespaceRegistry.java:234)
	at org.renjin.primitives.packaging.NamespaceRegistry.tryGetNamespace(NamespaceRegistry.java:191)
	at org.renjin.primitives.packaging.NamespaceRegistry.getNamespace(NamespaceRegistry.java:153)
	at org.renjin.primitives.packaging.NamespaceRegistry.getNamespace(NamespaceRegistry.java:115)
	at org.renjin.primitives.packaging.Packages.library(Packages.java:41)
	at org.renjin.primitives.R$primitive$library.doApply(R$primitive$library.java:73)
	at org.renjin.primitives.R$primitive$library.apply(R$primitive$library.java:34)
	at org.renjin.primitives.special.InternalFunction.apply(InternalFunction.java:45)
	at org.renjin.eval.Context.evaluateCall(Context.java:368)
	at org.renjin.eval.Context.evaluate(Context.java:256)
	at org.renjin.primitives.special.BeginFunction.apply(BeginFunction.java:38)
	at org.renjin.eval.Context.evaluateCall(Context.java:368)
	at org.renjin.eval.Context.evaluate(Context.java:256)
	at org.renjin.eval.Context.evaluate(Context.java:197)
	at org.renjin.sexp.Closure.doApply(Closure.java:84)
	at org.renjin.eval.ClosureDispatcher.apply(ClosureDispatcher.java:73)
	at org.renjin.eval.ClosureDispatcher.applyClosure(ClosureDispatcher.java:58)
	at org.renjin.sexp.Closure.apply(Closure.java:79)
	at org.renjin.eval.Context.evaluateCall(Context.java:368)
	at org.renjin.eval.Context.evaluate(Context.java:256)
	at org.renjin.eval.Context.evaluateExpressionVector(Context.java:351)
	at org.renjin.eval.Context.evaluate(Context.java:254)
	at org.renjin.script.RenjinScriptEngine.eval(RenjinScriptEngine.java:168)
	at org.renjin.script.RenjinScriptEngine.eval(RenjinScriptEngine.java:127)

Same issue I have encountered while using the renjin studio
-----------------------------------------------------------

Renjin 0.8.2340
Copyright (C) 2017 The R Foundation for Statistical Computing
Copyright (C) 2017 BeDataDriven
> library('org.renjin.cran:foreign')
Error: IOException while loading package org.renjin.cran:foreign: object 'spss_init' not found

**Comment by mjkallen** [comment]
The _foreign_ package is not yet compatible with Renjin. You can see the example with `spss_init()` failing on our build system [here](http://packages.renjin.org/package/org.renjin.cran/foreign/0.8-67/build/5#test-spss). This is because our C-to-Java Bytecode compiler isn't complete yet which is a known issue. We cannot give an estimate on when this will be fixed.

**Comment by subrotosanyal** [comment]
hi @mjkallen 
Thanks for your quick response.
Is there any other library which can be loaded by Renjin and provides support for SPSS files?

**Comment by mjkallen** [comment]
At the moment, I do not think so. Here's what a search in our package repository gives: http://packages.renjin.org/packages/search?q=spss

**Comment by subrotosanyal** [comment]
Thanks @mjkallen :-)

**Comment by akbertram** [comment]
@subrotosanyal Your report prompted me to open-source a Java SPSS reader library I wrote years ago: https://github.com/bedatadriven/spss-reader

Is still probably not super useful to use directly from Renjin, although you could:

```.R
reader <- com.bedatadriven.spss.SpssDataFileReader$new("myfile.sav")
var1 <- numeric(reader$numCases)
case <- 1
while(reader$readNextCase()) {
   var1[case] <- reader$getDoubleValue(0)
}
print(var1)
```

**Comment by subrotosanyal** [comment]
thanks @akbertram 👍 
I will give it a try.
Will let you know how it goes :-)

**Comment by akbertram** [comment]
Ideally there would be a Renjin package that wraps it with the same API exposed by the foreign package, but I don't think I'll have time in the coming weeks. 

You can look at the [renjin-xml2](https://github.com/bedatadriven/renjin-xml2) packages as an example of how to set up a wrapper around a Java library if you're interested in giving it a stab!
