### ISSUE TITLE
Could not resolve native method 'PROJ4_proj_def_dat_Installed' in package 'rgdal'

### ISSUE THREAD

**Issue by manojmano** [bedatadriven/renjin#331]
```
engine.eval("library(raster)");
engine.eval("library(rgdal)");
engine.put("grcPath", "E:\\Reproject.grc");
engine.eval("GDAL.open(grcPath, read.only = TRUE, silent = FALSE)");
engine.eval("x <- raster(grcPath)");
```

I trying to load raster file using raster and rgdal library. This code is working fine in Rstudio. But I'm getting the following error in Java Code. Any help?

```
Exception in thread "main" org.renjin.eval.EvalException: IOException while loading package org.renjin.cran:rgdal: Could not resolve native method 'PROJ4_proj_def_dat_Installed' in package 'rgdal'
	at org.renjin.primitives.packaging.NamespaceRegistry.tryLoad(NamespaceRegistry.java:218)
	at org.renjin.primitives.packaging.NamespaceRegistry.tryGetNamespace(NamespaceRegistry.java:181)
	at org.renjin.primitives.packaging.NamespaceRegistry.getNamespace(NamespaceRegistry.java:143)
	at org.renjin.primitives.packaging.NamespaceRegistry.getNamespace(NamespaceRegistry.java:105)
	at org.renjin.primitives.packaging.Packages.library(Packages.java:41)
	at org.renjin.primitives.R$primitive$library.doApply(R$primitive$library.java:73)
	at org.renjin.primitives.R$primitive$library.apply(R$primitive$library.java:34)
	at org.renjin.primitives.special.InternalFunction.apply(InternalFunction.java:45)
	at org.renjin.eval.Context.evaluateCall(Context.java:361)
	at org.renjin.eval.Context.evaluate(Context.java:249)
	at org.renjin.primitives.special.BeginFunction.apply(BeginFunction.java:38)
	at org.renjin.eval.Context.evaluateCall(Context.java:361)
	at org.renjin.eval.Context.evaluate(Context.java:249)
	at org.renjin.eval.Context.evaluate(Context.java:193)
	at org.renjin.sexp.Closure.doApply(Closure.java:98)
	at org.renjin.eval.ClosureDispatcher.apply(ClosureDispatcher.java:76)
	at org.renjin.eval.ClosureDispatcher.applyClosure(ClosureDispatcher.java:58)
	at org.renjin.sexp.Closure.apply(Closure.java:83)
	at org.renjin.eval.Context.evaluateCall(Context.java:361)
	at org.renjin.eval.Context.evaluate(Context.java:249)
	at org.renjin.eval.Context.evaluateExpressionVector(Context.java:344)
	at org.renjin.eval.Context.evaluate(Context.java:247)
	at org.renjin.script.RenjinScriptEngine.eval(RenjinScriptEngine.java:168)
	at org.renjin.script.RenjinScriptEngine.eval(RenjinScriptEngine.java:127)
```

**Comment by mjkallen** [comment]
Packages which interface to complex C libraries such as `gdal` are generally not supported by Renjin. See also the information from our build system: http://packages.renjin.org/package/org.renjin.cran/rgdal. 

This is not so much an issue with Renjin, but rather with our build system to be able to handle exotic gcc compiler configurations in R packages and our [gcc-bridge](http://www.renjin.org/blog/2016-01-31-introducing-gcc-bridge.html) module to transpile any C code to pure Java bytecode.
