### ISSUE TITLE
stats::HoltWinter not implemented

### ISSUE THREAD

**Issue by jbrownuf07** [bedatadriven/renjin#334]
Hey, just wanted to say great job on Renjin. It's really easy to get up and running with this library and I am impressed with the number of R packages that it currently supports. 

I ran into an issue with the forecast package and noticed that several tests in the package weren't passing in http://packages.renjin.org/package/org.renjin.cran/forecast

```
engine.eval("library(forecast)");
engine.eval("data(co2)");
engine.eval("coHW <- HoltWinters(co2)");
```

I run into the following exception:
```
org.renjin.eval.EvalException: Exception calling list(name = optim, address = org.renjin.sexp.ExternalPtr@ccd341d, numParameters = c(4L)) : object 'C_HoltWinters' not found
	at org.renjin.primitives.Native.external2(Native.java:469)
	at org.renjin.primitives.R$primitive$$External2.apply(R$primitive$$External2.java:63)
	at org.renjin.eval.Context.evaluateCall(Context.java:365)
	at org.renjin.eval.Context.evaluate(Context.java:249)
	at org.renjin.primitives.special.IfFunction.apply(IfFunction.java:44)
	at org.renjin.eval.Context.evaluateCall(Context.java:365)
	at org.renjin.eval.Context.evaluate(Context.java:249)
	at org.renjin.primitives.special.AssignLeftFunction.assignLeft(AssignLeftFunction.java:57)
	at org.renjin.primitives.special.AssignLeftFunction.apply(AssignLeftFunction.java:41)
	at org.renjin.eval.Context.evaluateCall(Context.java:365)
	at org.renjin.eval.Context.evaluate(Context.java:249)
	at org.renjin.primitives.special.BeginFunction.apply(BeginFunction.java:38)
	at org.renjin.eval.Context.evaluateCall(Context.java:365)
	at org.renjin.eval.Context.evaluate(Context.java:249)
	at org.renjin.eval.Context.evaluate(Context.java:193)
	at org.renjin.sexp.Closure.doApply(Closure.java:97)
	at org.renjin.eval.ClosureDispatcher.apply(ClosureDispatcher.java:78)
	at org.renjin.eval.ClosureDispatcher.applyClosure(ClosureDispatcher.java:49)
	at org.renjin.sexp.Closure.apply(Closure.java:82)
	at org.renjin.eval.Context.evaluateCall(Context.java:365)
	at org.renjin.eval.Context.evaluate(Context.java:249)
	at org.renjin.primitives.special.AssignLeftFunction.assignLeft(AssignLeftFunction.java:57)
	at org.renjin.primitives.special.AssignLeftFunction.apply(AssignLeftFunction.java:41)
	at org.renjin.eval.Context.evaluateCall(Context.java:365)
	at org.renjin.eval.Context.evaluate(Context.java:249)
	at org.renjin.primitives.special.BeginFunction.apply(BeginFunction.java:38)
	at org.renjin.eval.Context.evaluateCall(Context.java:365)
	at org.renjin.eval.Context.evaluate(Context.java:249)
	at org.renjin.primitives.special.IfFunction.apply(IfFunction.java:40)
	at org.renjin.eval.Context.evaluateCall(Context.java:365)
	at org.renjin.eval.Context.evaluate(Context.java:249)
	at org.renjin.primitives.special.BeginFunction.apply(BeginFunction.java:38)
	at org.renjin.eval.Context.evaluateCall(Context.java:365)
	at org.renjin.eval.Context.evaluate(Context.java:249)
	at org.renjin.primitives.special.IfFunction.apply(IfFunction.java:40)
	at org.renjin.eval.Context.evaluateCall(Context.java:365)
	at org.renjin.eval.Context.evaluate(Context.java:249)
	at org.renjin.primitives.special.BeginFunction.apply(BeginFunction.java:38)
	at org.renjin.eval.Context.evaluateCall(Context.java:365)
	at org.renjin.eval.Context.evaluate(Context.java:249)
	at org.renjin.primitives.special.IfFunction.apply(IfFunction.java:40)
	at org.renjin.eval.Context.evaluateCall(Context.java:365)
	at org.renjin.eval.Context.evaluate(Context.java:249)
	at org.renjin.primitives.special.BeginFunction.apply(BeginFunction.java:38)
	at org.renjin.eval.Context.evaluateCall(Context.java:365)
	at org.renjin.eval.Context.evaluate(Context.java:249)
	at org.renjin.eval.Context.evaluate(Context.java:193)
	at org.renjin.sexp.Closure.doApply(Closure.java:97)
	at org.renjin.eval.ClosureDispatcher.apply(ClosureDispatcher.java:78)
	at org.renjin.eval.ClosureDispatcher.applyClosure(ClosureDispatcher.java:49)
	at org.renjin.sexp.Closure.apply(Closure.java:82)
	at org.renjin.eval.Context.evaluateCall(Context.java:365)
	at org.renjin.eval.Context.evaluate(Context.java:249)
	at org.renjin.primitives.special.AssignLeftFunction.assignLeft(AssignLeftFunction.java:57)
	at org.renjin.primitives.special.AssignLeftFunction.apply(AssignLeftFunction.java:41)
	at org.renjin.eval.Context.evaluateCall(Context.java:365)
	at org.renjin.eval.Context.evaluate(Context.java:249)
	at org.renjin.eval.Context.evaluateExpressionVector(Context.java:348)
	at org.renjin.eval.Context.evaluate(Context.java:247)
	at org.renjin.script.RenjinScriptEngine.eval(RenjinScriptEngine.java:168)
	at org.renjin.script.RenjinScriptEngine.eval(RenjinScriptEngine.java:127)
	at FirstRenjinApp.forecast_example(FirstRenjinApp.java:343)
	at FirstRenjinApp.main(FirstRenjinApp.java:69)
Caused by: org.renjin.eval.EvalException: object 'C_HoltWinters' not found
	at org.renjin.eval.Context.evaluateSymbol(Context.java:295)
	at org.renjin.eval.Context.evaluate(Context.java:245)
	at org.renjin.invoke.codegen.ArgumentIterator.evalNext(ArgumentIterator.java:77)
	at org.renjin.primitives.R$primitive$$C.apply(R$primitive$$C.java:38)
	at org.renjin.eval.Context.evaluateCall(Context.java:365)
	at org.renjin.eval.Context.evaluate(Context.java:249)
	at org.renjin.eval.Context.evaluate(Context.java:193)
	at org.renjin.sexp.Closure.doApply(Closure.java:97)
	at org.renjin.eval.ClosureDispatcher.apply(ClosureDispatcher.java:78)
	at org.renjin.eval.ClosureDispatcher.applyClosure(ClosureDispatcher.java:49)
	at org.renjin.sexp.Closure.apply(Closure.java:82)
	at org.renjin.eval.Context.evaluateCall(Context.java:365)
	at org.renjin.eval.Context.evaluate(Context.java:249)
	at org.renjin.primitives.special.DollarFunction.apply(DollarFunction.java:48)
	at org.renjin.eval.Context.evaluateCall(Context.java:365)
	at org.renjin.eval.Context.evaluate(Context.java:249)
	at org.renjin.eval.Context.evaluate(Context.java:193)
	at org.renjin.sexp.Closure.doApply(Closure.java:97)
	at org.renjin.eval.ClosureDispatcher.apply(ClosureDispatcher.java:78)
	at org.renjin.eval.ClosureDispatcher.applyClosure(ClosureDispatcher.java:49)
	at org.renjin.sexp.Closure.apply(Closure.java:82)
	at org.renjin.eval.Context.evaluateCall(Context.java:365)
	at org.renjin.eval.Context.evaluate(Context.java:249)
	at org.renjin.eval.Context.evaluate(Context.java:193)
	at org.renjin.sexp.Closure.doApply(Closure.java:97)
	at org.renjin.eval.ClosureDispatcher.apply(ClosureDispatcher.java:78)
	at org.renjin.eval.ClosureDispatcher.applyClosure(ClosureDispatcher.java:49)
	at org.renjin.sexp.Closure.apply(Closure.java:82)
	at org.renjin.eval.Context.evaluateCall(Context.java:365)
	at org.renjin.eval.Context.evaluate(Context.java:249)
	at org.renjin.gnur.api.Rinternals.Rf_eval(Rinternals.java:1501)
	at org.renjin.stats.optim__.fminfn(optim.c:84)
	at org.renjin.stats.apply_optim__.lbfgsb(apply_optim.c:687)
	at org.renjin.stats.optim__.optim(optim.c:360)
	at org.renjin.stats.stats.optim(Unknown Source)
	at org.renjin.primitives.Native.external2(Native.java:464)
```

**Comment by jbrownuf07** [comment]
Hey, thanks for the prompt action. I tried the latest release (8.1-b10), but it's still not working.

**Comment by akbertram** [comment]
Can you make sure you try this on the latest release of Renjin (0.8.2422) ?
The HoltWinters() function is in the R stats package, not the forecast package. 

When I try your code above I get the following:
```
Renjin 0.8.2422
Copyright (C) 2017 The R Foundation for Statistical Computing
Copyright (C) 2017 BeDataDriven
Using system BLAS libraries.
> data(co2)
> coHW <- HoltWinters(co2)
> coHW
Holt-Winters exponential smoothing with trend and additive seasonal component.

Call:
 HoltWinters(x = co2) 

Smoothing parameters:
 alpha:  0.51264844356418 
 beta :  0.00949766904603 
 gamma:  0.47288678799482 

Coefficients:
                  [,1]
  a 364.76162366898694
  b   0.12474380425042
 s1   0.22152745995516
 s2   0.95528006045129
 s3   1.59847439486225
 s4   2.87580291519829
 s5   3.28200883534773
 s6   2.44069898939628
 s7   0.89694326358494
 s8  -1.37964276138164
 s9  -3.41123761724334
s10  -3.25701626483366
s11  -1.91348502861714
s12  -0.58442498557985
> 
```

which matches the output from GNU R.

**Comment by jbrownuf07** [comment]
Yeah, it's working now!
I noticed that it throws an exception when I try to load the forecast library: `library(forecast)`. I assume that's because not all the functionality in the forecast package is implemented. For instance, the `ets` function does not work. 

Great job and thank you!

**Comment by akbertram** [comment]
The Renjin project doesn't "implement" any third-party packages like forecast -- the goal is to load all these packages as-is. But unfortunately as you can see our C-to-JVM compiler is not yet complete and will fail on some C and C++ package source code, so indeed not all of the forecast package will run on Renjin today.

You can get an overview of what is available from the package by browsing the test results:
http://packages.renjin.org/package/org.renjin.cran/forecast/8.1/build/10
