### ISSUE TITLE
org.renjin.eval.EvalException: replacement has zero length

### ISSUE THREAD

**Issue by DaveJarvis** [bedatadriven/renjin#338]
Format numbers with commas.

**Replicate in R**
``` .R
> format( 1000, big.mark=',' )
[1] "1,000"
```

**Replicate in Renjin**
``` .java
getScriptEngine().eval( "format( 1000, big.mark=',' )" )
```

**Expected Results**
"1,000"

**Actual Results**
```
Exception occurred in target VM: replacement has zero length 
org.renjin.eval.EvalException: replacement has zero length
	at org.renjin.primitives.subset.VectorIndexSelection.buildReplacement(VectorIndexSelection.java:241)
	at org.renjin.primitives.subset.VectorIndexSelection.replaceAtomicVectorElements(VectorIndexSelection.java:206)
	at org.renjin.primitives.subset.VectorIndexSelection.replaceAtomicVectorElements(VectorIndexSelection.java:31)
	at org.renjin.primitives.subset.Subsetting.setSubset(Subsetting.java:336)
	at org.renjin.primitives.R$primitive$$bracket$assign.apply(R$primitive$$bracket$assign.java:48)
	at org.renjin.eval.Context.evaluateCall(Context.java:407)
	at org.renjin.eval.Context.evaluate(Context.java:282)
	at org.renjin.eval.Context.evaluate(Context.java:264)
	at org.renjin.primitives.special.AssignLeftFunction.assignLeft(AssignLeftFunction.java:72)
	at org.renjin.primitives.special.AssignLeftFunction.apply(AssignLeftFunction.java:41)
	at org.renjin.eval.Context.evaluateCall(Context.java:407)
	at org.renjin.eval.Context.evaluate(Context.java:282)
	at org.renjin.eval.Context.evaluate(Context.java:264)
	at org.renjin.primitives.special.BeginFunction.apply(BeginFunction.java:38)
	at org.renjin.eval.Context.evaluateCall(Context.java:407)
	at org.renjin.eval.Context.evaluate(Context.java:282)
	at org.renjin.eval.Context.evaluate(Context.java:264)
	at org.renjin.primitives.special.IfFunction.apply(IfFunction.java:40)
	at org.renjin.eval.Context.evaluateCall(Context.java:407)
	at org.renjin.eval.Context.evaluate(Context.java:282)
	at org.renjin.eval.Context.evaluate(Context.java:264)
	at org.renjin.primitives.special.BeginFunction.apply(BeginFunction.java:38)
	at org.renjin.eval.Context.evaluateCall(Context.java:407)
	at org.renjin.eval.Context.evaluate(Context.java:282)
	at org.renjin.eval.Context.evaluate(Context.java:264)
	at org.renjin.eval.Context.evaluate(Context.java:198)
	at org.renjin.sexp.Closure.doApply(Closure.java:97)
	at org.renjin.eval.ClosureDispatcher.apply(ClosureDispatcher.java:80)
	at org.renjin.eval.ClosureDispatcher.applyClosure(ClosureDispatcher.java:51)
	at org.renjin.sexp.Closure.apply(Closure.java:82)
	at org.renjin.eval.Context.evaluateCall(Context.java:407)
	at org.renjin.eval.Context.evaluate(Context.java:282)
	at org.renjin.eval.Context.evaluate(Context.java:264)
	at org.renjin.primitives.special.BeginFunction.apply(BeginFunction.java:38)
	at org.renjin.eval.Context.evaluateCall(Context.java:407)
	at org.renjin.eval.Context.evaluate(Context.java:282)
	at org.renjin.eval.Context.evaluate(Context.java:264)
	at org.renjin.primitives.special.SwitchFunction.doApply(SwitchFunction.java:69)
	at org.renjin.primitives.special.SwitchFunction.apply(SwitchFunction.java:34)
	at org.renjin.eval.Context.evaluateCall(Context.java:407)
	at org.renjin.eval.Context.evaluate(Context.java:282)
	at org.renjin.eval.Context.evaluate(Context.java:264)
	at org.renjin.primitives.special.BeginFunction.apply(BeginFunction.java:38)
	at org.renjin.eval.Context.evaluateCall(Context.java:407)
	at org.renjin.eval.Context.evaluate(Context.java:282)
	at org.renjin.eval.Context.evaluate(Context.java:264)
	at org.renjin.primitives.special.IfFunction.apply(IfFunction.java:44)
	at org.renjin.eval.Context.evaluateCall(Context.java:407)
	at org.renjin.eval.Context.evaluate(Context.java:282)
	at org.renjin.eval.Context.evaluate(Context.java:264)
	at org.renjin.primitives.special.BeginFunction.apply(BeginFunction.java:38)
	at org.renjin.eval.Context.evaluateCall(Context.java:407)
	at org.renjin.eval.Context.evaluate(Context.java:282)
	at org.renjin.eval.Context.evaluate(Context.java:264)
	at org.renjin.eval.Calls.applyClosure(Calls.java:47)
	at org.renjin.primitives.S3$GenericMethod.doApply(S3.java:1451)
	at org.renjin.primitives.S3$GenericMethod.apply(S3.java:1400)
	at org.renjin.primitives.S3.UseMethod(S3.java:80)
	at org.renjin.primitives.S3.UseMethod(S3.java:72)
	at org.renjin.primitives.R$primitive$UseMethod.doApply(R$primitive$UseMethod.java:77)
	at org.renjin.primitives.R$primitive$UseMethod.apply(R$primitive$UseMethod.java:31)
	at org.renjin.eval.Context.evaluateCall(Context.java:407)
	at org.renjin.eval.Context.evaluate(Context.java:282)
	at org.renjin.eval.Context.evaluate(Context.java:264)
	at org.renjin.eval.Context.evaluate(Context.java:198)
	at org.renjin.sexp.Closure.doApply(Closure.java:97)
	at org.renjin.eval.ClosureDispatcher.apply(ClosureDispatcher.java:80)
	at org.renjin.eval.ClosureDispatcher.applyClosure(ClosureDispatcher.java:51)
	at org.renjin.sexp.Closure.apply(Closure.java:82)
	at org.renjin.eval.Context.evaluateCall(Context.java:407)
	at org.renjin.eval.Context.evaluate(Context.java:282)
	at org.renjin.eval.Context.evaluate(Context.java:264)
	at org.renjin.eval.Context.evaluateExpressionVector(Context.java:390)
	at org.renjin.eval.Context.evaluate(Context.java:280)
	at org.renjin.eval.Context.evaluate(Context.java:264)
	at org.renjin.script.RenjinScriptEngine.eval(RenjinScriptEngine.java:168)
	at org.renjin.script.RenjinScriptEngine.eval(RenjinScriptEngine.java:127)
	at com.scrivenvar.processors.InlineRProcessor.eval(InlineRProcessor.java:174)
	at com.scrivenvar.processors.InlineRProcessor.processLink(InlineRProcessor.java:133)
	at com.scrivenvar.processors.InlineRProcessor.processLink(InlineRProcessor.java:53)
	at com.scrivenvar.processors.AbstractProcessor.processChain(AbstractProcessor.java:81)
	at com.scrivenvar.MainWindow.refreshSelectedTab(MainWindow.java:322)
	at com.scrivenvar.MainWindow.lambda$initTextChangeListener$5(MainWindow.java:274)
	at org.reactfx.value.ChangeListenerWrapper.accept(Val.java:786)
	at org.reactfx.util.AbstractReducingStreamNotifications.lambda$head$0(NotificationAccumulator.java:248)
	at org.reactfx.ObservableBase.notifyObservers(ObservableBase.java:68)
	at org.reactfx.SuspendableBase.resume(SuspendableBase.java:64)
	at org.reactfx.CloseableOnceGuard.close(Guard.java:49)
	at org.reactfx.MultiGuard.close(Guard.java:83)
	at org.reactfx.Suspendable$1.resumeSource(Suspendable.java:118)
	at org.reactfx.Suspendable$1.suspendSource(Suspendable.java:104)
	at org.reactfx.util.NonAccumulativeStreamNotifications.lambda$head$0(NotificationAccumulator.java:134)
	at org.reactfx.ObservableBase.notifyObservers(ObservableBase.java:68)
	at org.reactfx.ObservableBase.notifyObservers(ObservableBase.java:57)
	at org.reactfx.ProperEventStream.emit(ProperEventStream.java:18)
	at org.reactfx.EventStreams$3.lambda$observeInputs$0(EventStreams.java:105)
	at org.reactfx.value.ChangeListenerWrapper.accept(Val.java:786)
	at org.reactfx.util.AbstractReducingStreamNotifications.lambda$head$0(NotificationAccumulator.java:248)
	at org.reactfx.ObservableBase.notifyObservers(ObservableBase.java:68)
	at org.reactfx.ObservableBase.notifyObservers(ObservableBase.java:57)
	at org.reactfx.value.ValBase.invalidate(ValBase.java:32)
	at org.reactfx.SuspendableBoolean.release(SuspendableBoolean.java:24)
	at org.reactfx.CloseableOnceGuard.close(Guard.java:49)
	at org.reactfx.Suspendable.suspendWhile(Suspendable.java:49)
	at org.fxmisc.richtext.model.GenericEditableStyledDocumentBase.update(GenericEditableStyledDocumentBase.java:218)
	at org.reactfx.util.Tuple3.exec(Tuple3.java:43)
	at org.fxmisc.richtext.model.GenericEditableStyledDocumentBase.replace(GenericEditableStyledDocumentBase.java:125)
	at org.fxmisc.richtext.model.SimpleEditableStyledDocument.replace(SimpleEditableStyledDocument.java:10)
	at org.fxmisc.richtext.GenericStyledArea.replace(GenericStyledArea.java:1200)
	at org.fxmisc.richtext.GenericStyledArea.replaceText(GenericStyledArea.java:1187)
	at org.fxmisc.richtext.model.EditActions.replaceText(EditActions.java:147)
	at com.scrivenvar.editors.EditorPane.setText(EditorPane.java:99)
	at com.scrivenvar.FileEditorTab.load(FileEditorTab.java:268)
	at com.scrivenvar.FileEditorTab.activated(FileEditorTab.java:149)
	at com.scrivenvar.FileEditorTab.lambda$null$1(FileEditorTab.java:90)
	at com.sun.javafx.application.PlatformImpl.lambda$null$173(PlatformImpl.java:295)
	at java.security.AccessController.doPrivileged(Native Method)
	at com.sun.javafx.application.PlatformImpl.lambda$runLater$174(PlatformImpl.java:294)
	at com.sun.glass.ui.InvokeLaterDispatcher$Future.run(InvokeLaterDispatcher.java:95)
	at com.sun.glass.ui.gtk.GtkApplication._runLoop(Native Method)
	at com.sun.glass.ui.gtk.GtkApplication.lambda$null$49(GtkApplication.java:139)
	at java.lang.Thread.run(Thread.java:745)
```

**Additional Failing Test Cases**
``` .R
> formatC( 1000, big.mark=',' )
[1] "1,000"
> prettyNum( 1000, big.mark=',' )
[1] "1,000"
```

**Additional Details**
```
renjin-script-engine-0.8.2470-jar-with-dependencies.jar
```

**Comment by mjkallen** [comment]
There are additional issues with formatting character strings:

**GNU R 3.5.3:**
```
> format("foobar", width = 8, justify = "right")
[1] "  foobar"
> format("foobar", width = 8, justify = "centre")
[1] " foobar "
> format("foobar", width = 8, justify = "none")
[1] "foobar"
```

**Renjin**
```
> format("foobar", width = 8, justify = "right")
[1] "foobar  "
> format("foobar", width = 8, justify = "centre")
[1] "foobar  "
> format("foobar", width = 8, justify = "none")
[1] "foobar  "
```
