### ISSUE TITLE
version 0.8.2476  seems broken

### ISSUE THREAD

**Issue by kusamau** [bedatadriven/renjin#339]
I created a simple Maven project executing the simple example in [Evaluating R Language Code
](http://docs.renjin.org/en/latest/library/evaluating.html) the result is 

```
Exception in thread "main" java.lang.RuntimeException: org.renjin.eval.EvalException: Could not load package org.renjin:methods
	at org.renjin.eval.SessionBuilder.build(SessionBuilder.java:191)
	at org.renjin.script.RenjinScriptEngineFactory.getScriptEngine(RenjinScriptEngineFactory.java:110)
	at com.rezatec.rengine.REngine.main(REngine.java:12)
Caused by: org.renjin.eval.EvalException: Could not load package org.renjin:methods
	at org.renjin.primitives.packaging.NamespaceRegistry.getNamespace(NamespaceRegistry.java:164)
.....
```

Downgrading to **0.8.2474** all works as expected.

**Comment by akbertram** [comment]
I think it might be :-)
Actually I thought 0.8.2474 was seriously broken, but I'm working on an update now.

Can you share the rest of the stack trace? I'm not sure why the methods package won't load.

**Comment by kusamau** [comment]
This is all I have. Thanks!


```
Exception in thread "main" java.lang.RuntimeException: org.renjin.eval.EvalException: Could not load package org.renjin:methods
	at org.renjin.eval.SessionBuilder.build(SessionBuilder.java:191)
	at org.renjin.script.RenjinScriptEngineFactory.getScriptEngine(RenjinScriptEngineFactory.java:110)
	at com.rezatec.rengine.REngine.main(REngine.java:12)
Caused by: org.renjin.eval.EvalException: Could not load package org.renjin:methods
	at org.renjin.primitives.packaging.NamespaceRegistry.getNamespace(NamespaceRegistry.java:164)
	at org.renjin.primitives.packaging.NamespaceRegistry.getNamespace(NamespaceRegistry.java:126)
	at org.renjin.primitives.packaging.NamespaceRegistry.getNamespace(NamespaceRegistry.java:105)
	at org.renjin.primitives.packaging.Packages.library(Packages.java:41)
	at org.renjin.primitives.R$primitive$library.doApply(R$primitive$library.java:73)
	at org.renjin.primitives.R$primitive$library.apply(R$primitive$library.java:34)
	at org.renjin.primitives.special.InternalFunction.apply(InternalFunction.java:45)
	at org.renjin.eval.Context.evaluateCall(Context.java:407)
	at org.renjin.eval.Context.evaluate(Context.java:282)
	at org.renjin.eval.Context.evaluate(Context.java:264)
	at org.renjin.primitives.special.BeginFunction.apply(BeginFunction.java:38)
	at org.renjin.eval.Context.evaluateCall(Context.java:407)
	at org.renjin.eval.Context.evaluate(Context.java:282)
	at org.renjin.eval.Context.evaluate(Context.java:264)
	at org.renjin.eval.Context.evaluate(Context.java:198)
	at org.renjin.sexp.Closure.doApply(Closure.java:97)
	at org.renjin.eval.ClosureDispatcher.apply(ClosureDispatcher.java:80)
	at org.renjin.eval.ClosureDispatcher.applyClosure(ClosureDispatcher.java:51)
	at org.renjin.sexp.Closure.apply(Closure.java:82)
	at org.renjin.eval.Context.evaluateCall(Context.java:407)
	at org.renjin.eval.Context.evaluate(Context.java:282)
	at org.renjin.eval.Context.evaluate(Context.java:264)
	at org.renjin.eval.Context.evaluate(Context.java:198)
	at org.renjin.eval.SessionBuilder.build(SessionBuilder.java:186)
	... 2 more

```

**Comment by psolaimani** [comment]
Hi @kusamau,

I tried to mimic your issue with Renjin versions 0.8.2474, 0.8.2476, and 0.8.2478 but was not successful. 

Could you please share the output of your maven dependencies list next time this issue happens? 
(`mvn dependency:resolve && mvn -o dependency:list`)

**Comment by kusamau** [comment]
sure, this is an extract from my POM

`	<packaging>war</packaging>

	<repositories>
		<repository>
			<id>bedatadriven</id>
			<name>bedatadriven public repo</name>
			<url>https://nexus.bedatadriven.com/content/groups/public/</url>
		</repository>
	</repositories>

	<parent>
		<groupId>org.springframework.boot</groupId>
		<artifactId>spring-boot-starter-parent</artifactId>
		<version>1.5.7.RELEASE</version>
	</parent>

	<build>
		<plugins>
			<plugin>
				<artifactId>maven-compiler-plugin</artifactId>
				<version>3.7.0</version>
				<configuration>
					<source>1.8</source>
					<target>1.8</target>
				</configuration>
			</plugin>

			<plugin>
				<artifactId>maven-war-plugin</artifactId>
				<configuration>
					<failOnMissingWebXml>false</failOnMissingWebXml>
				</configuration>
			</plugin>
		</plugins>
	</build>
	<dependencies>
	
		<dependency>
			<groupId>org.renjin</groupId>
			<artifactId>renjin-script-engine</artifactId>
			<version>0.8.2478</version>
		</dependency>
	
	
		<dependency>
			<groupId>org.springframework.boot</groupId>
			<artifactId>spring-boot-starter-web</artifactId>
		</dependency>
		<dependency>
			<groupId>org.springframework.boot</groupId>
			<artifactId>spring-boot-starter-test</artifactId>
			<scope>test</scope>
		</dependency>
	</dependencies>`

**Comment by akbertram** [comment]
The error message seemed to indicates that the methods package (methods.jar) was not on your classpath. As long as this isn't happening with the latest version, I'll go ahead and close the issue. Please re-open if it becomes an issue again!

**Comment by kusamau** [comment]
I can confirm that it works with 0.8.2474 and 0.8.2478 but not with 0.8.2476. Consequently, having moved to 0.8.2478 I am fine. Thanks!
