### ISSUE TITLE
stem function is not working

### ISSUE THREAD

**Issue by chuanwen** [bedatadriven/renjin#349]
```
x = rnorm(1000)
stem(x)

ERROR: Class org.renjin.base.Base has no method named stemleaf
java.lang.IllegalArgumentException: Class org.renjin.base.Base has no method named stemleaf
	at org.renjin.invoke.reflection.ClassBindingImpl.getStaticMethodBinding(ClassBindingImpl.java:208)
	at org.renjin.primitives.Native.delegateToJavaMethod(Native.java:491)
	at org.renjin.primitives.Native.dotC(Native.java:132)
	at org.renjin.primitives.R$primitive$$C.apply(R$primitive$$C.java:66)
	at org.renjin.eval.Context.evaluateCall(Context.java:407)
	at org.renjin.eval.Context.evaluate(Context.java:282)
	at org.renjin.eval.Context.evaluate(Context.java:264)
	at org.renjin.primitives.special.BeginFunction.apply(BeginFunction.java:38)
	at org.renjin.eval.Context.evaluateCall(Context.java:407)
	at org.renjin.eval.Context.evaluate(Context.java:282)
	at org.renjin.eval.Context.evaluate(Context.java:264)
	at org.renjin.eval.Context.evaluate(Context.java:198)
	at org.renjin.sexp.Closure.doApply(Closure.java:97)
	at org.renjin.eval.ClosureDispatcher.apply(ClosureDispatcher.java:80)
	at org.renjin.eval.ClosureDispatcher.applyClosure(ClosureDispatcher.java:51)
	at org.renjin.sexp.Closure.apply(Closure.java:82)
	at org.renjin.eval.Context.evaluateCall(Context.java:407)
	at org.renjin.eval.Context.evaluate(Context.java:282)
	at org.renjin.eval.Context.evaluate(Context.java:264)
	at org.renjin.eval.Context.evaluateExpressionVector(Context.java:390)
	at org.renjin.eval.Context.evaluate(Context.java:280)
	at org.renjin.eval.Context.evaluate(Context.java:264)
	at org.renjin.repl.JlineRepl.readExpression(JlineRepl.java:244)
	at org.renjin.repl.JlineRepl.run(JlineRepl.java:131)
	at org.renjin.cli.Main.startInteractive(Main.java:126)
	at org.renjin.cli.Main.run(Main.java:111)
	at org.renjin.cli.Main.main(Main.java:78)
  at stem()
Caused by:java.lang.IllegalArgumentException: Class org.renjin.base.Base has no method named stemleaf
	at org.renjin.invoke.reflection.ClassBindingImpl.getStaticMethodBinding(ClassBindingImpl.java:208)
	at org.renjin.primitives.Native.delegateToJavaMethod(Native.java:491)
	at org.renjin.primitives.Native.dotC(Native.java:132)
	at org.renjin.primitives.R$primitive$$C.apply(R$primitive$$C.java:66)
	at org.renjin.eval.Context.evaluateCall(Context.java:407)
	at org.renjin.eval.Context.evaluate(Context.java:282)
	at org.renjin.eval.Context.evaluate(Context.java:264)
	at org.renjin.primitives.special.BeginFunction.apply(BeginFunction.java:38)
	at org.renjin.eval.Context.evaluateCall(Context.java:407)
	at org.renjin.eval.Context.evaluate(Context.java:282)
	at org.renjin.eval.Context.evaluate(Context.java:264)
	at org.renjin.eval.Context.evaluate(Context.java:198)
	at org.renjin.sexp.Closure.doApply(Closure.java:97)
	at org.renjin.eval.ClosureDispatcher.apply(ClosureDispatcher.java:80)
	at org.renjin.eval.ClosureDispatcher.applyClosure(ClosureDispatcher.java:51)
	at org.renjin.sexp.Closure.apply(Closure.java:82)
	at org.renjin.eval.Context.evaluateCall(Context.java:407)
	at org.renjin.eval.Context.evaluate(Context.java:282)
	at org.renjin.eval.Context.evaluate(Context.java:264)
	at org.renjin.eval.Context.evaluateExpressionVector(Context.java:390)
	at org.renjin.eval.Context.evaluate(Context.java:280)
	at org.renjin.eval.Context.evaluate(Context.java:264)
	at org.renjin.repl.JlineRepl.readExpression(JlineRepl.java:244)
	at org.renjin.repl.JlineRepl.run(JlineRepl.java:131)
	at org.renjin.cli.Main.startInteractive(Main.java:126)
	at org.renjin.cli.Main.run(Main.java:111)
	at org.renjin.cli.Main.main(Main.java:78)
```

**Comment by DaveJarvis** [comment]
Possibly related:

* https://github.com/bedatadriven/renjin/blob/daf1add59f40338a18f68f04be1c3a89ccbf417a/packages/graphics/src/main/R/stem.R - calling "stemleaf", which doesn't exist.
* https://github.com/bedatadriven/renjin/blob/daf1add59f40338a18f68f04be1c3a89ccbf417a/packages/graphics/src/main/c/stem.c#L152 - function name "StemLeaf"?
* https://github.com/bedatadriven/renjin/blob/daf1add59f40338a18f68f04be1c3a89ccbf417a/packages/graphics/src/main/c/stem.c#L53 - function name "stem_leaf"?
* http://packages.renjin.org/package/org.renjin.cran/aplpack - failing tests?

**Comment by psolaimani** [comment]
issue solved [here](https://github.com/bedatadriven/renjin/commit/2083225737040ed26e5f9f8bc2a56a8dc7cbca5f)
