### ISSUE TITLE
data.table: Unimplemented GNU R API function 'DUPLICATE_ATTRIB'

### ISSUE THREAD

**Issue by chuanwen** [bedatadriven/renjin#352]
```
library(data.table)
x = data.table(x = rnorm(1000)

ERROR: Exception calling Calloccolwrapper : Unimplemented GNU R API function 'DUPLICATE_ATTRIB'
org.renjin.gnur.api.UnimplementedGnuApiMethod: Unimplemented GNU R API function 'DUPLICATE_ATTRIB'
	at org.renjin.gnur.api.Rinternals.DUPLICATE_ATTRIB(Rinternals.java:458)
	at org.renjin.cran.data$table.assign__.shallow(assign.c:154)
	at org.renjin.cran.data$table.assign__.alloccol(assign.c:206)
	at org.renjin.cran.data$table.assign__.alloccolwrapper(assign.c:226)
	at org.renjin.primitives.Native.redotCall(Native.java:351)
	at org.renjin.primitives.R$primitive$$Call.apply(R$primitive$$Call.java:62)
	at org.renjin.eval.Context.evaluateCall(Context.java:407)
	at org.renjin.eval.Context.evaluate(Context.java:282)
	at org.renjin.eval.Context.evaluate(Context.java:264)
	at org.renjin.primitives.special.AssignLeftFunction.assignLeft(AssignLeftFunction.java:57)
	at org.renjin.primitives.special.AssignLeftFunction.apply(AssignLeftFunction.java:41)
	at org.renjin.eval.Context.evaluateCall(Context.java:407)
	at org.renjin.eval.Context.evaluate(Context.java:282)
	at org.renjin.eval.Context.evaluate(Context.java:264)
	at org.renjin.primitives.special.BeginFunction.apply(BeginFunction.java:38)
	at org.renjin.eval.Context.evaluateCall(Context.java:407)
	at org.renjin.eval.Context.evaluate(Context.java:282)
	at org.renjin.eval.Context.evaluate(Context.java:264)
	at org.renjin.eval.Context.evaluate(Context.java:198)
	at org.renjin.sexp.Closure.doApply(Closure.java:97)
	at org.renjin.eval.ClosureDispatcher.apply(ClosureDispatcher.java:80)
	at org.renjin.eval.ClosureDispatcher.applyClosure(ClosureDispatcher.java:51)
	at org.renjin.sexp.Closure.apply(Closure.java:82)
	at org.renjin.eval.Context.evaluateCall(Context.java:407)
	at org.renjin.eval.Context.evaluate(Context.java:282)
	at org.renjin.eval.Context.evaluate(Context.java:264)
	at org.renjin.primitives.special.BeginFunction.apply(BeginFunction.java:38)
	at org.renjin.eval.Context.evaluateCall(Context.java:407)
	at org.renjin.eval.Context.evaluate(Context.java:282)
	at org.renjin.eval.Context.evaluate(Context.java:264)
	at org.renjin.eval.Context.evaluate(Context.java:198)
	at org.renjin.sexp.Closure.doApply(Closure.java:97)
	at org.renjin.eval.ClosureDispatcher.apply(ClosureDispatcher.java:80)
	at org.renjin.eval.ClosureDispatcher.applyClosure(ClosureDispatcher.java:51)
	at org.renjin.sexp.Closure.apply(Closure.java:82)
	at org.renjin.eval.Context.evaluateCall(Context.java:407)
	at org.renjin.eval.Context.evaluate(Context.java:282)
	at org.renjin.eval.Context.evaluate(Context.java:264)
	at org.renjin.primitives.special.ReturnFunction.apply(ReturnFunction.java:33)
	at org.renjin.eval.Context.evaluateCall(Context.java:407)
	at org.renjin.eval.Context.evaluate(Context.java:282)
	at org.renjin.eval.Context.evaluate(Context.java:264)
	at org.renjin.primitives.special.IfFunction.apply(IfFunction.java:40)
	at org.renjin.eval.Context.evaluateCall(Context.java:407)
	at org.renjin.eval.Context.evaluate(Context.java:282)
	at org.renjin.eval.Context.evaluate(Context.java:264)
	at org.renjin.primitives.special.BeginFunction.apply(BeginFunction.java:38)
	at org.renjin.eval.Context.evaluateCall(Context.java:407)
	at org.renjin.eval.Context.evaluate(Context.java:282)
	at org.renjin.eval.Context.evaluate(Context.java:264)
	at org.renjin.eval.Context.evaluate(Context.java:198)
	at org.renjin.sexp.Closure.doApply(Closure.java:97)
	at org.renjin.eval.ClosureDispatcher.apply(ClosureDispatcher.java:80)
	at org.renjin.eval.ClosureDispatcher.applyClosure(ClosureDispatcher.java:51)
	at org.renjin.sexp.Closure.apply(Closure.java:82)
	at org.renjin.eval.Context.evaluateCall(Context.java:407)
	at org.renjin.eval.Context.evaluate(Context.java:282)
	at org.renjin.eval.Context.evaluate(Context.java:264)
	at org.renjin.invoke.codegen.ArgumentIterator.evalNext(ArgumentIterator.java:70)
	at org.renjin.primitives.R$primitive$list.apply(R$primitive$list.java:32)
	at org.renjin.eval.Context.evaluateCall(Context.java:407)
	at org.renjin.eval.Context.evaluate(Context.java:282)
	at org.renjin.sexp.Promise.doEval(Promise.java:92)
	at org.renjin.sexp.Promise.force(Promise.java:86)
	at org.renjin.eval.Context.evaluateSymbol(Context.java:345)
	at org.renjin.eval.Context.evaluate(Context.java:278)
	at org.renjin.eval.Context.evaluate(Context.java:264)
	at org.renjin.invoke.codegen.ArgumentIterator.evalNext(ArgumentIterator.java:70)
	at org.renjin.primitives.R$primitive$identical.apply(R$primitive$identical.java:29)
	at org.renjin.primitives.special.InternalFunction.apply(InternalFunction.java:45)
	at org.renjin.eval.Context.evaluateCall(Context.java:407)
	at org.renjin.eval.Context.evaluate(Context.java:282)
	at org.renjin.eval.Context.evaluate(Context.java:264)
	at org.renjin.eval.Context.evaluate(Context.java:198)
	at org.renjin.sexp.Closure.doApply(Closure.java:97)
	at org.renjin.eval.ClosureDispatcher.apply(ClosureDispatcher.java:80)
	at org.renjin.eval.ClosureDispatcher.applyClosure(ClosureDispatcher.java:51)
	at org.renjin.sexp.Closure.apply(Closure.java:82)
	at org.renjin.eval.Context.evaluateCall(Context.java:407)
	at org.renjin.eval.Context.evaluate(Context.java:282)
	at org.renjin.eval.Context.evaluate(Context.java:264)
	at org.renjin.primitives.Comparison.or(Comparison.java:52)
	at org.renjin.primitives.R$primitive$$bar$bar.doApply(R$primitive$$bar$bar.java:68)
	at org.renjin.primitives.R$primitive$$bar$bar.apply(R$primitive$$bar$bar.java:29)
	at org.renjin.eval.Context.evaluateCall(Context.java:407)
	at org.renjin.eval.Context.evaluate(Context.java:282)
	at org.renjin.eval.Context.evaluate(Context.java:264)
	at org.renjin.primitives.special.IfFunction.apply(IfFunction.java:32)
	at org.renjin.eval.Context.evaluateCall(Context.java:407)
	at org.renjin.eval.Context.evaluate(Context.java:282)
	at org.renjin.eval.Context.evaluate(Context.java:264)
	at org.renjin.primitives.special.BeginFunction.apply(BeginFunction.java:38)
	at org.renjin.eval.Context.evaluateCall(Context.java:407)
	at org.renjin.eval.Context.evaluate(Context.java:282)
	at org.renjin.eval.Context.evaluate(Context.java:264)
	at org.renjin.eval.Context.evaluate(Context.java:198)
	at org.renjin.sexp.Closure.doApply(Closure.java:97)
	at org.renjin.eval.ClosureDispatcher.apply(ClosureDispatcher.java:80)
	at org.renjin.eval.ClosureDispatcher.applyClosure(ClosureDispatcher.java:51)
	at org.renjin.sexp.Closure.apply(Closure.java:82)
	at org.renjin.eval.Context.evaluateCall(Context.java:407)
	at org.renjin.eval.Context.evaluate(Context.java:282)
	at org.renjin.eval.Context.evaluate(Context.java:264)
	at org.renjin.primitives.special.AssignLeftFunction.assignLeft(AssignLeftFunction.java:57)
	at org.renjin.primitives.special.AssignLeftFunction.apply(AssignLeftFunction.java:41)
	at org.renjin.eval.Context.evaluateCall(Context.java:407)
	at org.renjin.eval.Context.evaluate(Context.java:282)
	at org.renjin.eval.Context.evaluate(Context.java:264)
	at org.renjin.eval.Context.evaluateExpressionVector(Context.java:390)
	at org.renjin.eval.Context.evaluate(Context.java:280)
	at org.renjin.eval.Context.evaluate(Context.java:264)
	at org.renjin.repl.JlineRepl.readExpression(JlineRepl.java:244)
	at org.renjin.repl.JlineRepl.run(JlineRepl.java:131)
	at org.renjin.cli.Main.startInteractive(Main.java:126)
	at org.renjin.cli.Main.run(Main.java:111)
	at org.renjin.cli.Main.main(Main.java:78)
  at alloc.col()
  at null.data.table()
  at data.table()
  at identical()
  at data.table()
Caused by:org.renjin.gnur.api.UnimplementedGnuApiMethod: Unimplemented GNU R API function 'DUPLICATE_ATTRIB'
	at org.renjin.gnur.api.Rinternals.DUPLICATE_ATTRIB(Rinternals.java:458)
	at org.renjin.cran.data$table.assign__.shallow(assign.c:154)
	at org.renjin.cran.data$table.assign__.alloccol(assign.c:206)
	at org.renjin.cran.data$table.assign__.alloccolwrapper(assign.c:226)
	at org.renjin.primitives.Native.redotCall(Native.java:351)
	at org.renjin.primitives.R$primitive$$Call.apply(R$primitive$$Call.java:62)
	at org.renjin.eval.Context.evaluateCall(Context.java:407)
	at org.renjin.eval.Context.evaluate(Context.java:282)
	at org.renjin.eval.Context.evaluate(Context.java:264)
	at org.renjin.primitives.special.AssignLeftFunction.assignLeft(AssignLeftFunction.java:57)
	at org.renjin.primitives.special.AssignLeftFunction.apply(AssignLeftFunction.java:41)
	at org.renjin.eval.Context.evaluateCall(Context.java:407)
	at org.renjin.eval.Context.evaluate(Context.java:282)
	at org.renjin.eval.Context.evaluate(Context.java:264)
	at org.renjin.primitives.special.BeginFunction.apply(BeginFunction.java:38)
	at org.renjin.eval.Context.evaluateCall(Context.java:407)
	at org.renjin.eval.Context.evaluate(Context.java:282)
	at org.renjin.eval.Context.evaluate(Context.java:264)
	at org.renjin.eval.Context.evaluate(Context.java:198)
	at org.renjin.sexp.Closure.doApply(Closure.java:97)
	at org.renjin.eval.ClosureDispatcher.apply(ClosureDispatcher.java:80)
	at org.renjin.eval.ClosureDispatcher.applyClosure(ClosureDispatcher.java:51)
	at org.renjin.sexp.Closure.apply(Closure.java:82)
	at org.renjin.eval.Context.evaluateCall(Context.java:407)
	at org.renjin.eval.Context.evaluate(Context.java:282)
	at org.renjin.eval.Context.evaluate(Context.java:264)
	at org.renjin.primitives.special.BeginFunction.apply(BeginFunction.java:38)
	at org.renjin.eval.Context.evaluateCall(Context.java:407)
	at org.renjin.eval.Context.evaluate(Context.java:282)
	at org.renjin.eval.Context.evaluate(Context.java:264)
	at org.renjin.eval.Context.evaluate(Context.java:198)
	at org.renjin.sexp.Closure.doApply(Closure.java:97)
	at org.renjin.eval.ClosureDispatcher.apply(ClosureDispatcher.java:80)
	at org.renjin.eval.ClosureDispatcher.applyClosure(ClosureDispatcher.java:51)
	at org.renjin.sexp.Closure.apply(Closure.java:82)
	at org.renjin.eval.Context.evaluateCall(Context.java:407)
	at org.renjin.eval.Context.evaluate(Context.java:282)
	at org.renjin.eval.Context.evaluate(Context.java:264)
	at org.renjin.primitives.special.ReturnFunction.apply(ReturnFunction.java:33)
	at org.renjin.eval.Context.evaluateCall(Context.java:407)
	at org.renjin.eval.Context.evaluate(Context.java:282)
	at org.renjin.eval.Context.evaluate(Context.java:264)
	at org.renjin.primitives.special.IfFunction.apply(IfFunction.java:40)
	at org.renjin.eval.Context.evaluateCall(Context.java:407)
	at org.renjin.eval.Context.evaluate(Context.java:282)
	at org.renjin.eval.Context.evaluate(Context.java:264)
	at org.renjin.primitives.special.BeginFunction.apply(BeginFunction.java:38)
	at org.renjin.eval.Context.evaluateCall(Context.java:407)
	at org.renjin.eval.Context.evaluate(Context.java:282)
	at org.renjin.eval.Context.evaluate(Context.java:264)
	at org.renjin.eval.Context.evaluate(Context.java:198)
	at org.renjin.sexp.Closure.doApply(Closure.java:97)
	at org.renjin.eval.ClosureDispatcher.apply(ClosureDispatcher.java:80)
	at org.renjin.eval.ClosureDispatcher.applyClosure(ClosureDispatcher.java:51)
	at org.renjin.sexp.Closure.apply(Closure.java:82)
	at org.renjin.eval.Context.evaluateCall(Context.java:407)
	at org.renjin.eval.Context.evaluate(Context.java:282)
	at org.renjin.eval.Context.evaluate(Context.java:264)
	at org.renjin.invoke.codegen.ArgumentIterator.evalNext(ArgumentIterator.java:70)
	at org.renjin.primitives.R$primitive$list.apply(R$primitive$list.java:32)
	at org.renjin.eval.Context.evaluateCall(Context.java:407)
	at org.renjin.eval.Context.evaluate(Context.java:282)
	at org.renjin.sexp.Promise.doEval(Promise.java:92)
	at org.renjin.sexp.Promise.force(Promise.java:86)
	at org.renjin.eval.Context.evaluateSymbol(Context.java:345)
	at org.renjin.eval.Context.evaluate(Context.java:278)
	at org.renjin.eval.Context.evaluate(Context.java:264)
	at org.renjin.invoke.codegen.ArgumentIterator.evalNext(ArgumentIterator.java:70)
	at org.renjin.primitives.R$primitive$identical.apply(R$primitive$identical.java:29)
	at org.renjin.primitives.special.InternalFunction.apply(InternalFunction.java:45)
	at org.renjin.eval.Context.evaluateCall(Context.java:407)
	at org.renjin.eval.Context.evaluate(Context.java:282)
	at org.renjin.eval.Context.evaluate(Context.java:264)
	at org.renjin.eval.Context.evaluate(Context.java:198)
	at org.renjin.sexp.Closure.doApply(Closure.java:97)
	at org.renjin.eval.ClosureDispatcher.apply(ClosureDispatcher.java:80)
	at org.renjin.eval.ClosureDispatcher.applyClosure(ClosureDispatcher.java:51)
	at org.renjin.sexp.Closure.apply(Closure.java:82)
	at org.renjin.eval.Context.evaluateCall(Context.java:407)
	at org.renjin.eval.Context.evaluate(Context.java:282)
	at org.renjin.eval.Context.evaluate(Context.java:264)
	at org.renjin.primitives.Comparison.or(Comparison.java:52)
	at org.renjin.primitives.R$primitive$$bar$bar.doApply(R$primitive$$bar$bar.java:68)
	at org.renjin.primitives.R$primitive$$bar$bar.apply(R$primitive$$bar$bar.java:29)
	at org.renjin.eval.Context.evaluateCall(Context.java:407)
	at org.renjin.eval.Context.evaluate(Context.java:282)
	at org.renjin.eval.Context.evaluate(Context.java:264)
	at org.renjin.primitives.special.IfFunction.apply(IfFunction.java:32)
	at org.renjin.eval.Context.evaluateCall(Context.java:407)
	at org.renjin.eval.Context.evaluate(Context.java:282)
	at org.renjin.eval.Context.evaluate(Context.java:264)
	at org.renjin.primitives.special.BeginFunction.apply(BeginFunction.java:38)
	at org.renjin.eval.Context.evaluateCall(Context.java:407)
	at org.renjin.eval.Context.evaluate(Context.java:282)
	at org.renjin.eval.Context.evaluate(Context.java:264)
	at org.renjin.eval.Context.evaluate(Context.java:198)
	at org.renjin.sexp.Closure.doApply(Closure.java:97)
	at org.renjin.eval.ClosureDispatcher.apply(ClosureDispatcher.java:80)
	at org.renjin.eval.ClosureDispatcher.applyClosure(ClosureDispatcher.java:51)
	at org.renjin.sexp.Closure.apply(Closure.java:82)
	at org.renjin.eval.Context.evaluateCall(Context.java:407)
	at org.renjin.eval.Context.evaluate(Context.java:282)
	at org.renjin.eval.Context.evaluate(Context.java:264)
	at org.renjin.primitives.special.AssignLeftFunction.assignLeft(AssignLeftFunction.java:57)
	at org.renjin.primitives.special.AssignLeftFunction.apply(AssignLeftFunction.java:41)
	at org.renjin.eval.Context.evaluateCall(Context.java:407)
	at org.renjin.eval.Context.evaluate(Context.java:282)
	at org.renjin.eval.Context.evaluate(Context.java:264)
	at org.renjin.eval.Context.evaluateExpressionVector(Context.java:390)
	at org.renjin.eval.Context.evaluate(Context.java:280)
	at org.renjin.eval.Context.evaluate(Context.java:264)
	at org.renjin.repl.JlineRepl.readExpression(JlineRepl.java:244)
	at org.renjin.repl.JlineRepl.run(JlineRepl.java:131)
	at org.renjin.cli.Main.startInteractive(Main.java:126)
	at org.renjin.cli.Main.run(Main.java:111)
	at org.renjin.cli.Main.main(Main.java:78)
```

**Comment by DaveJarvis** [comment]
**Replicate in R**
``` .R
install.packages( 'data.table' )
library( 'data.table' )
data.table( rnorm( 1000 ) )
```

Output:

```
               V1
   1: -0.83156807
   2: -0.70778388
   3:  0.18994777
   4: -1.71180599
   5: -0.14287603
  ---            
 996: -1.21141079
 997:  0.03574074
 998: -1.85942718
 999: -0.16675582
1000:  0.92554939
```

**Replicate in Renjin**
``` .R
library( 'data.table' )
```

Renjin hangs at this line.

**Comment by akbertram** [comment]
The `DUPLICATE_ATTRIB` function is part of the C API of GNU R. We provide an emulation layer for these calls in the gnur-runtime module. You can find the stub for this particular function here:
https://github.com/bedatadriven/renjin/blob/master/tools/gnur-runtime/src/main/java/org/renjin/gnur/api/Rinternals.java#L457

I'm not exactly sure how this function is supposed to behave, but you can find in the GNU R sources and I expect it's only a few lines.
