### ISSUE TITLE
glmnet: Could not resolve native method 'get_int_parms' in package 'glmnet'

### ISSUE THREAD

**Issue by chuanwen** [bedatadriven/renjin#353]
```
library(glmnet)
x = matrix(rnorm(3000), ncol=3)
y = rnorm(1000)
fit = glmnet(x, y)

ERROR: Could not resolve native method 'get_int_parms' in package 'glmnet'
  at glmnet.control()
  at glmnet()

```

**Comment by akbertram** [comment]
This error results from a compilation failure of the glmnet fortran code at build time:
http://packages.renjin.org/package/org.renjin.cran/glmnet/2.0-13/build/12

The Fortran compilation fails because of a few ridiculously large fortran subroutines that lead to JVM methods that exceed the 65k limit on method body bytecode. 

There will always be some hard limit on the size of functions we can compile, but in this case, I think we are only hitting the limit because of some unneccessary verbosity in the bytecode that our compiler generates. This is something we can fix.

**Comment by akbertram** [comment]
Fixed in the latest release: http://packages.renjin.org/package/org.renjin.cran/glmnet/2.0-13/build/14

**Comment by akbertram** [comment]
@chuanwen does this work for you now?

**Comment by chuanwen** [comment]
Can't install the package now.

```
Renjin 0.8.2515
Copyright (C) 2017 The R Foundation for Statistical Computing
Copyright (C) 2017 BeDataDriven
Falling back to pure JVM BLAS libraries.
> library(glmnet)
Could not resolve org.renjin.bioconductor:glmnet
Tried:
* https://repo1.maven.org/maven2/org/renjin/bioconductor/glmnet/maven-metadata.xml
* https://nexus.bedatadriven.com/content/groups/public/org/renjin/bioconductor/glmnet/maven-metadata.xml
Loaded org.renjin.cran.glmnet version 2.0-13-b14.
Could not resolve org.renjin.bioconductor:foreach
Tried:
* https://repo1.maven.org/maven2/org/renjin/bioconductor/foreach/maven-metadata.xml
* https://nexus.bedatadriven.com/content/groups/public/org/renjin/bioconductor/foreach/maven-metadata.xml
Could not resolve org.renjin.bioconductor:iterators
Tried:
* https://repo1.maven.org/maven2/org/renjin/bioconductor/iterators/maven-metadata.xml
* https://nexus.bedatadriven.com/content/groups/public/org/renjin/bioconductor/iterators/maven-metadata.xml
Could not resolve org.renjin.bioconductor:codetools
Tried:
* https://repo1.maven.org/maven2/org/renjin/bioconductor/codetools/maven-metadata.xml
* https://nexus.bedatadriven.com/content/groups/public/org/renjin/bioconductor/codetools/maven-metadata.xml
Could not resolve org.renjin.bioconductor:Matrix
Tried:
* https://repo1.maven.org/maven2/org/renjin/bioconductor/Matrix/maven-metadata.xml
* https://nexus.bedatadriven.com/content/groups/public/org/renjin/bioconductor/Matrix/maven-metadata.xml
Loading required package: Matrix
Loading required package: utils
Loading required package: foreach
Warning messages:
1: In library(glmnet) :
  Symbol 'memory.size' is not defined in package 'org.renjin:utils'
2: In library(glmnet) :
  Symbol 'object.size' is not defined in package 'org.renjin:utils'
Could not resolve org.renjin.bioconductor:lattice
Tried:
* https://repo1.maven.org/maven2/org/renjin/bioconductor/lattice/maven-metadata.xml
* https://nexus.bedatadriven.com/content/groups/public/org/renjin/bioconductor/lattice/maven-metadata.xml
```

**Comment by akbertram** [comment]
The messages do indeed look confusing, but i think they actually indicate that glmnet has loaded. (From cran, but not bioconductor)

Can you run search() to check?

**Comment by chuanwen** [comment]
search() gave me (after execute library(glmnet)):
[1] ".GlobalEnv"        "package:glmnet"    "package:foreach"  
[4] "package:Matrix"    "package:stats"     "package:graphics" 
[7] "package:grDevices" "package:utils"     "package:datasets" 
[10] "package:methods"   "package:base"     

copy my old reply here (I deleted it as I thought I might have made some mistake, I just repeated the process on my laptop and got the same result)

Downloaded latest renjin and unzipped it. Can't install the glmnet package.
```
Renjin 0.8.2515
Copyright (C) 2017 The R Foundation for Statistical Computing
Copyright (C) 2017 BeDataDriven
Using system BLAS libraries.
> library(glmnet)
Could not resolve org.renjin.bioconductor:glmnet
Tried:
* https://repo1.maven.org/maven2/org/renjin/bioconductor/glmnet/maven-metadata.xml
* https://nexus.bedatadriven.com/content/groups/public/org/renjin/bioconductor/glmnet/maven-metadata.xml
Loaded org.renjin.cran.glmnet version 2.0-13-b14.
Could not resolve org.renjin.bioconductor:foreach
Tried:
* https://repo1.maven.org/maven2/org/renjin/bioconductor/foreach/maven-metadata.xml
* https://nexus.bedatadriven.com/content/groups/public/org/renjin/bioconductor/foreach/maven-metadata.xml
Could not resolve org.renjin.bioconductor:iterators
Tried:
* https://repo1.maven.org/maven2/org/renjin/bioconductor/iterators/maven-metadata.xml
* https://nexus.bedatadriven.com/content/groups/public/org/renjin/bioconductor/iterators/maven-metadata.xml
Could not resolve org.renjin.bioconductor:codetools
Tried:
* https://repo1.maven.org/maven2/org/renjin/bioconductor/codetools/maven-metadata.xml
* https://nexus.bedatadriven.com/content/groups/public/org/renjin/bioconductor/codetools/maven-metadata.xml
Could not resolve org.renjin.bioconductor:Matrix
Tried:
* https://repo1.maven.org/maven2/org/renjin/bioconductor/Matrix/maven-metadata.xml
Loading required package: Matrix
Loading required package: utils
Loading required package: foreach
Warning messages:
1: In library(glmnet) :
  Symbol 'memory.size' is not defined in package 'org.renjin:utils'
2: In library(glmnet) :
  Symbol 'object.size' is not defined in package 'org.renjin:utils'
Could not resolve org.renjin.bioconductor:lattice
Tried:
* https://repo1.maven.org/maven2/org/renjin/bioconductor/lattice/maven-metadata.xml
* https://nexus.bedatadriven.com/content/groups/public/org/renjin/bioconductor/lattice/maven-metadata.xml
```

**Comment by akbertram** [comment]
Looks like glmnet is loaded onto your search path, right after the global environment.

Do you any problem using the glmnet() function?

**Comment by chuanwen** [comment]
glmnet function indeed works now. cv.glmnet function does not work yet. Thanks for such a quick fix of the original bug!
```
> x = matrix(rnorm(3000), ncol=3)
> y = rnorm(1000)
> fit = glmnet(x, y)
> fit
> fit = cv.glmnet(x, y)
ERROR: invalid or not-yet-implemented 'Matrix' subsetting
  at stop()
  at function(x=<missing_arg>, i=<missing_arg>, j=<missing_arg>, ...=<missing_arg>, drop=TRUE)()
  at nrow()
  at nonzeroCoef()
  at predict.glmnet()
  at NextMethod()
  at predict.elnet()
  at predict()
  at is.vector()
  at lapply()
  at sapply()
  at cv.glmnet()
```

**Comment by chuanwen** [comment]
also the predict function does not work

```
x = matrix(rnorm(3000), ncol=3)
y = rnorm(1000)
fit = glmnet(x, y)
ypred = predict(fit, x)

ERROR: error in evaluating the argument 'x' in selecting a method for function 'as.matrix'
org.renjin.eval.EvalException: Conversion = '*'
	at org.renjin.eval.Context.evaluateCall(Context.java:416)
	at org.renjin.eval.Context.evaluate(Context.java:282)
	at org.renjin.sexp.Promise.doEval(Promise.java:92)
	at org.renjin.sexp.Promise.force(Promise.java:86)
	at org.renjin.eval.Context.evaluateSymbol(Context.java:345)
	at org.renjin.eval.Context.evaluate(Context.java:278)
	at org.renjin.eval.Context.evaluate(Context.java:264)
	at org.renjin.methods.MethodDispatch.R_dispatchGeneric(MethodDispatch.java:191)
	at org.renjin.methods.MethodDispatch.standardGeneric(MethodDispatch.java:137)
	at org.renjin.methods.Methods.standardGeneric(Methods.java:369)
	at org.renjin.primitives.R$primitive$standardGeneric.doApply(R$primitive$standardGeneric.java:79)
	at org.renjin.primitives.R$primitive$standardGeneric.apply(R$primitive$standardGeneric.java:33)
	at org.renjin.eval.Context.evaluateCall(Context.java:407)
	at org.renjin.eval.Context.evaluate(Context.java:282)
	at org.renjin.eval.Context.evaluate(Context.java:264)
	at org.renjin.eval.Context.evaluate(Context.java:198)
	at org.renjin.sexp.Closure.doApply(Closure.java:97)
	at org.renjin.eval.ClosureDispatcher.apply(ClosureDispatcher.java:80)
	at org.renjin.eval.ClosureDispatcher.applyClosure(ClosureDispatcher.java:51)
	at org.renjin.sexp.Closure.apply(Closure.java:82)
	at org.renjin.eval.Context.evaluateCall(Context.java:407)
	at org.renjin.eval.Context.evaluate(Context.java:282)
	at org.renjin.eval.Context.evaluate(Context.java:264)
	at org.renjin.primitives.special.AssignLeftFunction.assignLeft(AssignLeftFunction.java:57)
	at org.renjin.primitives.special.AssignLeftFunction.apply(AssignLeftFunction.java:41)
	at org.renjin.eval.Context.evaluateCall(Context.java:407)
	at org.renjin.eval.Context.evaluate(Context.java:282)
	at org.renjin.eval.Context.evaluate(Context.java:264)
	at org.renjin.primitives.special.BeginFunction.apply(BeginFunction.java:38)
	at org.renjin.eval.Context.evaluateCall(Context.java:407)
	at org.renjin.eval.Context.evaluate(Context.java:282)
	at org.renjin.eval.Context.evaluate(Context.java:264)
	at org.renjin.eval.Calls.applyClosure(Calls.java:47)
	at org.renjin.primitives.S3$GenericMethod.doApply(S3.java:1452)
	at org.renjin.primitives.S3$GenericMethod.applyNext(S3.java:1411)
	at org.renjin.primitives.S3.NextMethod(S3.java:91)
	at org.renjin.primitives.R$primitive$NextMethod.apply(R$primitive$NextMethod.java:42)
	at org.renjin.primitives.special.InternalFunction.apply(InternalFunction.java:45)
	at org.renjin.eval.Context.evaluateCall(Context.java:407)
	at org.renjin.eval.Context.evaluate(Context.java:282)
	at org.renjin.eval.Context.evaluate(Context.java:264)
	at org.renjin.eval.Context.evaluate(Context.java:198)
	at org.renjin.sexp.Closure.doApply(Closure.java:97)
	at org.renjin.eval.ClosureDispatcher.apply(ClosureDispatcher.java:80)
	at org.renjin.eval.ClosureDispatcher.applyClosure(ClosureDispatcher.java:51)
	at org.renjin.sexp.Closure.apply(Closure.java:82)
	at org.renjin.eval.Context.evaluateCall(Context.java:407)
	at org.renjin.eval.Context.evaluate(Context.java:282)
	at org.renjin.eval.Context.evaluate(Context.java:264)
	at org.renjin.primitives.special.BeginFunction.apply(BeginFunction.java:38)
	at org.renjin.eval.Context.evaluateCall(Context.java:407)
	at org.renjin.eval.Context.evaluate(Context.java:282)
	at org.renjin.eval.Context.evaluate(Context.java:264)
	at org.renjin.eval.Calls.applyClosure(Calls.java:47)
	at org.renjin.primitives.S3$GenericMethod.doApply(S3.java:1452)
	at org.renjin.primitives.S3$GenericMethod.apply(S3.java:1401)
	at org.renjin.primitives.S3.UseMethod(S3.java:80)
	at org.renjin.primitives.S3.UseMethod(S3.java:72)
	at org.renjin.primitives.R$primitive$UseMethod.doApply(R$primitive$UseMethod.java:77)
	at org.renjin.primitives.R$primitive$UseMethod.apply(R$primitive$UseMethod.java:31)
	at org.renjin.eval.Context.evaluateCall(Context.java:407)
	at org.renjin.eval.Context.evaluate(Context.java:282)
	at org.renjin.eval.Context.evaluate(Context.java:264)
	at org.renjin.eval.Context.evaluate(Context.java:198)
	at org.renjin.sexp.Closure.doApply(Closure.java:97)
	at org.renjin.eval.ClosureDispatcher.apply(ClosureDispatcher.java:80)
	at org.renjin.eval.ClosureDispatcher.applyClosure(ClosureDispatcher.java:51)
	at org.renjin.sexp.Closure.apply(Closure.java:82)
	at org.renjin.eval.Context.evaluateCall(Context.java:407)
	at org.renjin.eval.Context.evaluate(Context.java:282)
	at org.renjin.eval.Context.evaluate(Context.java:264)
	at org.renjin.primitives.special.AssignLeftFunction.assignLeft(AssignLeftFunction.java:57)
	at org.renjin.primitives.special.AssignLeftFunction.apply(AssignLeftFunction.java:41)
	at org.renjin.eval.Context.evaluateCall(Context.java:407)
	at org.renjin.eval.Context.evaluate(Context.java:282)
	at org.renjin.eval.Context.evaluate(Context.java:264)
	at org.renjin.eval.Context.evaluateExpressionVector(Context.java:390)
	at org.renjin.eval.Context.evaluate(Context.java:280)
	at org.renjin.eval.Context.evaluate(Context.java:264)
	at org.renjin.repl.JlineRepl.readExpression(JlineRepl.java:244)
	at org.renjin.repl.JlineRepl.run(JlineRepl.java:131)
	at org.renjin.cli.Main.startInteractive(Main.java:126)
	at org.renjin.cli.Main.run(Main.java:111)
	at org.renjin.cli.Main.main(Main.java:78)
Caused by: java.util.UnknownFormatConversionException: Conversion = '*'
	at java.util.Formatter.checkText(Formatter.java:2579)
	at java.util.Formatter.parse(Formatter.java:2555)
	at java.util.Formatter.format(Formatter.java:2501)
	at java.util.Formatter.format(Formatter.java:2455)
	at java.lang.String.format(String.java:2940)
	at org.renjin.primitives.R$primitive$$percent$times$percent.doApply(R$primitive$$percent$times$percent.java:73)
	at org.renjin.primitives.R$primitive$$percent$times$percent.apply(R$primitive$$percent$times$percent.java:31)
	at org.renjin.eval.Context.evaluateCall(Context.java:407)
	... 83 more
  at as.matrix()
  at predict.glmnet()
  at NextMethod()
  at predict.elnet()
  at predict()
Caused by:org.renjin.eval.EvalException: Conversion = '*'
	at org.renjin.eval.Context.evaluateCall(Context.java:416)
	at org.renjin.eval.Context.evaluate(Context.java:282)
	at org.renjin.sexp.Promise.doEval(Promise.java:92)
	at org.renjin.sexp.Promise.force(Promise.java:86)
	at org.renjin.eval.Context.evaluateSymbol(Context.java:345)
	at org.renjin.eval.Context.evaluate(Context.java:278)
	at org.renjin.eval.Context.evaluate(Context.java:264)
	at org.renjin.methods.MethodDispatch.R_dispatchGeneric(MethodDispatch.java:191)
	at org.renjin.methods.MethodDispatch.standardGeneric(MethodDispatch.java:137)
	at org.renjin.methods.Methods.standardGeneric(Methods.java:369)
	at org.renjin.primitives.R$primitive$standardGeneric.doApply(R$primitive$standardGeneric.java:79)
	at org.renjin.primitives.R$primitive$standardGeneric.apply(R$primitive$standardGeneric.java:33)
	at org.renjin.eval.Context.evaluateCall(Context.java:407)
	at org.renjin.eval.Context.evaluate(Context.java:282)
	at org.renjin.eval.Context.evaluate(Context.java:264)
	at org.renjin.eval.Context.evaluate(Context.java:198)
	at org.renjin.sexp.Closure.doApply(Closure.java:97)
	at org.renjin.eval.ClosureDispatcher.apply(ClosureDispatcher.java:80)
	at org.renjin.eval.ClosureDispatcher.applyClosure(ClosureDispatcher.java:51)
	at org.renjin.sexp.Closure.apply(Closure.java:82)
	at org.renjin.eval.Context.evaluateCall(Context.java:407)
	at org.renjin.eval.Context.evaluate(Context.java:282)
	at org.renjin.eval.Context.evaluate(Context.java:264)
	at org.renjin.primitives.special.AssignLeftFunction.assignLeft(AssignLeftFunction.java:57)
	at org.renjin.primitives.special.AssignLeftFunction.apply(AssignLeftFunction.java:41)
	at org.renjin.eval.Context.evaluateCall(Context.java:407)
	at org.renjin.eval.Context.evaluate(Context.java:282)
	at org.renjin.eval.Context.evaluate(Context.java:264)
	at org.renjin.primitives.special.BeginFunction.apply(BeginFunction.java:38)
	at org.renjin.eval.Context.evaluateCall(Context.java:407)
	at org.renjin.eval.Context.evaluate(Context.java:282)
	at org.renjin.eval.Context.evaluate(Context.java:264)
	at org.renjin.eval.Calls.applyClosure(Calls.java:47)
	at org.renjin.primitives.S3$GenericMethod.doApply(S3.java:1452)
	at org.renjin.primitives.S3$GenericMethod.applyNext(S3.java:1411)
	at org.renjin.primitives.S3.NextMethod(S3.java:91)
	at org.renjin.primitives.R$primitive$NextMethod.apply(R$primitive$NextMethod.java:42)
	at org.renjin.primitives.special.InternalFunction.apply(InternalFunction.java:45)
	at org.renjin.eval.Context.evaluateCall(Context.java:407)
	at org.renjin.eval.Context.evaluate(Context.java:282)
	at org.renjin.eval.Context.evaluate(Context.java:264)
	at org.renjin.eval.Context.evaluate(Context.java:198)
	at org.renjin.sexp.Closure.doApply(Closure.java:97)
	at org.renjin.eval.ClosureDispatcher.apply(ClosureDispatcher.java:80)
	at org.renjin.eval.ClosureDispatcher.applyClosure(ClosureDispatcher.java:51)
	at org.renjin.sexp.Closure.apply(Closure.java:82)
	at org.renjin.eval.Context.evaluateCall(Context.java:407)
	at org.renjin.eval.Context.evaluate(Context.java:282)
	at org.renjin.eval.Context.evaluate(Context.java:264)
	at org.renjin.primitives.special.BeginFunction.apply(BeginFunction.java:38)
	at org.renjin.eval.Context.evaluateCall(Context.java:407)
	at org.renjin.eval.Context.evaluate(Context.java:282)
	at org.renjin.eval.Context.evaluate(Context.java:264)
	at org.renjin.eval.Calls.applyClosure(Calls.java:47)
	at org.renjin.primitives.S3$GenericMethod.doApply(S3.java:1452)
	at org.renjin.primitives.S3$GenericMethod.apply(S3.java:1401)
	at org.renjin.primitives.S3.UseMethod(S3.java:80)
	at org.renjin.primitives.S3.UseMethod(S3.java:72)
	at org.renjin.primitives.R$primitive$UseMethod.doApply(R$primitive$UseMethod.java:77)
	at org.renjin.primitives.R$primitive$UseMethod.apply(R$primitive$UseMethod.java:31)
	at org.renjin.eval.Context.evaluateCall(Context.java:407)
	at org.renjin.eval.Context.evaluate(Context.java:282)
	at org.renjin.eval.Context.evaluate(Context.java:264)
	at org.renjin.eval.Context.evaluate(Context.java:198)
	at org.renjin.sexp.Closure.doApply(Closure.java:97)
	at org.renjin.eval.ClosureDispatcher.apply(ClosureDispatcher.java:80)
	at org.renjin.eval.ClosureDispatcher.applyClosure(ClosureDispatcher.java:51)
	at org.renjin.sexp.Closure.apply(Closure.java:82)
	at org.renjin.eval.Context.evaluateCall(Context.java:407)
	at org.renjin.eval.Context.evaluate(Context.java:282)
	at org.renjin.eval.Context.evaluate(Context.java:264)
	at org.renjin.primitives.special.AssignLeftFunction.assignLeft(AssignLeftFunction.java:57)
	at org.renjin.primitives.special.AssignLeftFunction.apply(AssignLeftFunction.java:41)
	at org.renjin.eval.Context.evaluateCall(Context.java:407)
	at org.renjin.eval.Context.evaluate(Context.java:282)
	at org.renjin.eval.Context.evaluate(Context.java:264)
	at org.renjin.eval.Context.evaluateExpressionVector(Context.java:390)
	at org.renjin.eval.Context.evaluate(Context.java:280)
	at org.renjin.eval.Context.evaluate(Context.java:264)
	at org.renjin.repl.JlineRepl.readExpression(JlineRepl.java:244)
	at org.renjin.repl.JlineRepl.run(JlineRepl.java:131)
	at org.renjin.cli.Main.startInteractive(Main.java:126)
	at org.renjin.cli.Main.run(Main.java:111)
	at org.renjin.cli.Main.main(Main.java:78)
Caused by: java.util.UnknownFormatConversionException: Conversion = '*'
	at java.util.Formatter.checkText(Formatter.java:2579)
	at java.util.Formatter.parse(Formatter.java:2555)
	at java.util.Formatter.format(Formatter.java:2501)
	at java.util.Formatter.format(Formatter.java:2455)
	at java.lang.String.format(String.java:2940)
	at org.renjin.primitives.R$primitive$$percent$times$percent.doApply(R$primitive$$percent$times$percent.java:73)
	at org.renjin.primitives.R$primitive$$percent$times$percent.apply(R$primitive$$percent$times$percent.java:31)
	at org.renjin.eval.Context.evaluateCall(Context.java:407)
	... 83 more
```

**Comment by chuanwen** [comment]
The warning message appears whenever I restart renjin and do library(glmnet), even though glmnet was already installed.

```
library(glmnet)

Renjin 0.8.2515
Copyright (C) 2017 The R Foundation for Statistical Computing
Copyright (C) 2017 BeDataDriven
Using system BLAS libraries.
Could not resolve org.renjin.bioconductor:glmnet
Tried:
* https://repo1.maven.org/maven2/org/renjin/bioconductor/glmnet/maven-metadata.xml
* https://nexus.bedatadriven.com/content/groups/public/org/renjin/bioconductor/glmnet/maven-metadata.xml
Could not resolve org.renjin.bioconductor:foreach
Tried:
* https://repo1.maven.org/maven2/org/renjin/bioconductor/foreach/maven-metadata.xml
Could not resolve org.renjin.bioconductor:iterators
Tried:
* https://repo1.maven.org/maven2/org/renjin/bioconductor/iterators/maven-metadata.xml
Could not resolve org.renjin.bioconductor:codetools
Tried:
* https://repo1.maven.org/maven2/org/renjin/bioconductor/codetools/maven-metadata.xml
Could not resolve org.renjin.bioconductor:Matrix
Tried:
* https://repo1.maven.org/maven2/org/renjin/bioconductor/Matrix/maven-metadata.xml
Loading required package: Matrix
Loading required package: utils
Loading required package: foreach
Warning messages:
1: In library(glmnet) :
  Symbol 'memory.size' is not defined in package 'org.renjin:utils'
2: In library(glmnet) :
  Symbol 'object.size' is not defined in package 'org.renjin:utils'
Could not resolve org.renjin.bioconductor:lattice
Tried:
* https://repo1.maven.org/maven2/org/renjin/bioconductor/lattice/maven-metadata.xml
* https://nexus.bedatadriven.com/content/groups/public/org/renjin/bioconductor/lattice/maven-metadata.xml

```

**Comment by chuanwen** [comment]
Added two new issues: one for the prediction function (issue 356), one for the cv.glmnet function (issue 355).

**Comment by chuanwen** [comment]
Added a new issue(357) for the misleading warning message.
