### ISSUE TITLE
IOException while loading package org.renjin.cran:rgeos: Could not resolve native method 'rgeos_Init' in package 'rgeos'

### ISSUE THREAD

**Issue by lucky1ravi** [bedatadriven/renjin#387]
Hi I am new to R language and renjin. In my project following is the maven dependency added.
`<dependency>
        <groupId>org.renjin.cran</groupId>
        <artifactId>rgeos</artifactId>
        <version>0.3-2-b24</version>
    </dependency>`
I have added the above dependency. also I tried with different and latest version of rgeos dependency.

I am loding rgeos package in code as engine.eval("library(rgeos)"); While loading this package in java I am getting below error
`org.renjin.eval.EvalException: IOException while loading package org.renjin.cran:rgeos: Could not resolve native method 'rgeos_Init' in package 'rgeos'
    at org.renjin.primitives.packaging.NamespaceRegistry.tryLoad(NamespaceRegistry.java:215)
    at org.renjin.primitives.packaging.NamespaceRegistry.tryGetNamespace(NamespaceRegistry.java:168)
    at org.renjin.primitives.packaging.NamespaceRegistry.getNamespace(NamespaceRegistry.java:130)
    at org.renjin.primitives.packaging.NamespaceRegistry.getNamespace(NamespaceRegistry.java:98)
    at org.renjin.primitives.packaging.Packages.library(Packages.java:40)
    at org.renjin.primitives.R$primitive$library.doApply(R$primitive$library.java:73)
    at org.renjin.primitives.R$primitive$library.apply(R$primitive$library.java:34)
    at org.renjin.primitives.special.InternalFunction.apply(InternalFunction.java:45)
    at org.renjin.eval.Context.evaluateCall(Context.java:407)
    at org.renjin.eval.Context.evaluate(Context.java:282)
    at org.renjin.eval.Context.evaluate(Context.java:264)
    at org.renjin.primitives.special.BeginFunction.apply(BeginFunction.java:38)
    at org.renjin.eval.Context.evaluateCall(Context.java:407)
    at org.renjin.eval.Context.evaluate(Context.java:282)
    at org.renjin.eval.Context.evaluate(Context.java:264)
    at org.renjin.eval.Context.evaluate(Context.java:198)
    at org.renjin.sexp.Closure.doApply(Closure.java:98)
    at org.renjin.eval.ClosureDispatcher.apply(ClosureDispatcher.java:80)
    at org.renjin.eval.ClosureDispatcher.applyClosure(ClosureDispatcher.java:51)
    at org.renjin.sexp.Closure.apply(Closure.java:83)
    at org.renjin.eval.Context.evaluateCall(Context.java:407)
    at org.renjin.eval.Context.evaluate(Context.java:282)
    at org.renjin.eval.Context.evaluate(Context.java:264)
    at org.renjin.eval.Context.evaluateExpressionVector(Context.java:390)
    at org.renjin.eval.Context.evaluate(Context.java:280)
    at org.renjin.eval.Context.evaluate(Context.java:264)
    at org.renjin.script.RenjinScriptEngine.eval(RenjinScriptEngine.java:168)
    at org.renjin.script.RenjinScriptEngine.eval(RenjinScriptEngine.java:127)
    at com.nact.Test.main(Test.java:21)
Caused by: org.renjin.eval.EvalException: Could not resolve native method 'rgeos_Init' in package 'rgeos'
    at org.renjin.primitives.Native.findMethodByName(Native.java:572)
    at org.renjin.primitives.Native.findMethod(Native.java:545)
    at org.renjin.primitives.Native.redotCall(Native.java:364)
    at org.renjin.primitives.R$primitive$$Call.apply(R$primitive$$Call.java:62)
    at org.renjin.eval.Context.evaluateCall(Context.java:407)
    at org.renjin.eval.Context.evaluate(Context.java:282)
    at org.renjin.eval.Context.evaluate(Context.java:264)
    at org.renjin.primitives.special.BeginFunction.apply(BeginFunction.java:38)
    at org.renjin.eval.Context.evaluateCall(Context.java:407)
    at org.renjin.eval.Context.evaluate(Context.java:282)
    at org.renjin.eval.Context.evaluate(Context.java:264)
    at org.renjin.eval.Context.evaluate(Context.java:198)
    at org.renjin.sexp.Closure.doApply(Closure.java:98)
    at org.renjin.eval.ClosureDispatcher.apply(ClosureDispatcher.java:80)
    at org.renjin.eval.ClosureDispatcher.applyClosure(ClosureDispatcher.java:51)
    at org.renjin.sexp.Closure.apply(Closure.java:83)
    at org.renjin.eval.Context.evaluateCall(Context.java:407)
    at org.renjin.eval.Context.evaluate(Context.java:282)
    at org.renjin.sexp.Promise.doEval(Promise.java:92)
    at org.renjin.sexp.Promise.force(Promise.java:86)
    at org.renjin.eval.Context.evaluateSymbol(Context.java:345)
    at org.renjin.eval.Context.evaluate(Context.java:278)
    at org.renjin.sexp.Promise.doEval(Promise.java:92)
    at org.renjin.sexp.Promise.force(Promise.java:86)
    at org.renjin.eval.Context.evaluateSymbol(Context.java:345)
    at org.renjin.eval.Context.evaluate(Context.java:278)
    at org.renjin.eval.Context.evaluate(Context.java:264)
    at org.renjin.invoke.codegen.ArgumentIterator.evalNext(ArgumentIterator.java:70)
    at org.renjin.primitives.R$primitive$assign.apply(R$primitive$assign.java:30)
    at org.renjin.primitives.special.InternalFunction.apply(InternalFunction.java:45)
    at org.renjin.eval.Context.evaluateCall(Context.java:407)
    at org.renjin.eval.Context.evaluate(Context.java:282)
    at org.renjin.eval.Context.evaluate(Context.java:264)
    at org.renjin.eval.Context.evaluate(Context.java:198)
    at org.renjin.sexp.Closure.doApply(Closure.java:98)
    at org.renjin.eval.ClosureDispatcher.apply(ClosureDispatcher.java:80)
    at org.renjin.eval.ClosureDispatcher.applyClosure(ClosureDispatcher.java:51)
    at org.renjin.sexp.Closure.apply(Closure.java:83)
    at org.renjin.eval.Context.evaluateCall(Context.java:407)
    at org.renjin.eval.Context.evaluate(Context.java:282)
    at org.renjin.eval.Context.evaluate(Context.java:264)
    at org.renjin.primitives.special.BeginFunction.apply(BeginFunction.java:38)
    at org.renjin.eval.Context.evaluateCall(Context.java:407)
    at org.renjin.eval.Context.evaluate(Context.java:282)
    at org.renjin.eval.Context.evaluate(Context.java:264)
    at org.renjin.eval.Context.evaluate(Context.java:198)
    at org.renjin.sexp.Closure.doApply(Closure.java:98)
    at org.renjin.eval.ClosureDispatcher.apply(ClosureDispatcher.java:80)
    at org.renjin.eval.ClosureDispatcher.applyClosure(ClosureDispatcher.java:51)
    at org.renjin.sexp.Closure.apply(Closure.java:83)
    at org.renjin.eval.Context.evaluateCall(Context.java:407)
    at org.renjin.eval.Context.evaluate(Context.java:282)
    at org.renjin.eval.Context.evaluate(Context.java:264)
    at org.renjin.primitives.special.BeginFunction.apply(BeginFunction.java:38)
    at org.renjin.eval.Context.evaluateCall(Context.java:407)
    at org.renjin.eval.Context.evaluate(Context.java:282)
    at org.renjin.eval.Context.evaluate(Context.java:264)
    at org.renjin.eval.Context.evaluate(Context.java:198)
    at org.renjin.sexp.Closure.doApply(Closure.java:98)
    at org.renjin.eval.ClosureDispatcher.apply(ClosureDispatcher.java:80)
    at org.renjin.eval.ClosureDispatcher.applyClosure(ClosureDispatcher.java:51)
    at org.renjin.sexp.Closure.apply(Closure.java:83)
    at org.renjin.eval.Context.evaluateCall(Context.java:407)
    at org.renjin.eval.Context.evaluate(Context.java:282)
    at org.renjin.eval.Context.evaluate(Context.java:264)
    at org.renjin.primitives.packaging.NamespaceRegistry.tryLoad(NamespaceRegistry.java:198)
    ... 28 more`

**Comment by psolaimani** [comment]
You can check the state of a package on [packages.renjin.org](packages.renjin.org). Here you can search for you package **rgeos** which will talke you to the [rgeos package page](http://packages.renjin.org/package/org.renjin.cran/rgeos).

On the package page you can see that status says:
> This package can be loaded by Renjin but there was an error compiling C/FORTRAN sources and all tests failed. An older version of this package is more compatible with Renjin. 

If you scroll further down you can see that all the tests are currently failing. You can either click "**View build log**" or on one of the failing tests to see the exact cause of the failure. In this case, all the tests are failing due to the same reason as you are experiencing.

From the **Build log** at top of the page I see that the build is not going well because ./configure step is not successful:
> checking for /usr/bin/svnversion... no
> configure: error: geos-config not found or not executable.
> configure: svn revision: 560
> checking for geos-config... no
> no
> [ERROR] Compilation of GNU R sources failed.
> org.renjin.gcc.InternalCompilerException: Failed to execute ./configure
> 	at org.renjin.packaging.NativeSourceBuilder.configure(NativeSourceBuilder.java:97)

it might be that this is due to missing dependencies on our build machine. in this case you could try to build this package locally. By clicking the bottom left button "**BUILD LOCALLY**" which will give you a link that you can paste and run on your terminal. in this case:
> curl http://packages.renjin.org/package/org.renjin.cran/rgeos/0.3-26/build/4/rebuild.sh | sh

you can see this link bellow the "**Build log**" section.

Please let us know if you could build this locally. We have some level of support for processing the configure and make files used in packages. But we not yet support all the manipulations that can be done within the build scripts, and **rgeos** has a pretty extensive [configure](https://github.com/cran/rgeos/blob/0.3-26/configure) file.
