### ISSUE TITLE
"org.renjin.eval.EvalException: object 'PostScript' not found" when attempting to plot tree using post.rpart

### ISSUE THREAD

**Issue by domtoupin** [bedatadriven/renjin#402]
Using CRAN R implementation, the following works as expected, plotting the resulting tree in a file named MCVE.ps:

``` R
mydata <- data.frame(ID = c(1,2,3), Input = c(TRUE, FALSE, TRUE), DesiredOutput = c(TRUE, FALSE, TRUE))

library(rpart) # load the rpart package

mytree <- rpart(DesiredOutput ~ Input, data = mydata, method = "class", minsplit = 2, minbucket = 1)

post(mytree, filename='MCVE.ps')
```

However, using renjin, an exception is thrown:
``` java
import javax.script.ScriptException;

import org.renjin.script.RenjinScriptEngine;
import org.renjin.script.RenjinScriptEngineFactory;

public class ErrorRenjin
{
	public static void main(String[] args)
	{
		RenjinScriptEngineFactory scriptEngineFactory = new RenjinScriptEngineFactory();
		RenjinScriptEngine renjinScriptEngine = scriptEngineFactory.getScriptEngine();

		try
		{
			renjinScriptEngine.eval("mydata <- data.frame(ID = c(1,2,3), Input = c(TRUE, FALSE, TRUE), DesiredOutput = c(TRUE, FALSE, TRUE))");
			renjinScriptEngine.eval("library(rpart) # load the rpart package\n");
			renjinScriptEngine.eval("mytree <- rpart(DesiredOutput ~ Input, data = mydata, method = \"class\", minsplit = 2, minbucket = 1)");
			renjinScriptEngine.eval("post(mytree, filename='MCVE.ps')");
		}
		catch (ScriptException e)
		{
			e.printStackTrace();
		}
	}
}
```
Exception stack:
``` java
Exception in thread "main" org.renjin.eval.EvalException: object 'PostScript' not found
	at org.renjin.eval.Context.evaluateSymbol(Context.java:335)
	at org.renjin.eval.Context.evaluate(Context.java:278)
	at org.renjin.eval.Context.evaluate(Context.java:264)
	at org.renjin.invoke.codegen.ArgumentIterator.evalNext(ArgumentIterator.java:70)
	at org.renjin.primitives.R$primitive$$External.apply(R$primitive$$External.java:34)
	at org.renjin.eval.Context.evaluateCall(Context.java:407)
	at org.renjin.eval.Context.evaluate(Context.java:282)
	at org.renjin.eval.Context.evaluate(Context.java:264)
	at org.renjin.primitives.special.BeginFunction.apply(BeginFunction.java:38)
	at org.renjin.eval.Context.evaluateCall(Context.java:407)
	at org.renjin.eval.Context.evaluate(Context.java:282)
	at org.renjin.eval.Context.evaluate(Context.java:264)
	at org.renjin.eval.Context.evaluate(Context.java:198)
	at org.renjin.sexp.Closure.doApply(Closure.java:98)
	at org.renjin.eval.ClosureDispatcher.apply(ClosureDispatcher.java:80)
	at org.renjin.eval.ClosureDispatcher.applyClosure(ClosureDispatcher.java:51)
	at org.renjin.sexp.Closure.apply(Closure.java:83)
	at org.renjin.eval.Context.evaluateCall(Context.java:407)
	at org.renjin.eval.Context.evaluate(Context.java:282)
	at org.renjin.eval.Context.evaluate(Context.java:264)
	at org.renjin.primitives.special.BeginFunction.apply(BeginFunction.java:38)
	at org.renjin.eval.Context.evaluateCall(Context.java:407)
	at org.renjin.eval.Context.evaluate(Context.java:282)
	at org.renjin.eval.Context.evaluate(Context.java:264)
	at org.renjin.primitives.special.IfFunction.apply(IfFunction.java:40)
	at org.renjin.eval.Context.evaluateCall(Context.java:407)
	at org.renjin.eval.Context.evaluate(Context.java:282)
	at org.renjin.eval.Context.evaluate(Context.java:264)
	at org.renjin.primitives.special.BeginFunction.apply(BeginFunction.java:38)
	at org.renjin.eval.Context.evaluateCall(Context.java:407)
	at org.renjin.eval.Context.evaluate(Context.java:282)
	at org.renjin.eval.Context.evaluate(Context.java:264)
	at org.renjin.eval.Calls.applyClosure(Calls.java:47)
	at org.renjin.primitives.S3$GenericMethod.doApply(S3.java:1459)
	at org.renjin.primitives.S3$GenericMethod.apply(S3.java:1408)
	at org.renjin.primitives.S3.UseMethod(S3.java:84)
	at org.renjin.primitives.S3.UseMethod(S3.java:72)
	at org.renjin.primitives.R$primitive$UseMethod.doApply(R$primitive$UseMethod.java:77)
	at org.renjin.primitives.R$primitive$UseMethod.apply(R$primitive$UseMethod.java:31)
	at org.renjin.eval.Context.evaluateCall(Context.java:407)
	at org.renjin.eval.Context.evaluate(Context.java:282)
	at org.renjin.eval.Context.evaluate(Context.java:264)
	at org.renjin.eval.Context.evaluate(Context.java:198)
	at org.renjin.sexp.Closure.doApply(Closure.java:98)
	at org.renjin.eval.ClosureDispatcher.apply(ClosureDispatcher.java:80)
	at org.renjin.eval.ClosureDispatcher.applyClosure(ClosureDispatcher.java:51)
	at org.renjin.sexp.Closure.apply(Closure.java:83)
	at org.renjin.eval.Context.evaluateCall(Context.java:407)
	at org.renjin.eval.Context.evaluate(Context.java:282)
	at org.renjin.eval.Context.evaluate(Context.java:264)
	at org.renjin.eval.Context.evaluateExpressionVector(Context.java:390)
	at org.renjin.eval.Context.evaluate(Context.java:280)
	at org.renjin.eval.Context.evaluate(Context.java:264)
	at org.renjin.script.RenjinScriptEngine.eval(RenjinScriptEngine.java:168)
	at org.renjin.script.RenjinScriptEngine.eval(RenjinScriptEngine.java:127)
	at ErrorRenjin.main(ErrorRenjin.java:18)
```
What is missing for this to work properly?

**Comment by akbertram** [comment]
Fixed in renjin 3.5-beta45
