### ISSUE TITLE
Unable to Install `ctv` package

### ISSUE THREAD

**Issue by ismailsunni** [bedatadriven/renjin#490]
I am trying to create a docker image based on this Renjin docker image https://github.com/nuest/renjin-docker to install some R packages. I want to use `ctv` since I want to install all packages in a view. But, I got this problem:

```
> library("ctv")
Could not resolve org.renjin.bioconductor:ctv
Tried:
* https://repo1.maven.org/maven2/org/renjin/bioconductor/ctv/maven-metadata.xml
* https://nexus.bedatadriven.com/content/groups/public/org/renjin/bioconductor/ctv/maven-metadata.xml
Loading required package: utils
Warning messages:
1: In library("ctv") :
  Symbol 'memory.size' is not defined in package 'org.renjin:utils'
2: In library("ctv") :
  Symbol 'object.size' is not defined in package 'org.renjin:utils'
Loaded org.renjin.cran.ctv version 0.8-5-b1.
```

Any idea how to fix this?

Thanks

**Comment by ismailsunni** [comment]
Ah, I got it working by using `library('org.renjin.cran:ctv')`,

Next question, how to use it? It gives me an error when I tried to use it as below

```
> ctv
ERROR: object 'ctv' not found
org.renjin.eval.EvalException: object 'ctv' not found
	at org.renjin.eval.Context.evaluateSymbol(Context.java:335)
	at org.renjin.eval.Context.evaluate(Context.java:278)
	at org.renjin.eval.Context.evaluate(Context.java:264)
	at org.renjin.eval.Context.evaluateExpressionVector(Context.java:390)
	at org.renjin.eval.Context.evaluate(Context.java:280)
	at org.renjin.eval.Context.evaluate(Context.java:264)
	at org.renjin.repl.JlineRepl.readExpression(JlineRepl.java:243)
	at org.renjin.repl.JlineRepl.run(JlineRepl.java:130)
	at org.renjin.cli.Main.startInteractive(Main.java:126)
	at org.renjin.cli.Main.run(Main.java:111)
	at org.renjin.cli.Main.main(Main.java:78)

```

**Comment by akbertram** [comment]
Renjin's package management works a bit differently (we hope better) than GNU R's, so I'm not sure the ctv package will be usable with Renjin, especially if it relies on the tools package.

The renjin command line tool is meant for testing and development and will always fetch packages on demand from Renjin's repository. It's probably not what you want to deploy into production with a container.

What are you trying to achieve with a docker image? Do you have a script or package that you want to deploy as a web service?

**Comment by ismailsunni** [comment]
Hi @akbertram 
Thanks for the answer.
> The renjin command line tool is meant for testing and development and will always fetch packages on demand from Renjin's repository. It's probably not what you want to deploy into production with a container.
So, it basically not a good idea to make a docker image with pre-installed R packages in renjin?

> What are you trying to achieve with a docker image? Do you have a script or package that you want to deploy as a web service?

I want to make a docker image with geospatial packages installed so that it will be easy for a user to run his/her R code in renjin or for a R packages developer to run a test for his/her package.

Is there an overview information about how much compatibility for R packages on renjin? I see in http://packages.renjin.org/ but I need to go to each package to see its status.

**Comment by perNyfelt** [comment]
Renjin packages are jar files and need to available to Renjin through the classpath. The ClasspathPackageLoader uses the available classpath to find packages and hence you can control which version of the package you want to use by setting up the classpath properly (see [here](http://docs.renjin.org/en/latest/library/execution-context.html#package-loading) for more on this. An easy way to do this is to use maven and just add the dependencies to your packages in there. If you need to ensure that you are working offline then you can force maven to use only what is in your local repo by using the -o switch. As an alternative, you can create  a "fat jar" with Renjin and all the other package dependencies using the shade or assembly plugins. A simple way to use that set-up would be to create a small entry point (with a main) for the script engine that takes an argument for a file containing an R script which it will [execute](http://docs.renjin.org/en/latest/library/evaluating.html) using the script engine.
