### ISSUE TITLE
RJDBC 

### ISSUE THREAD

**Issue by kimmanlui** [bedatadriven/renjin#495]
Hi , 

The R script works find in R environment.

the R script works find as 
```
           conn12 = RJDBC::dbConnect(jdbcDriver, 
                 paste0("jdbc:oracle:thin:@//",dblink12[[1]]), 
                 dblink12[[2]], 
                 dblink12[[3]])
```

But, I got the following error. 
```
Exception in thread "main" org.renjin.eval.EvalException: Namespace org.renjin.cran:RJDBC has no exported symbol named 'dbConnect'
        at org.renjin.primitives.packaging.Namespace.getExport(Namespace.java:101)
        at org.renjin.primitives.special.NamespaceFunction.apply(NamespaceFunction.java:44)
        at org.renjin.sexp.FunctionCall.eval(FunctionCall.java:80)
        at org.renjin.eval.Context.evaluate(Context.java:280)
        at org.renjin.eval.Context.evaluateFunction(Context.java:344)
        at org.renjin.sexp.FunctionCall.eval(FunctionCall.java:77)
        at org.renjin.primitives.special.AssignLeftFunction.assignLeft(AssignLeftFunction.java:58)
        at org.renjin.primitives.special.AssignLeftFunction.apply(AssignLeftFunction.java:42)
        at org.renjin.sexp.FunctionCall.eval(FunctionCall.java:80)
        at org.renjin.sexp.ExpressionVector.eval(ExpressionVector.java:85)
        at org.renjin.eval.Context.evaluate(Context.java:280)
        at org.renjin.script.RenjinScriptEngine.eval(RenjinScriptEngine.java:174)
        at org.renjin.script.RenjinScriptEngine.eval(RenjinScriptEngine.java:169)
        at org.renjin.script.RenjinScriptEngine.eval(RenjinScriptEngine.java:148)
        at com.pccw.mvno.App.main(App.java:16)
```

**Comment by kimmanlui** [comment]
It works in this way.
'''
library(DBI)
library("RJDBC")

jdbcDriver =JDBC("oracle.jdbc.OracleDriver",classPath="/ojdbc-full/ojdbc6.jar")
conn12 = DBI::dbConnect(jdbcDriver, 
                 paste0("jdbc:oracle:thin:@//",dblink12[[1]]), 
                 dblink12[[2]], 
                 dblink12[[3]])
'''
