### ISSUE TITLE
dplyr seem to stop execution

### ISSUE THREAD

**Issue by AbstractAlao** [bedatadriven/renjin#556]
I am trying to run an R script, but it seems to not execute dplyr  filter function. 

```
library(dplyr)
library(stringr)
library(lubridate)
library(rJava)
#library(tidyr)
#library(broom)
#library(ggplot2)
```

```
set.seed(23245, kind = "Mersenne-Twister")
options(dplyr.summarise.inform = FALSE, scipen = 999)
army_required_filter <- portal %>% dplyr::filter(Service == "Army")
```

Here is the Java code

```
RenjinScriptEngine engine = new RenjinScriptEngine();
List<String> scriptContent = RenjinUtils.getMeanScriptContent();
....
List<EvamIndex> data = Arrays.asList(evamIndex, evamIndex2);
ListVector vector = RenjinUtils.convertToListVector(data);

engine.put("portal", vector);

for(String line: scriptContent) {
   logger.info("Evaluating: {}", line);
   engine.eval(line);
}

```

In my vector, i have an attribute called Service

```
StringArrayVector.Builder serviceBranch = new StringArrayVector.Builder();
for (EvamIndex record : data) {
	serviceBranch.add(record.getServiceBranch().getName());

}

ListVector.NamedBuilder myDf = new ListVector.NamedBuilder();
		myDf.setAttribute(Symbols.CLASS, StringVector.valueOf("data.frame"));
		myDf.setAttribute(Symbols.ROW_NAMES, new RowNamesVector(data.size()));
		myDf.add("Installation", installation.build());
		myDf.add("Service", serviceBranch.build());
return myDf.build();
```

**Comment by akbertram** [comment]
Do you get some kind of error or stack trace?

**Comment by AbstractAlao** [comment]
I don't get an error.  It seems like it gets stuck in a loop or something because execution doesn't continue, but my unit test is still running.  If i remove the library(dplyr) line then i do get this error
`
org.renjin.eval.EvalException: object Service not found
`

I saw that it might be calling stats::filter instead of dplyr::filter, so i explicitly set dplyr



Here are my pom.xml entries 

```
<dependency>
			<groupId>org.renjin</groupId>
			<artifactId>renjin-script-engine</artifactId>
			<version>RELEASE</version>
		</dependency>
		<dependency>
			<groupId>org.renjin.cran</groupId>
			<artifactId>dplyr</artifactId>
			<version>0.7.4-b73</version>
		</dependency>
		<dependency>
			<groupId>org.renjin.cran</groupId>
			<artifactId>assertthat</artifactId>
			<version>0.2.1-b10</version>
		</dependency>
		<dependency>
			<groupId>org.renjin.cran</groupId>
			<artifactId>tidyselect</artifactId>
			<version>0.2.5-b3</version>
		</dependency>
		<dependency>
			<groupId>org.renjin.cran</groupId>
			<artifactId>tidyr</artifactId>
			<version>0.8.0-b1</version>
		</dependency>
		<dependency>
			<groupId>org.renjin.cran</groupId>
			<artifactId>stringr</artifactId>
			<version>1.4.0-b6</version>
		</dependency>
		<dependency>
			<groupId>org.renjin.cran</groupId>
			<artifactId>lubridate</artifactId>
			<version>1.7.4-b4</version>
		</dependency>
		<dependency>
			<groupId>org.renjin.cran</groupId>
			<artifactId>broom</artifactId>
			<version>0.4.4-b1</version>
		</dependency>
		<dependency>
			<groupId>org.renjin.cran</groupId>
			<artifactId>ggplot2</artifactId>
			<version>3.2.0-b8</version>
		</dependency>
```

**Comment by perNyfelt** [comment]
I have never been able to do anything useful with dplyr in renjin. If you look at the [build info](https://packages.renjin.org/package/org.renjin.cran/dplyr) almost all tests fails.

**Comment by AbstractAlao** [comment]
Ahh, ok .  on a side note when I try to load library(broom) , I get this stack trace. 

```
org.renjin.eval.EvalException: Exception initializing compiled GNU R library class org.renjin.cran.reshape2.reshape2
	at org.renjin.primitives.packaging.DllInfo.initialize(DllInfo.java:141)
	at org.renjin.primitives.packaging.Namespace.loadDynamicLibrary(Namespace.java:383)
	at org.renjin.primitives.packaging.Namespace.importDynamicLibrary(Namespace.java:296)
	at org.renjin.primitives.packaging.Namespace.initImports(Namespace.java:274)
	at org.renjin.primitives.packaging.NamespaceRegistry.load(NamespaceRegistry.java:175)
	at org.renjin.primitives.packaging.NamespaceRegistry.getNamespace(NamespaceRegistry.java:143)
	at org.renjin.primitives.packaging.NamespaceRegistry.getNamespace(NamespaceRegistry.java:114)
	at org.renjin.primitives.packaging.Namespace.initImports(Namespace.java:211)
	at org.renjin.primitives.packaging.NamespaceRegistry.load(NamespaceRegistry.java:175)
	at org.renjin.primitives.packaging.NamespaceRegistry.getNamespace(NamespaceRegistry.java:143)
	at org.renjin.primitives.packaging.NamespaceRegistry.getNamespace(NamespaceRegistry.java:114)
	at org.renjin.primitives.packaging.Packages.library(Packages.java:39)
	at org.renjin.primitives.R$primitive$library.doApply(R$primitive$library.java:68)
	at org.renjin.primitives.R$primitive$library.applyPromised(R$primitive$library.java:33)
	at org.renjin.sexp.BuiltinFunction.apply(BuiltinFunction.java:100)
	at org.renjin.primitives.special.InternalFunction.apply(InternalFunction.java:46)
	at org.renjin.sexp.FunctionCall.eval(FunctionCall.java:80)
	at org.renjin.primitives.special.BeginFunction.apply(BeginFunction.java:39)
	at org.renjin.sexp.FunctionCall.eval(FunctionCall.java:80)
	at org.renjin.sexp.Closure.applyPromised(Closure.java:200)
	at org.renjin.sexp.Closure.apply(Closure.java:133)
	at org.renjin.sexp.FunctionCall.eval(FunctionCall.java:80)
	at org.renjin.sexp.ExpressionVector.eval(ExpressionVector.java:85)
	at org.renjin.eval.Context.evaluate(Context.java:280)
	at org.renjin.script.RenjinScriptEngine.eval(RenjinScriptEngine.java:174)
	at org.renjin.script.RenjinScriptEngine.eval(RenjinScriptEngine.java:133)
	at org.fvap.model.evam.RenjinTest.runRenjin(RenjinTest.java:76)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.junit.runners.model.FrameworkMethod$1.runReflectiveCall(FrameworkMethod.java:59)
	at org.junit.internal.runners.model.ReflectiveCallable.run(ReflectiveCallable.java:12)
	at org.junit.runners.model.FrameworkMethod.invokeExplosively(FrameworkMethod.java:56)
	at org.junit.internal.runners.statements.InvokeMethod.evaluate(InvokeMethod.java:17)
	at org.junit.internal.runners.statements.RunBefores.evaluate(RunBefores.java:26)
	at org.junit.runners.ParentRunner$3.evaluate(ParentRunner.java:306)
	at org.junit.runners.BlockJUnit4ClassRunner$1.evaluate(BlockJUnit4ClassRunner.java:100)
	at org.junit.runners.ParentRunner.runLeaf(ParentRunner.java:366)
	at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:103)
	at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:63)
	at org.junit.runners.ParentRunner$4.run(ParentRunner.java:331)
	at org.junit.runners.ParentRunner$1.schedule(ParentRunner.java:79)
	at org.junit.runners.ParentRunner.runChildren(ParentRunner.java:329)
	at org.junit.runners.ParentRunner.access$100(ParentRunner.java:66)
	at org.junit.runners.ParentRunner$2.evaluate(ParentRunner.java:293)
	at org.junit.internal.runners.statements.RunBefores.evaluate(RunBefores.java:26)
	at org.junit.runners.ParentRunner$3.evaluate(ParentRunner.java:306)
	at org.junit.runners.ParentRunner.run(ParentRunner.java:413)
	at org.eclipse.jdt.internal.junit4.runner.JUnit4TestReference.run(JUnit4TestReference.java:93)
	at org.eclipse.jdt.internal.junit.runner.TestExecution.run(TestExecution.java:40)
	at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.runTests(RemoteTestRunner.java:529)
	at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.runTests(RemoteTestRunner.java:756)
	at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.run(RemoteTestRunner.java:452)
	at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.main(RemoteTestRunner.java:210)
Caused by: java.lang.VerifyError: Bad local variable type
Exception Details:
  Location:
    org/renjin/cran/reshape2/melt__._Z4rep_P7SEXPRECi(Lorg/renjin/sexp/SEXP;I)Lorg/renjin/sexp/SEXP; @1014: aload
  Reason:
    Type top (current frame, locals[133]) is not assignable to reference type
  Current Frame:
    bci: @1014
    flags: { }
    locals: { 'org/renjin/sexp/SEXP', integer, top, top, top, top, top, top, top, top, top, top, top, top, top, top, top, top, top, top, top, top, top, top, top, top, top, top, top, top, top, top, top, top, top, top, top, top, top, top, top, top, top, top, top, top, top, top, integer, 'org/renjin/gcc/runtime/MixedPtr', integer, top, 'org/renjin/gcc/runtime/MixedPtr', top, 'org/renjin/gcc/runtime/MixedPtr', top, 'org/renjin/gcc/runtime/MixedPtr', top, integer, 'org/renjin/gcc/runtime/MixedPtr', integer, top, 'org/renjin/gcc/runtime/MixedPtr', top, 'org/renjin/gcc/runtime/MixedPtr', integer, integer, 'org/renjin/gcc/runtime/MixedPtr', 'org/renjin/gcc/runtime/MixedPtr' }
    stack: { }
  Bytecode:
    0x0000000: 07b8 007f 3a31 07b8 007f 3a34 07b8 007f
    0x0000010: 3a36 07b8 007f 3a38 07b8 007f 3a3b 07b8
    0x0000020: 007f 3a3e 07b8 007f 3a40 04b8 007f 3a43
    0x0000030: 07b8 007f 3a44 0336 3003 3632 0336 3a03
    0x0000040: 363c 0336 422a b807 7636 4215 421b 6836
    0x0000050: 412a b802 95ab 0000 0000 037f 0000 0007
    0x0000060: 0000 000a 0000 01a7 0000 000d 0000 0043
    0x0000070: 0000 000e 0000 00ba 0000 000f 0000 021e
    0x0000080: 0000 0010 0000 0133 0000 0013 0000 030a
    0x0000090: 0000 0018 0000 0297 100d 1541 b802 1c3a
    0x00000a0: 9319 4019 93b8 00b5 0336 3fa7 0041 1542
    0x00000b0: 0768 3690 2ab8 031a 3a8e 1940 b800 b9b8
    0x00000c0: 031a 3a8b 153f 1542 6807 6836 8819 8b3a
    0x00000d0: 8603 1588 6036 8719 8615 87b9 002a 0200
    0x00000e0: 198e 1590 b901 5d03 0084 3f01 153f 1ba1
    0x00000f0: 000a a700 0303 a700 0404 9aff b4a7 0003
    0x0000100: 1940 b800 b93a 8519 40b8 00f0 a702 ea10
    0x0000110: 0e15 41b8 021c 3a84 193e 1984 b800 b503
    0x0000120: 363d a700 4315 4210 0868 3681 2ab8 077a
    0x0000130: 3a7f 193e b800 b9b8 077a 3a7c 153d 1542
    0x0000140: 6810 0868 3679 197c 3a77 0315 7960 3678
    0x0000150: 1977 1578 b900 2a02 0019 7f15 81b9 015d
    0x0000160: 0300 843d 0115 3d1b a100 0aa7 0003 03a7
    0x0000170: 0004 049a ffb2 a700 0319 3eb8 00b9 3a85
    0x0000180: 193e b800 f0a7 0271 0336 3c10 1015 41b8
    0x0000190: 021c 3a76 193b 1976 b800 b503 363a a700
    0x00001a0: 3b03 3639 a700 1d2a 1539 b800 e33a 7319
    0x00001b0: 3bb8 00b9 153c 1973 b806 8284 3c01 8439
    0x00001c0: 0115 3915 42a1 000a a700 0303 a700 0404
    0x00001d0: 9aff d7a7 0003 843a 0115 3a1b a100 0aa7
    0x00001e0: 0003 03a7 0004 049a ffba a700 0319 3bb8
    0x00001f0: 00b9 3a85 193b b800 f0a7 01fd 100a 1541
    0x0000200: b802 1c3a 7119 3819 71b8 00b5 0336 37a7
    0x0000210: 0041 1542 0768 366e 2ab8 0785 3a6c 1938
    0x0000220: b800 b9b8 0785 3a69 1537 1542 6807 6836
    0x0000230: 6619 693a 6403 1566 6036 6519 6415 65b9
    0x0000240: 002a 0200 196c 156e b901 5d03 0084 3701
    0x0000250: 1537 1ba1 000a a700 0303 a700 0404 9aff
    0x0000260: b4a7 0003 1938 b800 b93a 8519 38b8 00f0
    0x0000270: a701 8610 0f15 41b8 021c 3a63 1936 1963
    0x0000280: b800 b503 3635 a700 4315 4210 1068 3660
    0x0000290: 2ab8 0788 3a5e 1936 b800 b9b8 0788 3a5b
    0x00002a0: 1535 1542 6810 1068 3658 195b 3a56 0315
    0x00002b0: 5860 3657 1956 1557 b900 2a02 0019 5e15
    0x00002c0: 60b9 015d 0300 8435 0115 351b a100 0aa7
    0x00002d0: 0003 03a7 0004 049a ffb2 a700 0319 36b8
    0x00002e0: 00b9 3a85 1936 b800 f0a7 010d 1018 1541
    0x00002f0: b802 1c3a 5519 3419 55b8 00b5 0336 33a7
    0x0000300: 003d 1542 3653 2ab8 078b 3a51 1934 b800
    0x0000310: b9b8 078b 3a4e 1533 1542 6836 4c19 4e3a
    0x0000320: 4a03 154c 6036 4b19 4a15 4bb9 002a 0200
    0x0000330: 1951 1553 b901 5d03 0084 3301 1533 1ba1
    0x0000340: 000a a700 0303 a700 0404 9aff b8a7 0003
    0x0000350: 1934 b800 b93a 8519 34b8 00f0 a700 9a03
    0x0000360: 3632 1013 1541 b802 1c3a 4919 3119 49b8
    0x0000370: 00b5 0336 30a7 003c 0336 2fa7 001e 2a15
    0x0000380: 2fb8 0648 3a46 1931 b800 b915 3219 46b8
    0x0000390: 0636 5784 3201 842f 0115 2f15 42a1 000a
    0x00003a0: a700 0303 a700 0404 9aff d6a7 0003 8430
    0x00003b0: 0115 301b a100 0aa7 0003 03a7 0004 049a
    0x00003c0: ffb9 a700 0319 31b8 00b9 3a85 1931 b800
    0x00003d0: f0a7 0025 1943 b800 a219 44bb 0087 5913
    0x00003e0: 078f b600 8f03 b700 92c0 0012 1943 b800
    0x00003f0: a819 44b8 00ab 1985 b000 0000 00bf 0000
    0x0000400: 0000 bf00 0000 00bf 0000 0000 bf00 0000
    0x0000410: 00bf 0000 0000 bf00 0000 00bf 0000 0000
    0x0000420: bf00 0000 00bf 00bf                    
  Stackmap Table:
    full_frame(@152,{Object[#260],Integer,Top,Top,Top,Top,Top,Top,Top,Top,Top,Top,Top,Top,Top,Top,Top,Top,Top,Top,Top,Top,Top,Top,Top,Top,Top,Top,Top,Top,Top,Top,Top,Top,Top,Top,Top,Top,Top,Top,Top,Top,Top,Top,Top,Top,Top,Top,Integer,Object[#123],Integer,Top,Object[#123],Top,Object[#123],Top,Object[#123],Top,Integer,Object[#123],Integer,Top,Object[#123],Top,Object[#123],Integer,Integer,Object[#123],Object[#123]},{})
    full_frame(@174,{Object[#260],Integer,Top,Top,Top,Top,Top,Top,Top,Top,Top,Top,Top,Top,Top,Top,Top,Top,Top,Top,Top,Top,Top,Top,Top,Top,Top,Top,Top,Top,Top,Top,Top,Top,Top,Top,Top,Top,Top,Top,Top,Top,Top,Top,Top,Top,Top,Top,Integer,Object[#123],Integer,Top,Object[#123],Top,Object[#123],Top,Object[#123],Top,Integer,Object[#123],Integer,Top,Object[#123],Integer,Object[#123],Integer,Integer,Object[#123],Object[#123],Top,Top,Top,Top,Top,Top,Top,Top,Top,Top,Top,Top,Top,Top,Top,Top,Top,Top,Top,Top,Top,Top,Top,Top,Top,Top,Top,Top,Top,Top,Top,Top,Top,Top,Top,Top,Top,Top,Top,Top,Top,Top,Top,Top,Top,Top,Top,Top,Top,Top,Top,Top,Top,Top,Top,Top,Top,Top,Top,Top,Top,Top,Top,Top,Top,Top,Top,Top,Top,Top,Top,Top,Top,Top,Top,Top,Top,Top,Object[#260]},{})
    same_frame(@236)
    same_frame(@245)
    same_frame(@249)
    same_locals_1_stack_item_frame(@250,Integer)
    same_frame(@256)
    full_frame(@271,{Object[#260],Integer,Top,Top,Top,Top,Top,Top,Top,Top,Top,Top,Top,Top,Top,Top,Top,Top,Top,Top,Top,Top,Top,Top,Top,Top,Top,Top,Top,Top,Top,Top,Top,Top,Top,Top,Top,Top,Top,Top,Top,Top,Top,Top,Top,Top,Top,Top,Integer,Object[#123],Integer,Top,Object[#123],Top,Object[#123],Top,Object[#123],Top,Integer,Object[#123],Integer,Top,Object[#123],Top,Object[#123],Integer,Integer,Object[#123],Object[#123]},{})
    full_frame(@293,{Object[#260],Integer,Top,Top,Top,Top,Top,Top,Top,Top,Top,Top,Top,Top,Top,Top,Top,Top,Top,Top,Top,Top,Top,Top,Top,Top,Top,Top,Top,Top,Top,Top,Top,Top,Top,Top,Top,Top,Top,Top,Top,Top,Top,Top,Top,Top,Top,Top,Integer,Object[#123],Integer,Top,Object[#123],Top,Object[#123],Top,Object[#123],Top,Integer,Object[#123],Integer,Integer,Object[#123],Top,Object[#123],Integer,Integer,Object[#123],Object[#123],Top,Top,Top,Top,Top,Top,Top,Top,Top,Top,Top,Top,Top,Top,Top,Top,Top,Top,Top,Top,Top,Top,Top,Top,Top,Top,Top,Top,Top,Top,Top,Top,Top,Top,Top,Top,Top,Top,Top,Top,Top,Top,Top,Top,Top,Top,Top,Top,Top,Top,Top,Top,Top,Top,Top,Top,Top,Top,Top,Top,Top,Top,Top,Object[#260]},{})
    same_frame(@357)
    same_frame(@366)
    same_frame(@370)
    same_locals_1_stack_item_frame(@371,Integer)
    same_frame(@377)
    full_frame(@392,{Object[#260],Integer,Top,Top,Top,Top,Top,Top,Top,Top,Top,Top,Top,Top,Top,Top,Top,Top,Top,Top,Top,Top,Top,Top,Top,Top,Top,Top,Top,Top,Top,Top,Top,Top,Top,Top,Top,Top,Top,Top,Top,Top,Top,Top,Top,Top,Top,Top,Integer,Object[#123],Integer,Top,Object[#123],Top,Object[#123],Top,Object[#123],Top,Integer,Object[#123],Integer,Top,Object[#123],Top,Object[#123],Integer,Integer,Object[#123],Object[#123]},{})
    full_frame(@417,{Object[#260],Integer,Top,Top,Top,Top,Top,Top,Top,Top,Top,Top,Top,Top,Top,Top,Top,Top,Top,Top,Top,Top,Top,Top,Top,Top,Top,Top,Top,Top,Top,Top,Top,Top,Top,Top,Top,Top,Top,Top,Top,Top,Top,Top,Top,Top,Top,Top,Integer,Object[#123],Integer,Top,Object[#123],Top,Object[#123],Top,Object[#123],Top,Integer,Object[#123],Integer,Top,Object[#123],Top,Object[#123],Integer,Integer,Object[#123],Object[#123],Top,Top,Top,Top,Top,Top,Top,Top,Top,Top,Top,Top,Top,Top,Top,Top,Top,Top,Top,Top,Top,Top,Top,Top,Top,Top,Top,Top,Top,Top,Top,Top,Top,Top,Top,Top,Top,Top,Top,Top,Top,Top,Top,Top,Top,Top,Top,Top,Top,Object[#260]},{})
    full_frame(@423,{Object[#260],Integer,Top,Top,Top,Top,Top,Top,Top,Top,Top,Top,Top,Top,Top,Top,Top,Top,Top,Top,Top,Top,Top,Top,Top,Top,Top,Top,Top,Top,Top,Top,Top,Top,Top,Top,Top,Top,Top,Top,Top,Top,Top,Top,Top,Top,Top,Top,Integer,Object[#123],Integer,Top,Object[#123],Top,Object[#123],Top,Object[#123],Integer,Integer,Object[#123],Integer,Top,Object[#123],Top,Object[#123],Integer,Integer,Object[#123],Object[#123],Top,Top,Top,Top,Top,Top,Top,Top,Top,Top,Top,Top,Top,Top,Top,Top,Top,Top,Top,Top,Top,Top,Top,Top,Top,Top,Top,Top,Top,Top,Top,Top,Top,Top,Top,Top,Top,Top,Top,Top,Top,Top,Top,Top,Top,Top,Top,Top,Top,Object[#260]},{})
    same_frame(@449)
    same_frame(@459)
    same_frame(@463)
    same_locals_1_stack_item_frame(@464,Integer)
    same_frame(@470)
    full_frame(@473,{Object[#260],Integer,Top,Top,Top,Top,Top,Top,Top,Top,Top,Top,Top,Top,Top,Top,Top,Top,Top,Top,Top,Top,Top,Top,Top,Top,Top,Top,Top,Top,Top,Top,Top,Top,Top,Top,Top,Top,Top,Top,Top,Top,Top,Top,Top,Top,Top,Top,Integer,Object[#123],Integer,Top,Object[#123],Top,Object[#123],Top,Object[#123],Top,Integer,Object[#123],Integer,Top,Object[#123],Top,Object[#123],Integer,Integer,Object[#123],Object[#123],Top,Top,Top,Top,Top,Top,Top,Top,Top,Top,Top,Top,Top,Top,Top,Top,Top,Top,Top,Top,Top,Top,Top,Top,Top,Top,Top,Top,Top,Top,Top,Top,Top,Top,Top,Top,Top,Top,Top,Top,Top,Top,Top,Top,Top,Top,Top,Top,Top,Object[#260]},{})
    same_frame(@482)
    same_frame(@486)
    same_locals_1_stack_item_frame(@487,Integer)
    same_frame(@493)
    full_frame(@508,{Object[#260],Integer,Top,Top,Top,Top,Top,Top,Top,Top,Top,Top,Top,Top,Top,Top,Top,Top,Top,Top,Top,Top,Top,Top,Top,Top,Top,Top,Top,Top,Top,Top,Top,Top,Top,Top,Top,Top,Top,Top,Top,Top,Top,Top,Top,Top,Top,Top,Integer,Object[#123],Integer,Top,Object[#123],Top,Object[#123],Top,Object[#123],Top,Integer,Object[#123],Integer,Top,Object[#123],Top,Object[#123],Integer,Integer,Object[#123],Object[#123]},{})
    full_frame(@530,{Object[#260],Integer,Top,Top,Top,Top,Top,Top,Top,Top,Top,Top,Top,Top,Top,Top,Top,Top,Top,Top,Top,Top,Top,Top,Top,Top,Top,Top,Top,Top,Top,Top,Top,Top,Top,Top,Top,Top,Top,Top,Top,Top,Top,Top,Top,Top,Top,Top,Integer,Object[#123],Integer,Top,Object[#123],Top,Object[#123],Integer,Object[#123],Top,Integer,Object[#123],Integer,Top,Object[#123],Top,Object[#123],Integer,Integer,Object[#123],Object[#123],Top,Top,Top,Top,Top,Top,Top,Top,Top,Top,Top,Top,Top,Top,Top,Top,Top,Top,Top,Top,Top,Top,Top,Top,Top,Top,Top,Top,Top,Top,Top,Top,Top,Top,Top,Top,Top,Top,Top,Top,Top,Top,Top,Top,Object[#260]},{})
    same_frame(@592)
    same_frame(@601)
    same_frame(@605)
    same_locals_1_stack_item_frame(@606,Integer)
    same_frame(@612)
    full_frame(@627,{Object[#260],Integer,Top,Top,Top,Top,Top,Top,Top,Top,Top,Top,Top,Top,Top,Top,Top,Top,Top,Top,Top,Top,Top,Top,Top,Top,Top,Top,Top,Top,Top,Top,Top,Top,Top,Top,Top,Top,Top,Top,Top,Top,Top,Top,Top,Top,Top,Top,Integer,Object[#123],Integer,Top,Object[#123],Top,Object[#123],Top,Object[#123],Top,Integer,Object[#123],Integer,Top,Object[#123],Top,Object[#123],Integer,Integer,Object[#123],Object[#123]},{})
    full_frame(@649,{Object[#260],Integer,Top,Top,Top,Top,Top,Top,Top,Top,Top,Top,Top,Top,Top,Top,Top,Top,Top,Top,Top,Top,Top,Top,Top,Top,Top,Top,Top,Top,Top,Top,Top,Top,Top,Top,Top,Top,Top,Top,Top,Top,Top,Top,Top,Top,Top,Top,Integer,Object[#123],Integer,Top,Object[#123],Integer,Object[#123],Top,Object[#123],Top,Integer,Object[#123],Integer,Top,Object[#123],Top,Object[#123],Integer,Integer,Object[#123],Object[#123],Top,Top,Top,Top,Top,Top,Top,Top,Top,Top,Top,Top,Top,Top,Top,Top,Top,Top,Top,Top,Top,Top,Top,Top,Top,Top,Top,Top,Top,Top,Object[#260]},{})
    same_frame(@713)
    same_frame(@722)
    same_frame(@726)
    same_locals_1_stack_item_frame(@727,Integer)
    same_frame(@733)
    full_frame(@748,{Object[#260],Integer,Top,Top,Top,Top,Top,Top,Top,Top,Top,Top,Top,Top,Top,Top,Top,Top,Top,Top,Top,Top,Top,Top,Top,Top,Top,Top,Top,Top,Top,Top,Top,Top,Top,Top,Top,Top,Top,Top,Top,Top,Top,Top,Top,Top,Top,Top,Integer,Object[#123],Integer,Top,Object[#123],Top,Object[#123],Top,Object[#123],Top,Integer,Object[#123],Integer,Top,Object[#123],Top,Object[#123],Integer,Integer,Object[#123],Object[#123]},{})
    full_frame(@770,{Object[#260],Integer,Top,Top,Top,Top,Top,Top,Top,Top,Top,Top,Top,Top,Top,Top,Top,Top,Top,Top,Top,Top,Top,Top,Top,Top,Top,Top,Top,Top,Top,Top,Top,Top,Top,Top,Top,Top,Top,Top,Top,Top,Top,Top,Top,Top,Top,Top,Integer,Object[#123],Integer,Integer,Object[#123],Top,Object[#123],Top,Object[#123],Top,Integer,Object[#123],Integer,Top,Object[#123],Top,Object[#123],Integer,Integer,Object[#123],Object[#123],Top,Top,Top,Top,Top,Top,Top,Top,Top,Top,Top,Top,Top,Top,Top,Top,Object[#260]},{})
    same_frame(@828)
    same_frame(@837)
    same_frame(@841)
    same_locals_1_stack_item_frame(@842,Integer)
    same_frame(@848)
    full_frame(@863,{Object[#260],Integer,Top,Top,Top,Top,Top,Top,Top,Top,Top,Top,Top,Top,Top,Top,Top,Top,Top,Top,Top,Top,Top,Top,Top,Top,Top,Top,Top,Top,Top,Top,Top,Top,Top,Top,Top,Top,Top,Top,Top,Top,Top,Top,Top,Top,Top,Top,Integer,Object[#123],Integer,Top,Object[#123],Top,Object[#123],Top,Object[#123],Top,Integer,Object[#123],Integer,Top,Object[#123],Top,Object[#123],Integer,Integer,Object[#123],Object[#123]},{})
    full_frame(@888,{Object[#260],Integer,Top,Top,Top,Top,Top,Top,Top,Top,Top,Top,Top,Top,Top,Top,Top,Top,Top,Top,Top,Top,Top,Top,Top,Top,Top,Top,Top,Top,Top,Top,Top,Top,Top,Top,Top,Top,Top,Top,Top,Top,Top,Top,Top,Top,Top,Top,Integer,Object[#123],Integer,Top,Object[#123],Top,Object[#123],Top,Object[#123],Top,Integer,Object[#123],Integer,Top,Object[#123],Top,Object[#123],Integer,Integer,Object[#123],Object[#123],Top,Top,Top,Top,Object[#260]},{})
    full_frame(@894,{Object[#260],Integer,Top,Top,Top,Top,Top,Top,Top,Top,Top,Top,Top,Top,Top,Top,Top,Top,Top,Top,Top,Top,Top,Top,Top,Top,Top,Top,Top,Top,Top,Top,Top,Top,Top,Top,Top,Top,Top,Top,Top,Top,Top,Top,Top,Top,Top,Integer,Integer,Object[#123],Integer,Top,Object[#123],Top,Object[#123],Top,Object[#123],Top,Integer,Object[#123],Integer,Top,Object[#123],Top,Object[#123],Integer,Integer,Object[#123],Object[#123],Top,Top,Top,Top,Object[#260]},{})
    same_frame(@921)
    same_frame(@931)
    same_frame(@935)
    same_locals_1_stack_item_frame(@936,Integer)
    same_frame(@942)
    full_frame(@945,{Object[#260],Integer,Top,Top,Top,Top,Top,Top,Top,Top,Top,Top,Top,Top,Top,Top,Top,Top,Top,Top,Top,Top,Top,Top,Top,Top,Top,Top,Top,Top,Top,Top,Top,Top,Top,Top,Top,Top,Top,Top,Top,Top,Top,Top,Top,Top,Top,Top,Integer,Object[#123],Integer,Top,Object[#123],Top,Object[#123],Top,Object[#123],Top,Integer,Object[#123],Integer,Top,Object[#123],Top,Object[#123],Integer,Integer,Object[#123],Object[#123],Top,Top,Top,Top,Object[#260]},{})
    same_frame(@954)
    same_frame(@958)
    same_locals_1_stack_item_frame(@959,Integer)
    same_frame(@965)
    full_frame(@980,{Object[#260],Integer,Top,Top,Top,Top,Top,Top,Top,Top,Top,Top,Top,Top,Top,Top,Top,Top,Top,Top,Top,Top,Top,Top,Top,Top,Top,Top,Top,Top,Top,Top,Top,Top,Top,Top,Top,Top,Top,Top,Top,Top,Top,Top,Top,Top,Top,Top,Integer,Object[#123],Integer,Top,Object[#123],Top,Object[#123],Top,Object[#123],Top,Integer,Object[#123],Integer,Top,Object[#123],Top,Object[#123],Integer,Integer,Object[#123],Object[#123]},{})
    same_frame(@1014)
    full_frame(@1017,{},{Object[#58]})
    same_locals_1_stack_item_frame(@1022,Object[#58])
    same_locals_1_stack_item_frame(@1027,Object[#58])
    same_locals_1_stack_item_frame(@1032,Object[#58])
    same_locals_1_stack_item_frame(@1037,Object[#58])
    same_locals_1_stack_item_frame(@1042,Object[#58])
    same_locals_1_stack_item_frame(@1047,Object[#58])
    same_locals_1_stack_item_frame(@1052,Object[#58])
    same_locals_1_stack_item_frame(@1057,Object[#58])
    same_locals_1_stack_item_frame(@1062,Object[#58])

	at org.renjin.cran.reshape2.RcppExports__._ZTVSt9exception$$clinit(RcppExports.cpp)
	at org.renjin.cran.reshape2.RcppExports__.<clinit>(RcppExports.cpp)
	at org.renjin.cran.reshape2.reshape2.R_init_reshape2(Unknown Source)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.renjin.primitives.packaging.DllInfo.initialize(DllInfo.java:137)
	... 54 more
```
