### ISSUE TITLE
ClassCastException when obtaining confidence intervals for a linear model with more than 43 coefficients

### ISSUE THREAD

**Issue by cwlaird3** [bedatadriven/renjin#96]
I get a ClassCastException ( org.renjin.sexp.Null cannot be cast to org.renjin.sexp.StringVector) when obtaining confidence intervals for a linear model with more than 43 coefficients.

I'm seeing this in 0.7.0-RC7 and 0.7.0-RC8-SNAPSHOT.

I will submit a unit test to reproduce.

Stack trace:
java.lang.ClassCastException: org.renjin.sexp.Null cannot be cast to org.renjin.sexp.StringVector
	at org.renjin.primitives.combine.view.CombinedStringVector.combine(CombinedStringVector.java:28)
	at org.renjin.primitives.combine.LazyBuilder.buildAttributes(LazyBuilder.java:108)
	at org.renjin.primitives.combine.LazyBuilder.build(LazyBuilder.java:95)
	at org.renjin.primitives.combine.Combiner.build(Combiner.java:75)
	at org.renjin.primitives.combine.Combine.c(Combine.java:61)
	at org.renjin.primitives.R$primitive$c.apply(R$primitive$c.java:54)
	at org.renjin.eval.Context.evaluateCall(Context.java:261)
	at org.renjin.eval.Context.evaluate(Context.java:193)
	at org.renjin.invoke.codegen.ArgumentIterator.evalNext(ArgumentIterator.java:61)
	at org.renjin.primitives.R$primitive$$bracket.apply(R$primitive$$bracket.java:35)
	at org.renjin.eval.Context.evaluateCall(Context.java:261)
	at org.renjin.eval.Context.evaluate(Context.java:193)
	at org.renjin.primitives.special.AssignLeftFunction.assignLeft(AssignLeftFunction.java:60)
	at org.renjin.primitives.special.AssignLeftFunction.apply(AssignLeftFunction.java:44)
	at org.renjin.eval.Context.evaluateCall(Context.java:261)
	at org.renjin.eval.Context.evaluate(Context.java:193)
	at org.renjin.primitives.special.BeginFunction.apply(BeginFunction.java:46)
	at org.renjin.eval.Context.evaluateCall(Context.java:261)
	at org.renjin.eval.Context.evaluate(Context.java:193)
	at org.renjin.primitives.special.IfFunction.apply(IfFunction.java:46)
	at org.renjin.eval.Context.evaluateCall(Context.java:261)
	at org.renjin.eval.Context.evaluate(Context.java:193)
	at org.renjin.primitives.special.BeginFunction.apply(BeginFunction.java:46)
	at org.renjin.eval.Context.evaluateCall(Context.java:261)
	at org.renjin.eval.Context.evaluate(Context.java:193)
	at org.renjin.eval.Context.evaluate(Context.java:161)
	at org.renjin.sexp.Closure.doApply(Closure.java:108)
	at org.renjin.eval.ClosureDispatcher.apply(ClosureDispatcher.java:80)
	at org.renjin.eval.ClosureDispatcher.applyClosure(ClosureDispatcher.java:65)
	at org.renjin.sexp.Closure.apply(Closure.java:82)
	at org.renjin.eval.Context.evaluateCall(Context.java:261)
	at org.renjin.eval.Context.evaluate(Context.java:193)
	at org.renjin.invoke.codegen.ArgumentIterator.evalNext(ArgumentIterator.java:61)
	at org.renjin.primitives.R$primitive$$times.apply(R$primitive$$times.java:35)
	at org.renjin.eval.Context.evaluateCall(Context.java:261)
	at org.renjin.eval.Context.evaluate(Context.java:193)
	at org.renjin.invoke.codegen.ArgumentIterator.evalNext(ArgumentIterator.java:61)
	at org.renjin.primitives.R$primitive$sqrt.apply(R$primitive$sqrt.java:31)
	at org.renjin.eval.Context.evaluateCall(Context.java:261)
	at org.renjin.eval.Context.evaluate(Context.java:193)
	at org.renjin.primitives.special.AssignLeftFunction.assignLeft(AssignLeftFunction.java:60)
	at org.renjin.primitives.special.AssignLeftFunction.apply(AssignLeftFunction.java:44)
	at org.renjin.eval.Context.evaluateCall(Context.java:261)
	at org.renjin.eval.Context.evaluate(Context.java:193)
	at org.renjin.primitives.special.BeginFunction.apply(BeginFunction.java:46)
	at org.renjin.eval.Context.evaluateCall(Context.java:261)
	at org.renjin.eval.Context.evaluate(Context.java:193)
	at org.renjin.eval.Context.evaluate(Context.java:161)
	at org.renjin.sexp.Closure.doApply(Closure.java:108)
	at org.renjin.eval.ClosureDispatcher.apply(ClosureDispatcher.java:80)
	at org.renjin.eval.ClosureDispatcher.applyClosure(ClosureDispatcher.java:65)
	at org.renjin.sexp.Closure.apply(Closure.java:82)
	at org.renjin.eval.Context.evaluateCall(Context.java:261)
	at org.renjin.eval.Context.evaluate(Context.java:193)
	at org.renjin.primitives.special.AssignLeftFunction.assignLeft(AssignLeftFunction.java:60)
	at org.renjin.primitives.special.AssignLeftFunction.apply(AssignLeftFunction.java:44)
	at org.renjin.eval.Context.evaluateCall(Context.java:261)
	at org.renjin.eval.Context.evaluate(Context.java:193)
	at org.renjin.primitives.special.BeginFunction.apply(BeginFunction.java:46)
	at org.renjin.eval.Context.evaluateCall(Context.java:261)
	at org.renjin.eval.Context.evaluate(Context.java:193)
	at org.renjin.eval.Calls.applyClosure(Calls.java:71)
	at org.renjin.primitives.S3$GenericMethod.doApply(S3.java:584)
	at org.renjin.primitives.S3$GenericMethod.apply(S3.java:571)
	at org.renjin.primitives.S3.UseMethod(S3.java:43)
	at org.renjin.primitives.S3.UseMethod(S3.java:35)
	at org.renjin.primitives.R$primitive$UseMethod.doApply(R$primitive$UseMethod.java:77)
	at org.renjin.primitives.R$primitive$UseMethod.apply(R$primitive$UseMethod.java:31)
	at org.renjin.eval.Context.evaluateCall(Context.java:261)
	at org.renjin.eval.Context.evaluate(Context.java:193)
	at org.renjin.eval.Context.evaluate(Context.java:161)
	at org.renjin.sexp.Closure.doApply(Closure.java:108)
	at org.renjin.eval.ClosureDispatcher.apply(ClosureDispatcher.java:80)
	at org.renjin.eval.ClosureDispatcher.applyClosure(ClosureDispatcher.java:65)
	at org.renjin.sexp.Closure.apply(Closure.java:82)
	at org.renjin.eval.Context.evaluateCall(Context.java:261)
	at org.renjin.eval.Context.evaluate(Context.java:193)
	at org.renjin.sexp.Promise.doEval(Promise.java:90)
	at org.renjin.sexp.Promise.force(Promise.java:83)
	at org.renjin.eval.Context.evaluate(Context.java:195)
	at org.renjin.eval.Context.evaluateSymbol(Context.java:239)
	at org.renjin.eval.Context.evaluate(Context.java:189)
	at org.renjin.invoke.codegen.ArgumentIterator.evalNext(ArgumentIterator.java:61)
	at org.renjin.primitives.R$primitive$is$matrix.apply(R$primitive$is$matrix.java:28)
	at org.renjin.eval.Context.evaluateCall(Context.java:261)
	at org.renjin.eval.Context.evaluate(Context.java:193)
	at org.renjin.primitives.special.IfFunction.apply(IfFunction.java:40)
	at org.renjin.eval.Context.evaluateCall(Context.java:261)
	at org.renjin.eval.Context.evaluate(Context.java:193)
	at org.renjin.primitives.special.BeginFunction.apply(BeginFunction.java:46)
	at org.renjin.eval.Context.evaluateCall(Context.java:261)
	at org.renjin.eval.Context.evaluate(Context.java:193)
	at org.renjin.eval.Context.evaluate(Context.java:161)
	at org.renjin.sexp.Closure.doApply(Closure.java:108)
	at org.renjin.eval.ClosureDispatcher.apply(ClosureDispatcher.java:80)
	at org.renjin.eval.ClosureDispatcher.applyClosure(ClosureDispatcher.java:65)
	at org.renjin.sexp.Closure.apply(Closure.java:82)
	at org.renjin.eval.Context.evaluateCall(Context.java:261)
	at org.renjin.eval.Context.evaluate(Context.java:193)
	at org.renjin.invoke.codegen.ArgumentIterator.evalNext(ArgumentIterator.java:61)
	at org.renjin.primitives.R$primitive$sqrt.apply(R$primitive$sqrt.java:31)
	at org.renjin.eval.Context.evaluateCall(Context.java:261)
	at org.renjin.eval.Context.evaluate(Context.java:193)
	at org.renjin.invoke.codegen.ArgumentIterator.evalNext(ArgumentIterator.java:61)
	at org.renjin.primitives.R$primitive$$bracket.apply(R$primitive$$bracket.java:35)
	at org.renjin.eval.Context.evaluateCall(Context.java:261)
	at org.renjin.eval.Context.evaluate(Context.java:193)
	at org.renjin.primitives.special.AssignLeftFunction.assignLeft(AssignLeftFunction.java:60)
	at org.renjin.primitives.special.AssignLeftFunction.apply(AssignLeftFunction.java:44)
	at org.renjin.eval.Context.evaluateCall(Context.java:261)
	at org.renjin.eval.Context.evaluate(Context.java:193)
	at org.renjin.primitives.special.BeginFunction.apply(BeginFunction.java:46)
	at org.renjin.eval.Context.evaluateCall(Context.java:261)
	at org.renjin.eval.Context.evaluate(Context.java:193)
	at org.renjin.eval.Calls.applyClosure(Calls.java:71)
	at org.renjin.primitives.S3$GenericMethod.doApply(S3.java:584)
	at org.renjin.primitives.S3$GenericMethod.apply(S3.java:571)
	at org.renjin.primitives.S3.UseMethod(S3.java:43)
	at org.renjin.primitives.S3.UseMethod(S3.java:35)
	at org.renjin.primitives.R$primitive$UseMethod.doApply(R$primitive$UseMethod.java:77)
	at org.renjin.primitives.R$primitive$UseMethod.apply(R$primitive$UseMethod.java:31)
	at org.renjin.eval.Context.evaluateCall(Context.java:261)
	at org.renjin.eval.Context.evaluate(Context.java:193)
	at org.renjin.eval.Context.evaluate(Context.java:161)
	at org.renjin.sexp.Closure.doApply(Closure.java:108)
	at org.renjin.eval.ClosureDispatcher.apply(ClosureDispatcher.java:80)
	at org.renjin.eval.ClosureDispatcher.applyClosure(ClosureDispatcher.java:65)
	at org.renjin.sexp.Closure.apply(Closure.java:82)
	at org.renjin.eval.Context.evaluateCall(Context.java:261)
	at org.renjin.eval.Context.evaluate(Context.java:193)
	at org.renjin.eval.Context.evaluateExpressionVector(Context.java:252)
	at org.renjin.eval.Context.evaluate(Context.java:191)
	at org.renjin.script.RenjinScriptEngine.eval(RenjinScriptEngine.java:134)
	at org.renjin.script.RenjinScriptEngine.eval(RenjinScriptEngine.java:97)
	at RenjinMultivariateTest.test(RenjinMultivariateTest.java:74)

**Comment by cwlaird3** [comment]
Hi Alex,

Any updates or thoughts on this?

Thanks.

**Comment by akbertram** [comment]
@cwlaird3 this is fixed by PR #97 right? Can we close this?

**Comment by cwlaird3** [comment]
It is fixed.  Thanks.
